go-acme/lego

acme/client_test.go

Just a simple test to make sure a Client gets set up properly. It will have to be added to when more solvers are implemented.

Test NewClient

---

acme/client.go
acme/dvsni_challenge.go
acme/simple_http_challenge.go
acme/simple_http_challenge_test.go

This adds an implementation of CanSolve to SimpleHTTP and adds tests for it.

Finish SimpleHTTP and add tests

---

README.md

Took me a while to distill it down to this process - thanks for your help on Slack! Hopefully this can help others in the future.

Add bare-bones acme usage example

---

acme/client.go
acme/simple_http_challenge.go
acme/simple_http_challenge_test.go

This should prevent a few headaches in the future :sweat_smile:

Fix file descriptor leaks

---

acme/client.go
acme/client_test.go
acme/http_challenge.go
acme/http_challenge_test.go
acme/messages.go

This PR adds a solver for the HTTP-01 challenge to lego.
Fixes #24

Add the HTTP-01 challenge

---

README.md
acme/client.go
acme/client_test.go
acme/dvsni_challenge.go
acme/http_challenge_test.go
acme/messages.go
acme/tls_sni_challenge.go
acme/tls_sni_challenge_test.go

This WIP PR adds the TLS-SNI solver

Add TLS-SNI-01 Challenge

---

cli.go
cli_handlers.go

Add a way for cronjobs to automatically renew certificates.

---

acme/client.go
cli_handlers.go

Make sure the CLI returns proper non-zero exit codes on errors.

---

acme/error.go
acme/http_challenge.go
acme/http_challenge_test.go
acme/messages.go
acme/tls_sni_challenge.go

This PR changes the generic "The server could not validate our request" error message to something more informing :) Fixes #49.

Better challenge errors

---

acme/dns_challenge.go
acme/dns_challenge_cloudflare.go
acme/dns_challenge_cloudflare_test.go
acme/dns_challenge_manual.go
acme/dns_challenge_rfc2136.go
acme/dns_challenge_rfc2136_test.go
acme/dns_challenge_route53.go
acme/dns_challenge_route53_test.go
acme/dns_challenge_test.go

Modular dns-01 challenge providers

---

acme/client.go
cli_handlers.go

Added proper SAN awareness to RenewCertificate
Fixes #54

Fix: renew dropping additional DNSNames

---

acme/crypto.go

This will make it more convenient and easier for servers to update their OCSP stapling at the correct time.

Return full, parsed ocsp response instead of just the status

---

acme/client.go
acme/crypto.go
acme/http.go
acme/http_challenge_test.go
acme/http_test.go
acme/jws.go
acme/tls_sni_challenge_test.go
cli.go

Also a couple miscellaneous vet fixes.
Tried to be complaint with http://tools.ietf.org/html/rfc7231#section-5.5.3

Implement custom User-Agent string

---

acme/crypto.go

I was confused when I couldn't successfully do GetOCSPForCert when the same bundle was successfully used to start a TLS listener.
This method more closely reflects how crypto/tls does it here: https://golang.org/src/crypto/tls/tls.go?s=5139:5210#L174
Even though extra newlines at the end of a PEM file may not be technically correct input, crypto/tls is generous, and this way feels a little bit cleaner too.

Fix PEM decoding if file ends with multiple newlines

---

acme/dns_challenge_route53.go

Kind of a followup to #79 (you beat me to it):
Apparently Route53 never returns more than 100 zones even if we request a higher count. This PR makes sure that we get all available zones when there are more then 100.

Making sure we get all zones from Route53

---

acme/dns_challenge_digitalocean.go
acme/dns_challenge_digitalocean_test.go
acme/dns_challenge_rfc2136_test.go
acme/http.go
acme/http_challenge.go
acme/tls_sni_challenge.go

Also a few vet/lint fixes and improved some error messages. Closes #65

Add DigitalOcean DNS provider

---

README.md

It looks like it was merged in 602aeba6c1abc035f4f17a4e6863f616aa574c24. Am I correct?

Mark DNS challenge as completed in the README

---

acme/dns_challenge_dnsimple.go

While running a few tests, I discovered two bugs: one related to the use of subdomains, and the other related to a very subtle edge case with multiple records.
Each bug is described in the corresponding commit message, along with the successful test message.

Fix bugs with subdomains

---

account.go
acme/client.go
acme/client_test.go
acme/crypto.go
acme/crypto_test.go
acme/dns_challenge.go
acme/dns_challenge_test.go
acme/http_challenge.go
acme/http_challenge_test.go
acme/jws.go
acme/messages.go
acme/tls_sni_challenge.go
acme/tls_sni_challenge_test.go
cli.go
cli_handlers.go
configuration.go
crypto.go

This is a WIP.
If you have any suggestions or questions, let me know :)

Add EC support

---

README.md
cli.go

Nothing major; just a few minor updates.

Update README and version

---

providers/dns/gandi/gandi.go
providers/dns/gandi/gandi_test.go

Commit 8512fab modified the cloudflare, dnsimple and route53 providers to use the `acme.FindZoneByFqdn` function. This commit makes the corresponding change to the Gandi provider.
Benefits are a small reduction in code size and keeping code style similar to the other providers.

Gandi DNS: use acme.FindZoneByFqdn function

---

README.md

The usage output seems to have drifted and was causes confusion when
attempting to use as a reference.

Update README usage Section

---

README.md

Update README sudo section to reflect addition of the `--dns` flag.

Update README sudo section

---

providers/dns/digitalocean/digitalocean.go

It looks like there's been enough refactoring so that my last PR is unnecessary. Here's a quick fix using the new solution.
I'll go ahead and close the other PR

DigitalOcean uses FindZoneByFqdn

---

acme/dns_challenge.go
cli.go
cli_handlers.go

Add dns-timeout support.

---

account.go

Write account.json without executable bit set

---

cli.go
cli_handlers.go
providers/dns/dnsmadeeasy/dnsmadeeasy.go
providers/dns/dnsmadeeasy/dnsmadeeasy_test.go

👋 Here's a DNSProvider implementation for DNSMadeEasy (http://dnsmadeeasy.com/).

Add DNSProvider for DNSMadeEasy (http://dnsmadeeasy.com/)

---

cli.go
cli_handlers.go
configuration.go

Update import paths for cli package.

codegangsta is now called urfave.

---

acme/dns_challenge.go
acme/dns_challenge_test.go

Fix for https://github.com/xenolf/lego/issues/248

Correctly determine the zone for CNAME domains pointing to another zone

---

acme/client.go

quick little fix for outdated docs

Fix documentation for acme.NewClient

---

providers/dns/googlecloud/googlecloud.go

Fixes #257
Previously the google cloud provider assumed the domain being provided
was also the authoritative zone. This fix uses an acme function to
recursively lookup the authoritative zone for a provided domain.
This solves the same problem as https://github.com/xenolf/lego/pull/261 but doesn't require the extra flag.

Fix GoogleCloud DNS challenge to allow subdomains

---

acme/client.go

Let me know what you think of this fix. It seems straightforward enough, but I may have missed something. This change was tested and I've confirmed it fixes the issue for me. Want to double-check it for correctness? I'd love to get this out for the next Caddy release, like, tomorrow. :smile:

Skip challenges when authz is already valid

---

providers/dns/cloudflare/cloudflare.go

addresses https://github.com/xenolf/lego/issues/275

add txt and name to query params, remove Type check

---

cli.go
cli_handlers.go
providers/dns/pdns/README.md
providers/dns/pdns/pdns.go
providers/dns/pdns/pdns_test.go

Add PowerDNS provider

---

acme/client.go

This would have been good to know. :wink:

Document that challenge providers get replaced

---

.travis.yml
cli.go
cli_handlers.go
providers/http/memcached/README.md
providers/http/memcached/memcached.go
providers/http/memcached/memcached_test.go

This adds a memcached provider for use with nginx's memcached module.

add memcached provider

---

cli.go
cli_handlers.go
providers/dns/azure/azure.go
providers/dns/azure/azure_test.go

This is a first attempt at a working Azure DNS challenge provider.
Fixes #180

Azure DNS Provider

---

cli.go
cli_handlers.go
providers/dns/exoscale/exoscale.go
providers/dns/exoscale/exoscale_test.go

Add support for Exoscale DNS provider

Add Exoscale DNS provider

---

cli.go
cli_handlers.go
providers/dns/dnspod/dnspod.go
providers/dns/dnspod/dnspod_test.go

Add dns provider for dnspod.
Dnspod provides domain name services in China.

Add dns provider for dnspod

---

providers/http/memcached/memcached.go

There is a small issue where the package desc doesn't reflect the package name.

Fix invalid package name

---

acme/client_test.go
acme/jws.go

Do not lock on http request, lock only on datastructure changes. @xenolf WDYT?

Reduce nonce locking

---

acme/error.go
acme/jws.go

Add an error type and one off retry for nonce errors.
closes #339

Fix nonce error

---

README.md

Thumbs up to @DeltaEvo for creating the AUR package.

Add lego installation via package manager for ArchLinux

---

acme/jws.go

https://github.com/xenolf/lego/issues/359

Add error checking for the jws httpPost

---

providers/dns/dnsimple/dnsimple.go
providers/dns/dnsimple/dnsimple_test.go

Hi again! Since last PR (#363), we recognised that error messages needed to be tweaked for the sake of usability.
Would you mind to merge this PR with these small adjustments? Thank you.

Update error messages for DNSimple provider

---

providers/dns/azure/azure.go

fixing problem after changes in github.com/Azure/go-autorest

fixed #389 

---

cli.go
providers/dns/dns_providers.go
providers/dns/otc/mock.go
providers/dns/otc/otc.go
providers/dns/otc/otc_test.go

Add DNS Provider for the german Open Telekom Cloud (OTC).
https://cloud.telekom.de/infrastruktur/open-telekom-cloud/

Add DNS Provider for otc

---

providers/dns/exoscale/exoscale.go

Fix for issue: #429 
@carlwgeorge - Ran into this at about the same time. :)

handle move of egoscale to exoscale

---

providers/dns/exoscale/exoscale.go

some changes were made to the egoscale library, required by the dns provider. There were mostly made to please golint.
Cheers,

exoscale: update to latest egoscale version

---

acme/http.go

Use proxies from environment when making outbound http connections

---

providers/dns/pdns/pdns.go

Fix PowerDNS zone URL, add leading slash

---

cli.go
providers/dns/cloudxns/cloudxns.go
providers/dns/cloudxns/cloudxns_test.go
providers/dns/dns_providers.go

Add DNS Provider for [CloudXNS](https://www.cloudxns.net/Index/index.html?l=en-us).
[API Document](https://www.cloudxns.net/Support/detail/id/1361.html) (Chinese version only)

Add DNS Provider for CloudXNS

---

cli.go
providers/dns/dns_providers.go
providers/dns/exoscale/exoscale.go
providers/dns/lightsail/lightsail.go
providers/dns/lightsail/lightsail_integration_test.go
providers/dns/lightsail/lightsail_test.go
providers/dns/lightsail/testutil_test.go

Support for DNS provider: Lightsail
#459

Support for DNS provider: Lightsail

---

cli.go
providers/dns/dns_providers.go
providers/dns/namedotcom/namedotcom.go
providers/dns/namedotcom/namedotcom_test.go

This PR adds Name.com as a provider for the DNS challenge.

add Name.com provider

---

providers/dns/dyn/dyn.go

If Dyn responds with a 3xx or 4xx status code, information describing exactly
what went wrong is generally included in the body of the response (as part of
the typical Dyn JSON response). On the other hand, if Dyn responds with a 5xx
status code, we very likely have extremely limited information.
This commit modifies the reporting to display the explanatory messages included
in the body of the Dyn response for 3xx and 4xx status codes. The intent is to
make it much easier to determine what might be going wrong (when something is
going wrong).

Slightly improve Dyn DNS provider error reporting.

---

cli.go
providers/dns/dns_providers.go
providers/dns/glesys/glesys.go
providers/dns/glesys/glesys_test.go

This is a solver that interacts with the GleSYS API to solve DNS-01 challenges.

Add DNS-01 solver using the GleSYS API

---

acmev2/client.go
acmev2/messages.go

This fixes #514. I didn't add tests because it doesn't seem that tests for ACMEv2 are in a working state yet.

Fixed CN regression in ACMEv2.

---

.gitignore

```
• GETTING AND VALIDATING GIT STATE
• releasing v0.5.0, commit 084e2809343d58a1555ae668e0f87219f9a33a92
⨯ release failed after 0.02s error=git is currently in a dirty state:
?? .gitcookies
Script failed with status 1
failed to deploy
```

Ignore gitcookies.

---

.gometalinter.json
.travis.yml
Makefile
acme/client.go
cli_handlers.go
providers/dns/cloudflare/cloudflare.go
providers/dns/pdns/pdns.go
providers/dns/rackspace/rackspace_test.go

Add linters

---

CHANGELOG.md
README.md

- `CHANGELOG.md` update for release
- Fixes for `README.md`

Prepare release v1.0.0

---

providers/dns/pdns/README.md

according to https://doc.powerdns.com/authoritative/domainmetadata.html#soa-edit-api the correct meta field name is SOA-EDIT-API

SOA-API-EDIT should be SOA-EDIT-API

---

providers/dns/gcloud/googlecloud.go

While performing some initial tests to convert to V2 and fully utilize lego, we experienced cases where the `TXT` challenge records were not getting cleaned up. Our assumption was due to the large number of records we have under a single zone results in the current call which gets all records to not be returned due to it being paged. 
I updated `findTxtRecords` to use the same logic from `Present` when pulling any existing records and then updated `Present` and `ClanUp` to both use the function. 
We've pulled in this change internally and have performed several tests and no longer experience the issue with `TXT` challenge records lingering around.

gcloud: update findTxtRecords to use Name=fqdn and Type=TXT

---

providers/dns/ns1/ns1.go

NS1 API works with zones, so `acme.FindZoneByFqdn` must be used to determine the authoritative zone instead of assuming the supplied domain is a zone root.

NS1: use the authoritative zone and not the domain name

---

cli_handlers.go

Exclude TLS ALPN for some CLI arguments

---

Gopkg.lock

fix: for dep v0.5.0.

---

cli.go
providers/dns/dns_providers.go
providers/dns/netcup/client.go
providers/dns/netcup/client_test.go
providers/dns/netcup/netcup.go
providers/dns/netcup/netcup_test.go

Add support for netcup DNS API
when providing according credentials, live tests worked

Add DNS Provider for netcup

---

acme/client.go

Panic on generating a certificate

---

acme/client_test.go
acme/crypto_test.go
acme/dns_challenge.go
acme/dns_challenge_test.go
acme/http_challenge_test.go
acme/http_test.go
acme/tls_alpn_challenge_test.go

Use Testify.

---

providers/dns/cloudxns/client.go
providers/dns/cloudxns/client_test.go
providers/dns/cloudxns/cloudxns.go

Client isolation to facilitate testing.
Fixes #619

CloudXNS: client isolation.

---

log/logger.go

Use an interface for logger, it's a good practice :smiley:

Use an interface for logger.

---

providers/dns/azure/azure.go
providers/dns/gcloud/googlecloud.go
providers/dns/iij/iij.go

dns providers: fix errors.

---

acme/client.go
acme/dns_challenge.go
providers/dns/gcloud/googlecloud.go
providers/dns/gcloud/googlecloud_test.go

Append existing TXT record to the new TXT record.
Fixes #641

Fix: gcloud wildcard

---

providers/dns/ns1/ns1.go
providers/dns/ns1/ns1_test.go

Fix the bug:
```
ns1: ns1: dns: domain must be fully qualified
```
Related to https://github.com/containous/traefik/issues/3871 and #463

ns1: fix getHostedZone.

---

README.md

Correct example of renew action with days flag

---

acme/dns_challenge.go
providers/dns/ns1/ns1.go

- invalid body when create.
- update TXT record instead of create if needed.
- better logs.
Fixes #653

ns1: fix challenge.

---

platform/config/env/env.go
platform/config/env/env_test.go
providers/dns/cloudflare/cloudflare.go

Cloudflare: support for CF_API_KEY and CF_API_EMAIL

---

providers/dns/namecheap/client.go
providers/dns/namecheap/namecheap.go
providers/dns/namecheap/namecheap_test.go

- simplification of the provider code
- client separated from the provider
- fix wildcard + san
Related to https://github.com/containous/traefik/issues/3977#issuecomment-427645511

namecheap: fix challenge

---

providers/dns/bluecat/bluecat.go
providers/dns/cloudxns/cloudxns.go
providers/dns/dnspod/dnspod.go
providers/dns/glesys/glesys.go
providers/dns/sakuracloud/sakuracloud.go

- config was not use in all the provider
- typo in bluecat provider

Fix some provider bugs

---

providers/dns/duckdns/duckdns.go
providers/dns/duckdns/duckdns_test.go

fix issue #626 by always converting url to subdomain.duckdns.org
Fixes #626

duckdns: fix subsubdomain

---

CHANGELOG.md
README.md

- `CHANGELOG.md` update for release
- Fixes for `README.md`

Prepare release v1.1.0

---

acme/client.go
acme/client_test.go
acme/http.go

Thanks to Pebble strict mode :1st_place_medal: 
Fixes #694

Support POST-as-GET.

---

.dockerignore
CHANGELOG.md
Dockerfile
Makefile
README.md

- `CHANGELOG.md` update for release
- Fixes for `README.md`
- new Docker image build system.

Prepare release v1.2.0

---

Dockerfile

fix: Docker image.

---

Makefile
acme/api/internal/sender/useragent.go
internal/release.go

- fix: missing version
- add release helper commands

Release helper

---

challenge/resolver/prober.go

Due to an invalid naming, some errors are not handled as expected.
Fixes #734

fix: errors management in the prober.

---

.golangci.toml
providers/dns/gcloud/googlecloud.go
providers/dns/gcloud/googlecloud_test.go

- fix duplicate RR
- add tests

gcloud: fix duplicate RR

---

CONTRIBUTING.md

Adds a guide to make a pull request.

contrib: adds a guide to make a pull request.

---

providers/dns/transip/transip.go
providers/dns/transip/transip_test.go

The Transip API doesn't allow to add a record without update all the zone/domain records. 
In some case, this produce a race condition.
See https://github.com/containous/traefik/issues/4346
**Note:** a wildcard certificate is the best way to handle this case.

transip: concurrent access to the API.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.0.0

---

.travis.yml
acme/api/internal/secure/jws.go
acme/api/order_test.go
challenge/resolver/solver_manager_test.go
providers/dns/auroradns/auroradns.go
providers/dns/cloudflare/cloudflare.go
providers/dns/dnspod/dnspod.go

Updates golangci-lint and applies updated rules.

chore: updates golangci-lint.

---

cmd/cmd_dnshelp.go
providers/dns/gcloud/googlecloud.go

- https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application
- https://github.com/golang/oauth2/blob/36a7019397c4c86cf59eeab3bc0d188bac444277/google/default.go#L61-L76

gcloud: More detailed information about Google Cloud DNS.

---

providers/dns/alidns/alidns.go

alicloud: fix pagination.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.1.0

---

challenge/dns01/dns_challenge.go
challenge/http01/http_challenge.go

Log wildcard domain correctly in validation

---

.golangci.toml
.travis.yml
acme/api/certificate_test.go
acme/api/internal/nonces/nonce_manager_test.go
acme/api/internal/secure/jws_test.go
acme/api/internal/sender/sender_test.go
certificate/certificates_test.go
providers/dns/azure/azure_test.go
providers/dns/netcup/internal/client_test.go
providers/dns/nifcloud/internal/client_test.go
providers/dns/otc/mock_test.go
providers/dns/rackspace/rackspace_test.go
providers/dns/stackpath/stackpath_test.go
providers/dns/vegadns/vegadns_test.go
registration/registar_test.go

Updates golangci-lint and applies updated rules.

chore: update golangci-lint.

---

certcrypto/crypto.go
cmd/accounts_storage.go
cmd/flags.go
cmd/setup.go

fix: CLI and key type.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.2.0

---

providers/dns/vscale/internal/client.go

Fixes the same issue as in #803 but for Vscale 
Manual testing:
```
dig +short test.lego.freak.click A                                                                                                                               
95.213.158.178
```
```
./lego -m dstdfx@gmail.com --dns vscale -s https://acme-staging-v02.api.letsencrypt.org/directory -d "test.lego.freak.click" run                                 Fri Feb 22 11:33:29 2019
2019/02/22 11:33:34 [INFO] [test.lego.freak.click] acme: Obtaining bundled SAN certificate
2019/02/22 11:33:35 [INFO] [test.lego.freak.click] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/cGVjytfhOMbnjP2vjhwhyBSYmxcL0Q6VEKuD88v7EDU
2019/02/22 11:33:35 [INFO] [test.lego.freak.click] acme: Could not find solver for: tls-alpn-01
2019/02/22 …
```

vscale: getting sub-domain

---

providers/dns/hostingde/client.go
providers/dns/hostingde/hostingde.go
providers/dns/hostingde/model.go

* wait for zone status after update (needed if you add more than one CN)
* fix an error if customer does not have access to dns-groups

bugfix hostingde client fails if customer has no access to dns-groups

---

providers/dns/oraclecloud/oraclecloud.go

OracleCloud: ttl config and timeout 

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.3.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.4.0

---

providers/dns/cloudns/cloudns.go
providers/dns/cloudns/internal/client.go
providers/dns/cloudns/internal/client_test.go

~~If I understand correctly the "not clear" documentation of ClouDNS, the List records operation returns an array: https://www.cloudns.net/wiki/article/57/~~
related to https://github.com/containous/traefik/issues/4772
ping @tzakrajs

cloudns: fix TTL and status validation

---

Dockerfile

Add tzdata to the Docker image.
Fixes #862

Add tzdata to the Docker image.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.5.0

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_exec.md
docs/content/dns/zz_gen_godaddy.md
docs/content/dns/zz_gen_hostingde.md
docs/content/dns/zz_gen_httpreq.md
providers/dns/exec/exec.toml
providers/dns/godaddy/godaddy.toml
providers/dns/hostingde/hostingde.toml
providers/dns/httpreq/httpreq.toml

Adds some missing information (resolve TODO).

doc: adds some missing information.

---

challenge/dns01/dns_challenge_manual.go

manual: serial behavior.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.6.0

---

providers/dns/vegadns/vegadns_test.go

Simplify and homogenize tests.

vegadns: refactor  tests.

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_cloudflare.md
platform/config/env/env_test.go
providers/dns/cloudflare/cloudflare.toml

Add better documentation about env vars.

Improve Cloudflare documentation.

---

certificate/authorization.go

fix: confusing message.

---

registration/registar.go

Too early deprecation.

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_joker.md
providers/dns/joker/client.go
providers/dns/joker/client_test.go
providers/dns/joker/joker.go
providers/dns/joker/joker.toml
providers/dns/joker/joker_test.go

joker: support username and password.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.7.0

---

providers/dns/vultr/vultr.go

vultr: invalid record type.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.7.1

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v2.7.2

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.0.1

---

.golangci.toml
challenge/http01/domain_matcher.go
challenge/http01/domain_matcher_test.go
challenge/http01/http_challenge_server.go
challenge/http01/http_challenge_test.go
cmd/flags.go
cmd/setup_challenges.go
docs/content/usage/cli/_index.md

feat: ease operation behind proxy servers

---

docs/content/dns/zz_gen_dreamhost.md
providers/dns/dreamhost/dreamhost.toml

Add example command to dreamhost provider docs.

dreamhost: Add CLI example

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.1.0

---

.golangci.toml
.travis.yml
acme/api/internal/sender/sender.go
acme/api/internal/sender/sender_test.go
challenge/dns01/dns_challenge_test.go
challenge/dns01/nameserver_test.go
challenge/http01/domain_matcher.go
cmd/cmd_renew_test.go
cmd/zz_gen_cmd_dnshelp.go
internal/dnsdocs/dns.go.tmpl
platform/config/env/env_test.go
providers/dns/alidns/alidns.go
providers/dns/cloudxns/internal/client_test.go
providers/dns/conoha/internal/client_test.go
providers/dns/dnsimple/dnsimple_test.go
providers/dns/easydns/easydns_test.go
providers/dns/iij/iij_test.go
providers/dns/joker/client_test.go
providers/dns/linodev4/linodev4_test.go
providers/dns/netcup/internal/client.go
providers/dns/netcup/internal/client_test.go
providers/dns/nifcloud/internal/client_test.go
providers/dns/otc/mock_test.go
providers/dns/rackspace/rackspace.go
providers/dns/selectel/internal/client.go
providers/dns/vscale/internal/client.go

Update golangci-lint to v1.21.0.
The version is define in the Travis settings.

chore: update linter.

---

acme/api/api.go
acme/api/certificate.go
acme/commons.go
acme/errors.go
certificate/certificates.go
challenge/challenges.go
challenge/tlsalpn01/tls_alpn_challenge.go
challenge/tlsalpn01/tls_alpn_challenge_server.go

Update ACME RFC links from draft to RFC8555.

Update ACME RFC links from draft to RFC8555.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_autodns.md
providers/dns/autodns/autodns.toml

Prepare release v3.2.0

---

e2e/challenges_test.go

Remove some debug code in e2e tests.
I forgot to delete this line in one of my previous PRs.

Remove some debug code in e2e tests.

---

acme/api/account.go
e2e/challenges_test.go
registration/registar.go

Close https://github.com/go-acme/lego/issues/443

Add support to update account

---

providers/dns/dreamhost/dreamhost.go

dns/dreamhost: fix GoDoc

---

certcrypto/crypto.go

This code is borrowed from the standard library; seemed like a good approach. Also adds support for ed25519 keys.
fix #1029

Successfully parse private key PEM blocks

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.3.0

---

go.mod
go.sum
providers/dns/dnspod/dnspod.go

Design improvements of the lib.
https://github.com/nrdcg/dnspod-go/compare/v0.3.0...nrdcg:v0.4.0

Update dnspod lib.

---

docs/content/dns/zz_gen_ovh.md
providers/dns/ovh/ovh.toml

The setup is not trivial and I had to scavenge this information from #233 to figure out what to do.
This will hopefully help others that are trying to the same.
Note: I am only guessing that this is the right way to add DNS provider documentation. I have written the PR in the GitHub web editor, because I have no idea how to test it. I don't see why it shouldn't work, but please check if it syntactically makes sense. The instructions themselves work, I have just used them to renew my certificates.

ovh: Improve provider documentation

---

.golangci.toml
acme/api/api.go
providers/dns/checkdomain/checkdomain.go
providers/dns/checkdomain/client.go
providers/dns/selectel/internal/client.go
providers/dns/vscale/internal/client.go
providers/dns/zoneee/zoneee_test.go

- update golangci-lint configuration
- minor changes.

Minors changes

---

.travis.yml
cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_servercow.md
providers/dns/dns_providers.go
providers/dns/servercow/internal/client.go
providers/dns/servercow/internal/client_test.go
providers/dns/servercow/internal/fixtures/records-01.json
providers/dns/servercow/internal/model.go
providers/dns/servercow/internal/model_test.go
providers/dns/servercow/servercow.go
providers/dns/servercow/servercow.toml
providers/dns/servercow/servercow_test.go

Add DNS provider for Servercow.
https://cp.servercow.de/client/plugin/support_manager/knowledgebase/view/34/dns-api-v1/7/
Fixes #990

Add DNS provider for Servercow.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.4.0

---

.travis.yml
go.mod
providers/dns/checkdomain/checkdomain_test.go
providers/dns/httpreq/httpreq_test.go
providers/dns/zoneee/zoneee_test.go

- ci: drop go1.13
- ci: add go1.14
- update golangci-lint (in Travis)

Update to go1.14

---

challenge/http01/http_challenge.go
challenge/resolver/prober.go
challenge/tlsalpn01/tls_alpn_challenge.go

lib: Improve cleanup log messages.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.5.0

---

providers/dns/alidns/alidns.go

I'm using a domain with punycode, and caught error like this when using dns01 challenge to alicloud:
```
docker run -it --rm -e ALICLOUD_ACCESS_KEY=xxx -e ALICLOUD_SECRET_KEY=xxx goacme/lego -d test.xn--punycode1.xn--punycode2 --dns alidns -m xxx@xxx.com --accept-tos --dns.resolvers 223.5.5.5:53 run 
2020/03/18 14:51:18 No key found for account xxx@xxx.com. Generating a P384 key.
2020/03/18 14:51:18 Saved key to /.lego/accounts/acme-v02.api.letsencrypt.org/xxx@xxx.com/keys/xxx@xxx.com.key
2020/03/18 14:51:19 [INFO] acme: Registering account for xxx@xxx.com
!!!! HEADS UP !!!!
Your account credentials have been saved in your Let's Encrypt
configuration directory at "/.lego/accounts".
You should make a secure backup of this folder now. This
configuration directory will also contain …
```

alicloud: add support for domain with punycode

---

docs/content/usage/cli/_index.md

fix: broken link to port usage section.

---

docs/content/dns/zz_gen_namedotcom.md
providers/dns/namedotcom/namedotcom.toml

Improve Name.com documentation

---

providers/dns/rimuhosting/rimuhosting.go
providers/dns/zonomi/zonomi.go

Use HTTP client from configuration.

rimuhosting: use HTTP client from config.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.6.0

---

cmd/cmd_run.go

Fixes #1122.
I've also applied a little formatting by inserting new lines between paragraphs.

Fix account storage location warning message

---

cmd/cmd_renew.go

fix: review path information.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.7.0

---

.goreleaser.yml

binaries: Add MIPS arch.

---

docs/content/dns/_index.md

doc: fix example of env vars file.

---

providers/dns/alidns/alidns.go
providers/dns/arvancloud/arvancloud.go
providers/dns/dnsimple/dnsimple.go
providers/dns/dnspod/dnspod.go
providers/dns/godaddy/godaddy.go
providers/dns/namedotcom/namedotcom.go
providers/dns/ovh/ovh.go
providers/dns/sakuracloud/client.go
providers/dns/vultr/vultr.go

- arvandcloud: fix: record name. 
- transform `extractRecordName`  method to a simple function.

arvandcloud: fix: record name.

---

providers/dns/constellix/constellix.go
providers/dns/constellix/internal/fixtures/records-Search.json

https://api-docs.constellix.com/?version=latest#81003e4f-bd3f-413f-a18d-6d9d18f10201

constellix: fix search records API call.

---

providers/dns/stackpath/stackpath.go

stackpath: fix subdomain support.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.8.0

---

go.mod
go.sum
providers/dns/designate/designate.go
providers/dns/designate/designate_test.go

This PR adds support for `clouds.yml` with the Openstack provider.
Fixes: https://github.com/go-acme/lego/issues/1217

designate: add support for Openstack clouds.yaml

---

docs/content/dns/zz_gen_scaleway.md
providers/dns/scaleway/scaleway.toml

Fixes wrong dns provider code in docs example.

scaleway: fix example

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v3.9.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.0.1

---

docs/content/usage/cli/_index.md
docs/content/usage/cli/examples.md

Improve documentation

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.1.0

---

providers/dns/azure/azure.go

azure: fix target must be a non-nil pointer

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.1.1

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Preprare release v4.1.2

---

providers/dns/azure/azure.go

azure: fix error handling.

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.1.3

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_hyperone.md
providers/dns/hyperone/hyperone.toml

See changelog at https://github.com/go-acme/lego/releases/tag/v3.9.0 .

Add 'since' tag to HyperOne provider

---

providers/dns/pdns/client.go
providers/dns/pdns/client_test.go

pdns: URL request creation.

---

providers/dns/dnspod/dnspod.go
providers/dns/vultr/vultr.go

vult, dnspod: fix default HTTP timeout.

---

docs/content/dns/zz_gen_rfc2136.md
providers/dns/rfc2136/rfc2136.toml

This small patch adds an example to the RFC2136 provider.

Example for RFC 2136 provider

---

acme/api/internal/sender/useragent.go

Prepare release v4.2.0

---

certificate/certificates.go

Based on https://github.com/certbot/certbot/pull/8596
Fixes #1333

fix: preferred chain only match root name

---

providers/dns/mythicbeasts/mythicbeasts.go

Also snuck in a correction to the `MYTHICBEASTS_USERNAME` env var in a comment.
Fixes #1357

mythicbeasts: implement `ProviderTimeout`

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.3.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.3.1

---

providers/dns/exoscale/exoscale.go

This change fixes the `exoscale` DNS provider debug mode activation.

exoscale: fix DNS provider debugging

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_hostingde.md
providers/dns/hostingde/hostingde.go
providers/dns/hostingde/hostingde.toml
providers/dns/hostingde/hostingde_test.go

hostingde: autodetection of the zone name.

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_lightsail.md
providers/dns/lightsail/lightsail.toml

I was using the Lightsail provider and noticed that the documentation was lacking, so i added some description (based on route 53 documentation), hope can help others who will be using it in in the future :)

lightsail: improve documentation

---

docs/content/dns/zz_gen_ovh.md
providers/dns/ovh/ovh.toml

Hello,
Thanks for your project.
There is a typo in the documentation of OVH.

ovh: fix example in documentation

---

go.mod
go.sum
providers/dns/hurricane/hurricane.go
providers/dns/hurricane/internal/client.go
providers/dns/hurricane/internal/client_test.go

hurricane: add API rate limiter.

---

certcrypto/crypto.go
cmd/setup.go

csr: Support the type `NEW CERTIFICATE REQUEST`

---

providers/dns/simply/simply.go

Related to https://github.com/go-acme/lego/pull/1419#issuecomment-855426947

simply: fix Go doc.

---

CHANGELOG.md
README.md
acme/api/internal/sender/useragent.go

Prepare release v4.4.0

---

acme/api/api.go
go.mod
go.sum
providers/dns/dynu/internal/client.go
providers/dns/hostingde/client.go

- https://github.com/cenkalti/backoff/compare/v4.1.0...v4.1.1
related to #1428

lib: use permanent error instead of context cancellation

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_lightsail.md
docs/content/dns/zz_gen_route53.md
providers/dns/lightsail/lightsail.toml
providers/dns/route53/route53.toml

Make the Lightsail and Route53 documentation less confusing and more detailed.

aws: detailed credentials

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/new_dns_provider.yml

Add "How do you use lego?" section and improve some fields.

docs: improve issue forms.

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_alidns.md
providers/dns/alidns/alidns.go
providers/dns/alidns/alidns.toml
providers/dns/alidns/alidns_test.go

ECS instance RAM role w/ Go SDK: https://www.alibabacloud.com/help/doc-detail/66223.html

alidns: support ECS instance RAM role

---

go.mod
go.sum
providers/dns/desec/desec.go

https://github.com/nrdcg/desec/compare/v0.5.0...v0.6.0

desec: bump to v0.6.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.5.0

---

providers/dns/godaddy/godaddy.go
providers/dns/godaddy/internal/client.go
providers/dns/godaddy/internal/client_test.go
providers/dns/godaddy/internal/fixtures/errors.json
providers/dns/godaddy/internal/fixtures/getrecords.json
providers/dns/godaddy/internal/types.go

- extract the client to a package
- add tests on the client methods

godaddy: add tests on the client

---

go.mod
go.sum

Related to https://github.com/vinyldns/go-vinyldns/issues/80

vinyl: use tag for the API client

---

providers/dns/mythicbeasts/client.go
providers/dns/mythicbeasts/mythicbeasts.go

mythicbeasts: fix token expiration

---

challenge/http01/http_challenge_server.go
challenge/http01/http_challenge_test.go

Addresses #1471 (opened by me, not long ago)
The semantics aren't perfect, but it's functional. Very minor changes and impacts.
Tests didn't all pass, but mine did!
Related to  #1472

added uds capability to http challenge server

---

docs/content/dns/zz_gen_joker.md
providers/dns/joker/joker.toml

Related to https://github.com/go-acme/lego/issues/1166#issuecomment-705636476
Closes #1554

joker: explains user and password for SVC mode

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.6.0

---

docs/content/dns/zz_gen_httpreq.md
providers/dns/httpreq/httpreq.toml

docs: fix link in the httpreq page

---

cmd/cmd_renew.go

feat: add LEGO_CERT_PEM_PATH and LEGO_CERT_PFX_PATH

---

Makefile
providers/dns/rfc2136/rfc2136.go

related to https://github.com/go-acme/lego/discussions/1632

rfc2136: fix TSIG secret

---

.github/workflows/documentation.yml
.github/workflows/go-cross.yml
.github/workflows/pr.yml
.github/workflows/release.yml
go.mod

- split main workflow:
- documentation.yml
- pr.yml
- release.yml
- update to go1.17

chore: update CI

---

go.mod
go.sum

chore: update logrus

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_route53.md
providers/dns/route53/route53.go
providers/dns/route53/route53.toml

I also needed AssumeRole, so I supported #1647.
See the command result in the comment.
Fixes #1647

route53: add assume role ARN

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.7.0

---

cmd/cmd_renew.go
go.mod
go.sum

This aligns our behaviour with that of certbot.
- Issue: #1656
- Amends: #1657

cli/renew: skip random sleep if stdout is a terminal

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

**IMPORTANT**
2 commits:
Fixes #1667

Prepare release v4.8.0

---

docs/content/installation/_index.md

docs: update install from sources

---

providers/dns/njalla/internal/client.go
providers/dns/njalla/internal/client_test.go
providers/dns/njalla/internal/types.go
providers/dns/njalla/njalla.go

njalla: fix record id unmarshal error

---

.github/workflows/documentation.yml
.github/workflows/go-cross.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.golangci.toml
certcrypto/crypto_test.go
challenge/dns01/dns_challenge_manual_test.go
challenge/http01/domain_matcher.go
cmd/accounts_storage.go
cmd/certs_storage.go
e2e/loader/loader.go
go.mod
go.sum
platform/config/env/env.go
platform/config/env/env_test.go
providers/dns/acmedns/acmedns.go
providers/dns/bluecat/bluecat.go
providers/dns/cloudflare/cloudflare.go
providers/dns/cloudns/internal/client.go
providers/dns/designate/designate_test.go
providers/dns/hurricane/internal/client.go
providers/dns/joker/internal/dmapi/client.go
providers/dns/joker/provider_dmapi.go
providers/dns/lightsail/lightsail.go
providers/dns/oraclecloud/oraclecloud_test.go
providers/dns/route53/route53.go

- go1.18
- update linter
- use new go1.18 features

feat: update to go1.18

---

.github/workflows/pr.yml
.golangci.toml
providers/dns/clouddns/internal/client.go
providers/dns/cloudns/internal/client.go
providers/dns/digitalocean/client.go
providers/dns/dreamhost/client.go
providers/dns/dyn/client.go
providers/dns/gandiv5/client.go
providers/dns/glesys/client.go
providers/dns/joker/internal/dmapi/client.go
providers/dns/mydnsjp/client.go
providers/dns/mythicbeasts/client.go
providers/dns/namecheap/client.go
providers/dns/otc/client.go
providers/dns/safedns/internal/client.go
providers/dns/vercel/internal/client.go

Update golangci-lint to v1.49.0

chore: update linter

---

acme/api/internal/nonces/nonce_manager_test.go
acme/api/internal/secure/jws_test.go
providers/dns/luadns/luadns.go

luadns: fix cname support

---

.golangci.toml
challenge/dns01/dns_challenge.go
challenge/dns01/nameserver.go
challenge/dns01/nameserver_unix.go
challenge/dns01/nameserver_windows.go
docs/content/dns/_index.md
providers/dns/acmedns/acmedns_test.go
providers/dns/versio/versio_test.go

drop `LEGO_EXPERIMENTAL_CNAME_SUPPORT`

feat: take out CNAME support from experimental features

---

README.md
cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_yandex.md
providers/dns/yandex/yandex.toml

- https://github.com/go-acme/lego/pull/1715#issuecomment-1250371197
- https://github.com/go-acme/lego/issues/1693#issuecomment-1250363604
cc @paskal

docs: un-deprecate Yandex

---

providers/dns/oraclecloud/oraclecloud.go

This is necessary for CNAME records
Closes #1730

oraclecloud: use fqdn to resolve zone

---

CHANGELOG.md
providers/dns/duckdns/duckdns.go
providers/dns/duckdns/duckdns_test.go

duckdns: fix CNAME support

---

challenge/dns01/dns_challenge.go

cname: add log about CNAME entries

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.9.1

---

docs/content/dns/zz_gen_arvancloud.md
providers/dns/arvancloud/arvancloud.toml
providers/dns/arvancloud/internal/client.go
providers/dns/arvancloud/internal/fixtures/get_txt_record.json

arvancloud: replace arvancloud.com by arvancloud.ir

---

challenge/dns01/domain.go
challenge/dns01/domain_test.go
providers/dns/alidns/alidns.go
providers/dns/arvancloud/arvancloud.go
providers/dns/civo/civo.go
providers/dns/constellix/constellix.go
providers/dns/desec/desec.go
providers/dns/dnsimple/dnsimple.go
providers/dns/dnspod/dnspod.go
providers/dns/exoscale/exoscale.go
providers/dns/gandi/gandi.go
providers/dns/gandiv5/gandiv5.go
providers/dns/glesys/glesys.go
providers/dns/godaddy/godaddy.go
providers/dns/hetzner/hetzner.go
providers/dns/infomaniak/infomaniak.go
providers/dns/mythicbeasts/mythicbeasts.go
providers/dns/namedotcom/namedotcom.go
providers/dns/namesilo/namesilo.go
providers/dns/nearlyfreespeech/nearlyfreespeech.go
providers/dns/ovh/ovh.go
providers/dns/sakuracloud/client.go
providers/dns/servercow/servercow.go
providers/dns/stackpath/stackpath.go
providers/dns/tencentcloud/client.go
providers/dns/vkcloud/vkcloud.go
providers/dns/vultr/vultr.go
providers/dns/yandexcloud/yandexcloud.go
providers/dns/zoneee/zoneee.go

return an error when extracting record name instead of panic

fix: return an error when extracting record name

---

.github/workflows/documentation.yml
.github/workflows/go-cross.yml
.github/workflows/pr.yml
.github/workflows/release.yml

- upgrade actions/setup-go to v3
- upgrade actions/checkout to v3
- upgrade crazy-max/ghaction-github-pages to v3
- upgrade goreleaser/goreleaser-action to v3

chore: upgrade actions

---

acme/api/internal/secure/jws.go
acme/api/order_test.go
challenge/resolver/solver_manager_test.go
go.mod
go.sum
providers/dns/hyperone/internal/token.go

go-jose v2 is not actively developed anymore
https://github.com/square/go-jose/tree/master#go-jose
jose v3 is also looking for help but at least it should be maintained

update go-jose package to latest

---

providers/dns/pdns/client.go
providers/dns/pdns/pdns.go

Hello,
Fixes #1780
It should fix linked issue. What do you think about it ?

pdns: fix usage of notify only when zone kind is Master or Slave 

---

providers/dns/hetzner/internal/client.go
providers/dns/hetzner/internal/types.go

Superseeds #1813
Fix unexpected "could not get zone"-errors when there are more than 100 zones.

hetzner: improve zone ID detection

---

providers/dns/alidns/alidns.go

alidns: filter on record type

---

providers/dns/namesilo/namesilo.go

namesilo: add cleanup before add a DNS record

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.10.0

---

providers/dns/acmedns/acmedns.go

acmedns: fix CNAME support

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.10.1

---

certcrypto/crypto.go
cmd/flags.go
cmd/setup.go
docs/data/zz_cli_help.toml

which LetsEncrypt and other CAs support.

feat: add RSA 3072

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.11.0

---

cmd/certs_storage.go
cmd/certs_storage_test.go

fix: archive only domain-related files on revoke

---

docs/content/installation/_index.md

- add homebrew installation note

docs: add homebrew installation

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.12.0

---

providers/dns/dnsmadeeasy/internal/client.go

dnsmadeeasy: fix DeleteRecord

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.12.2

---

cmd/cmd_list.go

Fixes #1942
It's related to https://github.com/go-acme/lego/pull/1590

fix: list command

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.13.2

---

providers/dns/azuredns/azuredns.go

This PR fixes the bad AzureDNS provider configuration

azure: fix configuration from env vars

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.13.3

---

providers/dns/route53/route53.go

route53: avoid unexpected records deletion

---

providers/dns/pdns/internal/client.go

pdns: fix notify

---

docs/content/dns/zz_gen_edgedns.md
docs/content/installation/_index.md
providers/dns/edgedns/edgedns.toml

This PR fixes two broken links I spotted in the docu.

doc: fix broken links

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.14.0

---

go.mod
go.sum
providers/dns/bunny/bunny.go
providers/dns/bunny/bunny.toml

Save the bunny by placing it in the Nature Reserve.
https://github.com/nrdcg/bunny-go
https://github.com/nrdcg/bunny-go/compare/e11d9dc91f04...c9dda82568d9
Related to #2008

bunny: use NRDCG fork

---

providers/dns/bunny/bunny.go
providers/dns/bunny/bunny_test.go

bunny: fix zone detection

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.14.1

---

docs/content/dns/zz_gen_designate.md
providers/dns/designate/designate.toml

Added public Designate provider Fuga Cloud.

doc: update Designate documentation

---

platform/config/env/env.go
platform/config/env/env_test.go
providers/dns/liquidweb/liquidweb.go
providers/dns/liquidweb/liquidweb.toml

Related to https://github.com/go-acme/lego/pull/2031#issuecomment-1762962188

liquidweb: add LWAPI_ prefix for env vars

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_regru.md
providers/dns/regru/regru.go
providers/dns/regru/regru.toml

Added support for "reg.ru" DNS provider to additional authentication by SSL certificates pair

regru: client certificate support

---

providers/dns/constellix/constellix.go

constellix: follow rate limiting headers

---

providers/dns/desec/desec.go

desec: increase default propagation interval

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.15.0

---

.golangci.yml
certcrypto/crypto_test.go
certificate/authorization.go
challenge/dns01/nameserver.go
docs/Makefile
platform/tester/env.go
providers/dns/cloudxns/internal/client.go
providers/dns/constellix/constellix.go
providers/dns/edgedns/edgedns.go
providers/dns/oraclecloud/configprovider.go
providers/dns/yandexcloud/yandexcloud.go

chore: minor changes

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.16.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.16.1

---

providers/dns/dns_providers.go

https://github.com/go-acme/lego/issues/2013#issuecomment-2021553242

httpnet: add provider to NewDNSChallengeProviderByName

---

go.mod
go.sum
providers/dns/oraclecloud/configprovider.go
providers/dns/oraclecloud/oraclecloud.go
providers/dns/oraclecloud/oraclecloud_test.go

oracle: update API client

---

.golangci.yml
cmd/cmd_renew.go
docs/content/usage/cli/Obtain-a-Certificate.md
docs/content/usage/cli/Renew-a-Certificate.md

feat: fills LEGO_CERT_PFX_PATH and LEGO_CERT_PEM_PATH only when needed

---

certificate/renewal.go
certificate/renewal_test.go

feat: renewal retry after value

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_route53.md
providers/dns/route53/route53.go
providers/dns/route53/route53.toml
providers/dns/route53/route53_test.go

route53: adds option to not wait for changes

---

acme/api/renewal.go

chore: remove remaining deprecated ARI call

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.17.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.17.4

---

providers/dns/azure/azure.go
providers/dns/azure/private.go
providers/dns/azure/public.go
providers/dns/azuredns/azuredns.go
providers/dns/azuredns/private.go
providers/dns/azuredns/public.go
providers/dns/bunny/bunny.go
providers/dns/desec/desec.go
providers/dns/designate/designate.go
providers/dns/digitalocean/digitalocean.go
providers/dns/directadmin/directadmin.go
providers/dns/hostingde/hostingde.go
providers/dns/httpnet/httpnet.go
providers/dns/ovh/ovh.go
providers/dns/servercow/servercow.go
providers/dns/zoneee/zoneee.go

Minor change to have something more homogenous about zone name management.

chore: homogenous zone name env var management

---

go.mod
go.sum
providers/dns/vultr/vultr.go
providers/dns/vultr/vultr_test.go

Version v3 of the API ~~adds http.response to calls, add a function to report response code.~~
https://github.com/vultr/govultr/compare/v2.17.2...v3.9.0

chore: bump to github.com/vultr/govultr/v3

---

go.mod

`toolchain not available` issue:

chore: update go version inside go.mod

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.18.0

---

providers/dns/godaddy/godaddy.go
providers/dns/godaddy/internal/client.go
providers/dns/godaddy/internal/client_test.go
providers/dns/godaddy/internal/fixtures/error-extended.json
providers/dns/godaddy/internal/types.go

godaddy: fix cleanup

---

providers/dns/brandit/internal/client.go
providers/dns/nifcloud/internal/client.go
providers/dns/websupport/internal/client.go

Fixes #2273
https://github.com/go-acme/lego/pull/2274#issuecomment-2353028124

chore: use UTC instead of GMT when possible

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.19.0

---

CHANGELOG.md
acme/api/internal/sender/useragent.go

Prepare release v4.19.1

---

.github/workflows/go-cross.yml
challenge/dns01/nameserver.go

https://go.dev/doc/go1.23#syncpkgsync

fix: go1.22 compatibility

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_variomedia.md
providers/dns/variomedia/variomedia.toml

fix: variomedia documentation

---

providers/dns/limacity/limacity.go

limacity: fix error message

---

cmd/cmd_renew.go

chore: domain merge simplification

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

Prepare release v4.20.0

---

CHANGELOG.md

docs: improve changelog style

---

providers/dns/directadmin/directadmin.go

directadmin: fix timeout configuration

---

.github/workflows/release.yml
.goreleaser.yml

I added the `AUR_KEY` to the secrets.
https://aur.archlinux.org/packages/lego-bin

chore: publish aur lego-bin

---

.goreleaser.yml
CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

Related to https://github.com/go-acme/lego/pull/2358#issuecomment-2491426419
After checking the [goreleaser doc](https://goreleaser.com/customization/snapcraft/), There is not need for an explicit definition of the channels.

Prepare release v4.20.4

---

docs/content/usage/cli/Obtain-a-Certificate.md
docs/data/zz_cli_help.toml

Added some additional documentation based on #1754, to help others.

docs: add note about --dns.resolvers

---

providers/dns/infomaniak/infomaniak.go

infomaniak: increase default propagation timeout

---

providers/dns/azuredns/azuredns.go
providers/dns/azuredns/private.go
providers/dns/azuredns/public.go
providers/dns/azuredns/servicediscovery.go
providers/dns/bunny/bunny.go
providers/dns/bunny/bunny_test.go
providers/dns/huaweicloud/huaweicloud.go
providers/dns/internal/ptr/types.go
providers/dns/inwx/inwx.go
providers/dns/lightsail/lightsail_integration_test.go
providers/dns/route53/route53.go
providers/dns/route53/route53_integration_test.go
providers/dns/volcengine/volcengine.go

I created a package `ptr` to handle `pointer` and `deref` functions instead of having several implementations.

chore: shared deref and pointer functions

---

cmd/setup.go

Related to #2367
Related to #1546
Closes #1280

fix(cli): use retryable client for ACME server calls

---

providers/dns/netcup/netcup.go

Related to https://github.com/traefik/traefik/issues/11327

netcup: increase default propagation values

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

Prepare release v4.21.0

---

cmd/cmd_renew.go
cmd/cmd_run.go
cmd/flags.go
cmd/hook.go

- use constants for env vars related to flags
- move code related to hook

chore: use constants for env vars related to flags

---

.github/workflows/pr.yml
README.md
acme/api/order.go
acme/commons.go
certificate/certificates.go
cmd/cmd_renew.go
cmd/cmd_run.go
docs/content/_index.md
e2e/challenges_test.go
e2e/dnschallenge/dns_challenges_test.go
e2e/fixtures/pebble-config-dns.json
e2e/fixtures/pebble-config.json

Adds support for Profiles Extension
https://www.ietf.org/id/draft-aaron-acme-profiles-00.html
https://letsencrypt.org/2025/01/09/acme-profiles/
https://github.com/go-acme/lego/discussions/2400

feat: add support for Profiles Extension

---

challenge/http01/http_challenge.go
challenge/resolver/solver_manager.go
cmd/flags.go
cmd/setup_challenges.go
docs/data/zz_cli_help.toml

feat: add delay option for HTTP challenge

---

acme/api/order.go
acme/commons.go
acme/errors.go
certificate/certificates.go
certificate/certificates_test.go
challenge/resolver/solver_manager.go
challenge/resolver/solver_manager_test.go
registration/registar.go

fix: rewrite status management

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

Prepare release v4.22.1

---

providers/dns/acmedns/acmedns.go
providers/dns/acmedns/acmedns_test.go
providers/dns/acmedns/mock_test.go

Related to https://github.com/go-acme/lego/pull/2443#issuecomment-2663470866

acme-dns: use new registred account

---

.goreleaser.yml
CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

Prepare release v4.22.2

---

providers/dns/dnsimple/dnsimple.go

dnssimple: use GetZone

---

.github/ISSUE_TEMPLATE/feature_request.yml

Syntax error is preventing this template to be used while creating new issues.

chore: fix feature request template

---

challenge/resolver/solver_manager.go
challenge/tlsalpn01/tls_alpn_challenge.go
cmd/flags.go
cmd/setup_challenges.go
docs/data/zz_cli_help.toml

Similar to #2422 but for TLSALPN challenge.

feat: add delay option for TLSALPN challenge

---

acme/api/identifier.go
acme/api/identifier_test.go
acme/api/order.go

fix: check order identifiers difference between client and server

---

README.md

Correct extension for issue template is `.yml`.

chore: update link to create issue about new provider

---

providers/dns/mijnhost/mijnhost.go

mijnhost: improve record filter

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

**IMPORTANT**
The 2 commits must be kept: the merge must be done with a **rebase** (neither merge commit nor squash)
2 commits:

Prepare release v4.24.0

---

certificate/certificates.go
cmd/flags.go
cmd/setup.go
lego/client.go
lego/client_config.go

feat: add option to disable common name in CSR

---

.github/workflows/pr.yml
cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_zoneedit.md

Checks the generated files inside PRs

chore: check generated files

---

providers/dns/sakuracloud/sakuracloud.go

While waiting for a change in the API client, we can already change the constructor of the API client to gain 1.41 MB in binary size.
https://github.com/sacloud/iaas-api-go/issues/376

chore: use custom API client constructor for sakuracloud

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

**IMPORTANT**
The 2 commits must be kept: the merge must be done with a **rebase** (neither merge commit nor squash)
2 commits:

Prepare release v4.25.0

---

cmd/flags.go
docs/data/zz_cli_help.toml

Fixes https://github.com/go-acme/lego/discussions/2594

fix: wrong CLI flag type

---

challenge/dns01/fqdn.go
challenge/dns01/fqdn_test.go
providers/dns/auroradns/auroradns.go
providers/dns/gandi/gandi_test.go
providers/dns/gcloud/googlecloud.go
providers/dns/otc/internal/client_test.go
providers/dns/otc/internal/fixtures/zones-recordsets_POST-request.json
providers/dns/otc/otc_test.go
providers/dns/safedns/safedns.go
providers/dns/selectelv2/selectelv2.go
providers/dns/yandex360/yandex360.go

- Removes useless call to `DumpRequest`
- Replaces `dns01.ToFqdn` with `dns.Fqdn`

chore: clean up

---

docs/content/dns/zz_gen_azuredns.md
providers/dns/azuredns/azuredns.go
providers/dns/azuredns/azuredns.toml
providers/dns/azuredns/credentials.go

azuredns: pipeline credential support

---

cmd/zz_gen_cmd_dnshelp.go
docs/content/dns/zz_gen_selectelv2.md
providers/dns/selectelv2/selectelv2.go
providers/dns/selectelv2/selectelv2.toml
providers/dns/selectelv2/selectelv2_test.go

selectelv2: add missing options

---

CHANGELOG.md
acme/api/internal/sender/useragent.go
cmd/lego/zz_gen_version.go
providers/dns/internal/useragent/useragent.go

**IMPORTANT**
The 2 commits must be kept: the merge must be done with a **rebase** (neither merge commit nor squash)
2 commits:

Prepare release v4.26.0
