- acme/crypto_test.go
Even though the std lib does the heavy lifting, this should verify (somewhat) that the helper functions are working.
Better tests would involve replacing crypto/rand.Reader with a non-random Reader then comparing the contents to make sure the proper std lib crypto functions were called and their values returned.
> Basic tests for crypto wrapper functions

- README.md
- acme/client.go
- acme/client_test.go
- cli_handlers.go
Error handling can still be improved and cleaned up a bit, but this is a start. Since `acme` is a package that will be imported by other programs, I took out all the log.Fatal lines that kill the program and either returned the error or, where that wasn't immediately obvious how to do, replaced with log.Print.
> Replaced fatal with print; return errors from NewClient

- acme/client.go
- acme/client_test.go
- acme/error.go
- acme/simple_http_challenge.go
- acme/simple_http_challenge_test.go
My logic behind this change is basically this: a user of this library can set `acme.Logger` to something custom if they want to; otherwise it uses the default log.Logger instance. (Currently, acme package _never_ uses the standard log.Logger, which is causing problems in Caddy which uses that logger.)
Also, my next PR will clean up the log statements a bit, making them more consistent and also removing the superfluous `\n` at the end (the log package adds them for us, which is nice -- keeps our strings cleaner).
> Make acme.Logger optional; otherwise use standard log.Logger

- acme/messages.go
It enables (un)marshaling regr.json files used in official client.
> Add JSON tags to RegistrationResource as used in official client

- acme/client.go
- acme/client_test.go
The spec doesn't require /directory, so I think it's best left for the user to specify it. Better to change it now than later. Also improved some comments/docs and fixed a test.
> Don't try appending /directory to caURL

- acme/dns_challenge.go
https://github.com/letsencrypt/boulder/pull/1295 changed encoding of DNS record to base64url without padding.
> Base64 encode dns-01 record

- acme/client.go
An empty case in Go does not fallthrough to the next one.
> Add explicit fallthrough

- acme/challenges.go
- acme/client.go
- acme/client_test.go
- acme/dns_challenge.go
- acme/dns_challenge_cloudflare.go
- acme/dns_challenge_cloudflare_test.go
- acme/dns_challenge_manual.go
- acme/dns_challenge_rfc2136.go
- acme/dns_challenge_rfc2136_test.go
- acme/dns_challenge_route53.go
- acme/dns_challenge_route53_test.go
- acme/http_challenge.go
- acme/http_challenge_server.go
- acme/http_challenge_test.go
- acme/messages.go
- acme/provider.go
- acme/tls_sni_challenge.go
- acme/tls_sni_challenge_server.go
- acme/tls_sni_challenge_test.go
- configuration.go
This implements the last suggestion from #32 by @janeczku to separate solving the `http-01` challenge, from making the `keyAuth` available at the appropriate path.
This change creates a new interface
```go
type HTTPChallengeProvider interface {
PresentToken(domain, path, keyAuth string) error
CleanUp(domain, path string)
}
```
And a `httpChallengeServer` (extracted from `httpChallenge`) which implements that interface and is used by `Client`. 
I am looking to use `lego` as a library to generate certs and will need to have my own logic for making the token available, so the suggestion in #32 was quite useful.
@xenolf If you have any thoughts on this change (or suggestions on impelemtnation) i'm all ears.
> http-01: refactor provider for presenting token

- acme/dns_challenge.go
- acme/dns_challenge_cloudflare.go
- acme/dns_challenge_dnsimple.go
- acme/dns_challenge_dnsimple_test.go
This PR adds support for [DNSimple](https://dnsimple.com/) using the [DNSimple API](https://developer.dnsimple.com/) and the [DNSimple Go client](https://github.com/weppos/go-dnsimple).
For now there are unit tests for the initialization, and live integration tests for Present/CleanUp. I'm planning to add some integration tests that use a mock client, but I need to check a few things on the existing go client first.
---
In the implementation, I tried to reuse the same conventions of the existing DNS providers. I have a couple of questions related to this implementation:
1. In the tests, none of the clients tests the proper assignment of the credentials:
```go
func TestNewDNSProviderDNSimpleValid(t *testing.T) {
os.Setenv("DNSIMPLE_EMAIL", "")
os.Setenv("DNSIMPLE_API_KEY", "")
_, err := …
```
> Add DNSimple DNS support

- acme/dns_challenge.go
- acme/dns_challenge_test.go
We can ask the OS resolver for the IP of Google's public anycast DNS.
No need to "bootstrap" with literal IP address. The OS resolver knows
best about IPv4 ./. IPv6.
Mostly fixes #88.
> dns_challenge preCheckDNS: let system resolver decide IPv4 ./. IPv6.

- acme/dns_challenge.go
This is a very trivial change.
While debugging #90 I noticed that the message related to the DNS validation did not include the domain name (whereas the HTTP and TLS challenges do). This is very useful when multiple domains are requested, and the challenges for each domain are run in parallel.
I added the domain for consistency with the other two log messages.
> Add missing domain name for consistency

- acme/dns_challenge.go
- acme/dns_challenge_route53.go
- acme/dns_challenge_route53_test.go
Fixes:
- InvalidTXTRDATA error when creating TXT record (closes #94)
- Present() should poll and wait until the status of the record change becomes INSYNC (thanks @oov)
Adds a retry w/ timeout utility function that may be used in other places
> Route53 provider fixes

- README.md
Following up from #94 with additional docs!
> Add full CLI example and IAM policy for Route 53 to the README.

- acme/http.go
When a HEAD request failed, the error wasn't handled correctly causing the subsequent `Body.Close()` to panic.
```
2016/01/30 18:47:58 client.go:31: [INFO][redacted] acme: Obtaining bundled SAN certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4ed32f]
goroutine 14377 [running]:
github.com/xenolf/lego/acme.httpHead(0x8d57d0, 0x2e, 0x0, 0x2b21962ff5d8, 0xc2081be660)
/.../src/github.com/xenolf/lego/acme/http.go:37 +0x14f
github.com/xenolf/lego/acme.(*jws).getNonce(0xc2081bf6b0, 0x0, 0x0)
/.../src/github.com/xenolf/lego/acme/jws.go:74 +0x4a
github.com/xenolf/lego/acme.(*jws).Nonce(0xc2081bf6b0, 0x0, 0x0, 0x0, 0x0)
/.../src/github.com/xenolf/lego/acme/jws.go:85 +0x78 …
```
> Handle HEAD request errors

- README.md
The IAM policy in the README seemed like it would benefit from being shorter, which I accomplished as follows:
* `Sid` is optional and can be omitted for brevity.
* Both `route53:ListHostedZones` and `route53:GetChange` are effectively allowed for `*`, so they can be combined into a single statement.
* Actions can be specified on the same line as  `"Action": […]`, since the JSON is equivalent either way.
See [the README in my fork](https://github.com/willglynn/lego/tree/compact_iam_policy#aws-route-53) for a preview, and compare to [the README in master](https://github.com/xenolf/lego/blob/master/README.md#aws-route-53). `Resource: […]` could be combined too, but that would make the `<INSERT_YOUR_HOSTED_ZONE_ID_HERE>` line really long, so I left that as-is.
> Compact IAM policy

- acme/crypto.go
This issue came up on another project, see: https://github.com/mholt/caddy/pull/579
> GetOCSPForCert should fail if there are no OCSP servers in the cert.

- acme/dns_challenge_route53.go
- acme/dns_challenge_route53_test.go
AWS client tools commonly support passing credentials via `AWS_ACCESS_KEY_ID` + `AWS_SECRET_ACCESS_KEY`, but supporting only this is insufficient. For example, access key IDs provided by STS require passing in `AWS_SECURITY_TOKEN` as a third value, and EC2 instances are often provided dynamic credentials at runtime via the EC2 metadata service.
This changeset makes `lego` attempt to find credentials in the same way that the `aws` CLI tool attempts to find credentials. The result is even less auth code than before because `goamz` provides all this with `aws.GetAuth()`.
> Add support for additional AWS authentication sources

- acme/http_challenge_server.go
If TCP connection reuse (KeepAlives) are left on then, in a sequence
of challenges arising from a multiple-domain certficate, challenges
after the 1st can fail due to reusing the now defunct tcp connection
used in the first challenge. This has been observed when using the Go
standard library reverse proxy to forward the challenges to Lego.
Fixes #107
> http-01 challenge: disable TCP connection reuse

- README.md
I completely forgot that the Let's Encrypt staging endpoint exists (#110). Might be worth a mention in the README.
> Mention the Let's Encrypt staging endpoint in the README

- acme/dns_challenge.go
- acme/dns_challenge_route53.go
- acme/dns_challenge_test.go
Replaces #96 
* Gets a list of all authoritative nameservers by looking up the NS RRs for the root domain (zone apex)
* Verifies that the expected TXT record exists on all nameservers before sending off the challenge to ACME server
> Refactor DNS check

- acme/dns_challenge_rfc2136.go
- acme/dns_challenge_rfc2136_test.go
- cli_handlers.go
The TSIG algorithm is currently hardcoded as HMAC-MD5. Any other key type cannot be used. Let's add an environment variable that allows to pass through the pseudo domain name used for the HMAC type.
Also append the default DNS port to the target nameserver to be updated, in case none is specified. This is caused by the Go API wanting to know the port for the connection, but we know a sensible destination default.
> Allow to customize the TSIG algorithm and allow to omit the DNS port

- README.md
- cli.go
- cli_handlers.go
This irks me, particularly because challenge selection is non-deterministic:
$ AWS_PROFILE=… AWS_REGION=us-east-1 lego -m … --dns=route53 --server=https://acme-stang.api.letsencrypt.org/directory -d foo.willglynn.com run
2016/02/11 19:48:49 [INFO][foo.willglynn.com] acme: Obtaining bundled SAN certificate
2016/02/11 19:48:49 [INFO][foo.willglynn.com] acme: Trying to solve HTTP-01
2016/02/11 19:48:49 [foo.willglynn.com] Could not obtain certificates
[foo.willglynn.com] error presenting token: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied
If I say `lego --dns=foo`, I want `lego` to solve a DNS challenge. That's why I told it which provider I want it to use when solving a DNS challenge.
The commit below makes `--dns=foo` also imply `-x http-01 -x …
> --dns=foo means we specifically intend to fulfill a DNS challenge

- acme/dns_challenge_cloudflare.go
- acme/dns_challenge_cloudflare_test.go
Since there is no officially maintained (or widely accepted) library for CloudFlare it is better to implement the API calls using just the standard net/http library.
> Refactor CloudFlare DNS provider to have no 3rd party dependencies

- acme/dns_challenge.go
In #133 I was seeing unnecessary delays in checking/confirming the DNS propagation for my Gandi challenge provider. 
When I examined `checkDNSPropagation` I found that it was exiting
early if the TXT record could not be found on the recursive
nameserver, and thus the authoritative nameservers were not being
queried until after the record showed up on the recursive nameserver
causing the delay.
If I am understanding things correctly (a big if!) if the recursive nameserver returns not found for the CNAME check we should just press on and examine the authoritative nameservers. This commit does that and it *appears* to fix my problem.
Is this correct? Thoughts?
> DNS Challenge: Fix handling of CNAMEs

- cli_handlers.go
> CLI: Give helpful error message if --http/--tls is given without colon

- README.md
- acme/dns_challenge.go
- acme/dns_challenge_rfc2136.go
- acme/dns_challenge_rfc2136_test.go
- acme/dns_challenge_test.go
- cli.go
- cli_handlers.go
- Removal of RFC2136_ZONE from help text
- Query nameserver directly to find zone we have to update
- During insert, make sure the new record is the ONLY challenge.
(I had a few panics, hence 3 challenges left. Not good.)
> Issue/140: Using RFC2136 dns challenge does not allow me to create multi domain certs.

- acme/provider.go
Just a tiny change to the comment for `ChallengeProvider`. There was a missing period in-between the sentences. While I was at it, I also added a small introductory sentence.
> Improve wording of ChallengeProvider comment

- acme/dns_challenge.go
- acme/provider.go
There was what I perceived as a problem with my Gandi `ChallengeProvider` in #133. Because of Gandi's long DNS record propagation time (in my tests, up to 25 minutes), I had to alter the timeout the `acme` package used when checking for record propagation. However, this affected **all** the DNS providers, the remainder of which just require the existing 30 second timeout. Forcing them all to have a 40 minute timeout for the sake of Gandi seemed... wrong?
This PR adds a new `ChallengeProviderTimeout` type to the acme package which allows for implementing DNS providers that require an unsually long timeout when checking for record propagation. In fact, although it would only be necessary for DNS providers like Gandi at present, it need not be solely for DNS providers. There could be in the …
> Add ChallengeProviderTimeout type to acme package

- cli.go
As more dns providers are being added, the lego help text is getting increasingly difficult to read.  It will get continually more cluttered as new providers are added.
This change moves DNS provider (--dns) help to a separate 'dnshelp' command and elaborates on how to use the dns provider (including an example).
> Add a separate 'dnshelp' command.

- cli.go
- cli_handlers.go
- providers/dns/googlecloud/dns_challenge_googlecloud.go
- providers/dns/googlecloud/dns_challenge_googlecloud_test.go
Use GCE_PROJECT to designate your GCE project.
Authentication is automatically picked up from gcloud credentials if
running locally and from GCE metadata if run within Google Cloud.
Requires at least permission scope
"https://www.googleapis.com/auth/ndev.clouddns.readwrite"
> Add DNS challenge provider for Google Cloud DNS

- cli_handlers.go
- providers/dns/googlecloud/googlecloud.go
- providers/dns/googlecloud/googlecloud_test.go
Conventionally, the package name matches the last component of the import path.
Also, add package description.
> googlecloud dns: Make package name match import path

- cli_handlers.go
- providers/dns/cloudflare/cloudflare.go
- providers/dns/cloudflare/cloudflare_test.go
- providers/dns/digitalocean/digitalocean.go
- providers/dns/digitalocean/digitalocean_test.go
- providers/dns/dnsimple/dnsimple.go
- providers/dns/dnsimple/dnsimple_test.go
- providers/dns/dyn/dyn.go
- providers/dns/dyn/dyn_test.go
- providers/dns/gandi/gandi.go
- providers/dns/gandi/gandi_test.go
- providers/dns/googlecloud/googlecloud.go
- providers/dns/googlecloud/googlecloud_test.go
- providers/dns/namecheap/namecheap.go
- providers/dns/rfc2136/rfc2136.go
- providers/dns/rfc2136/rfc2136_test.go
- providers/dns/route53/route53.go
- providers/dns/route53/route53_test.go
Different DNS providers were handling credentials in different ways.
Some were reading credential environment variables in cli_handlers.go
and then passing them into the NewDNSProvider function, while others
were reading the environment variables within their NewDNSProvider
functions.
This change moves all credential environment handling into the
providers, thereby decentralizing the handling of credentials.
> Make DNS provider credential-handling more consistent.

- providers/dns/gandi/gandi.go
- providers/dns/gandi/gandi_test.go
Prior to 47219ad, the Gandi DNS tests ran in a separate package from the provider itself, called `gandi_test`. Following that commit they were changed to run in the provider's package.
The `Endpoint` variable was only exported in order to be usable from `gandi_test`. Since the tests now run in `gandi`, it should be unexported and its comment changed, since the comment is now inaccurate.
> Gandi DNS: Unexport Endpoint variable

- providers/dns/cloudflare/cloudflare.go
Updated timeout for cloudflare dns challenge record propagation to fix issue as described in https://github.com/xenolf/lego/issues/167
I haven't written a test, but the current value of 30 seconds isn't tested either. I'm not familiar enough with golang to do write it within reasonable time, so hope that's okay.
> Updated timeout for cloudflare dns challenge

- acme/dns_challenge.go
- acme/dns_challenge_manual.go
- providers/dns/cloudflare/cloudflare.go
- providers/dns/dnsimple/dnsimple.go
- providers/dns/route53/route53.go
I noticed that the CloudFlare lookup didn't lookup directly based on the zone name (which seemed silly).
I Adjusting lookupNameservers() to return the fqdn at point it finds the NS as this seemed like a better idea vs. making a new function to repeat the same process.
I also changed the other providers to use the new method vs. the suffix method. I've adjusted where appropriate for differing uses of FQDNs in zone names.
> Use zone name when talking to DNS APIs

- providers/dns/gandi/gandi_test.go
This adds a live test to the Gandi provider. It runs provided that both the environment variables GANDI_API_KEY and GANDI_TEST_DOMAIN are set. Otherwise the test is skipped.
In terms of what it does, it more or less just executes the example code in the README, using the Let's Encrypt staging server, and checks for failures along the way.
> Gandi DNS: add live test

- README.md
The example in README no longer compiles, due to new signature of `acme.NewClient` (taking a `KeyType`). This PR hopefully fixes that.
> Update README example section

- acme/jws.go
- acme/messages.go
Changes the import path for go-jose to pin to the `v1` branch (via gopkg.in). I maintain backwards-compatibility for the `v1` branch, whereas `master` can diverge over time. This is to make sure I don't end up breaking your build :-). Thanks.
> Build with go-jose.v1 (instead of master)

- README.md
- providers/dns/route53/fixtures_test.go
- providers/dns/route53/route53.go
- providers/dns/route53/route53_test.go
- providers/dns/route53/testutil_test.go
Fully backwards compatible in terms of credential mechanisms
(environment variables, shared credentials file, EC2 metadata).
If a custom AWS IAM policy is in use it needs to be updated with permissions
for the route53:ListHostedZonesByName action.
> Switch route53 provider to the official AWS SDK

- acme/error.go
This patch adds code to only parse the HTTP response body as JSON if the content-type header advertises the content as JSON. In my case, the directory server was unavailable: it returned a 503 HTTP response code with an HTML document, and the only thing lego reported was:
2016/04/04 19:12:56 Could not create client: get directory at 'https://acme-v01.api.letsencrypt.org/directory': invalid character '<' looking for beginning of value
This was caused by trying to parse the document body (HTML) as JSON, without looking at the content-type header and returning the JSON parse error.
Closes #181
> Only try to parse JSON documents

- acme/jws.go
Some time (near once per 50-100 certificates) lego fails with stack:
panic: runtime error: index out of range
goroutine 1906 [running]:
panic(0x8781a0, 0xc8200100b0)
C:/Go/src/runtime/panic.go:464 +0x3e6
github.com/xenolf/lego/acme.(*jws).Nonce(0xc820374300, 0x0, 0x0, 0x0, 0x0)
c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/jws.go:105 +0x176
gopkg.in/square/go-jose%2ev1.(*genericSigner).Sign(0xc8203923c0, 0xc8205a6240, 0x6b, 0x8b, 0x6d0778650c48, 0x0, 0x0)
c:/Users/Tim/Documents/go/src/gopkg.in/square/go-jose.v1/signing.go:157 +0x376
github.com/xenolf/lego/acme.(*jws).signContent(0xc820374300, 0xc8205a6240, 0x6b, 0x8b, 0x481c4b, 0x0, 0x0)
c:/Users/Tim/Documents/go/src/github.com/xenolf/lego/acme/jws.go:70 +0x1f5
github.com/xenolf/lego/acme.(*jws).post(0xc820374300, …
> Fix out of range

- acme/dns_challenge.go
- acme/dns_challenge_manual.go
- providers/dns/cloudflare/cloudflare.go
- providers/dns/digitalocean/digitalocean.go
- providers/dns/dnsimple/dnsimple.go
- providers/dns/gandi/gandi.go
- providers/dns/gandi/gandi_test.go
- providers/dns/rfc2136/rfc2136.go
- providers/dns/route53/route53.go
With regard to the issues seen in #179
* Logic to retry the DNS query up 3 times (respects truncated errors)
* Added an alternate recursive nameserver
* Logic to use alt NS after 1st failure (only when the default NS is used)
* Adjusted formatting of 2 errors to differentiate the returned error string
> Retry logic for dnsQuery

- providers/dns/dnsimple/dnsimple.go
Requesting a certificate using DNSimple provider results in the  following error:
> Error obtaining certificate: Error presenting token dns: domain must be fully qualified
> Fix broken DNSimple provider

- Dockerfile
I have modified the official Dockerfile and made two changes
- Each RUN instruction creates an additional layer in the docker image. Adding files in one RUN instruction and deleting it in another RUN instruction will not reduce the size of the image. I used a single RUN command so that all the package/file removal happens in the same command in which the package installation happens, so that no additional layers are created.
- Similar to RUN statement, ADD instruction also creates an additional layer. Using git clone in the RUN statement and deleting it within the same statement ensures that an additional layer with source files is not added.
> Optimized Dockerfile for smaller image size

- providers/dns/route53/route53.go
Fixes #192 
Route 53 allows multiple zones with the same name to co-exist in an account. The most common use case is a split-view DNS with one private and one public zone for the same domain name. This patch makes sure we don’t ever provision the authorization record to the private zone.
The other case where there are multiple public zones with the same name in the account is not covered here since this would require a bigger code change. It's also unclear whether that's a thing people actually do, so waiting for relevant issue reports before addressing this.
> Route 53: Make sure we don't provision to a private hosted zone

- providers/dns/dyn/dyn.go
Dyn provider was using incorrect zone in Present and Cleanup functions.
This uses FindZoneByFqdn() to find the correct zone for use in the
subsequent API calls.
> Fixes #199

- cli.go
When I made a typo in command line, e.g. `--emial` instead of `--email`. Lego printed general `Incorrect Usage.` message. I expected to see something more useful.
This patch report error from command line parser to log. In case above:
`2016/05/14 18:19:20 flag provided but not defined: -emal
`
> Report error from command line parser to user.

- cli.go
If you run the lego binary with sudo in a directory the user has no access to os.Getwd() will fail with a very missleading error message. It is currently not possible to use --path to set the working directory because the os.Getwd() check fails before you get the chance. This pull request should fix that.
How to reproduce:
`
sudo -i
cd /root
sudo -u nobody /tmp/lego --path="/tmp"
`
> Allow setting "--path" even if os.Getwd() fails

- acme/client.go
- acme/messages.go
This PR adds 2 new functions for registration support in `acme.Client`:
* `QueryRegistration`: This performs a POST on the client
registration's URI and gets the updated registration info.
* `DeleteRegistration`: This deletes the registration as currently
configured in the client.
The latter, while a part of the IETF draft, may not be 100% functional in LE yet, my tests showed that resources were still available after deletion. If anyone knows for sure would be nice to know :)
> reg: Add Query and Delete functions

- acme/tls_sni_challenge.go
- acme/tls_sni_challenge_server.go
Used by rsc.io/letsencrypt to get the challenge domain. Originally committed under rsc.io/letsencrypt/vendor and maintained original authorship as from https://github.com/rsc/letsencrypt/commit/2ba1dda8fd06c47af5847588616112a9bf93c346.
Addresses issues with vendoring rsc.io/letsencrypt, especially with godep, see
- #225 
- https://github.com/rsc/letsencrypt/issues/9
- https://github.com/docker/distribution/pull/1779
> Change TLS SNI Challenge Cert function to return domain

- acme/client.go
If a client tries to register and encounters a 409 (Conflict) response the client now uses the old registration provided in the Location header of the 409 response. This makes the registration a bit more robust.
> In case of conflict during registration, the old registration is now recovered

- cli.go
- cli_handlers.go
Using this with the default configuration of lighthttpd on an EdgeOS router from Ubiquiti that expects a .pem.  Adding a --pem option saves a few lines of script and directly generates the concatenated crt + key.
I could move the --pem option to under the run and renew commands.  Wasn't clear if there's a preference here.
> Add optional support for .pem output (.crt + .key)

- providers/dns/route53/route53.go
- providers/dns/route53/route53_integration_test.go
While more than likely never to come up in a real-world situation, during renewal integration testing a value of 120 seconds has proven to be too high (the old challenge record has not expired by the time the new one is created).
> providers/dns/route53: Adjust DNS challenge TTL to 10 seconds

- .gitignore
- cli.go
- cli_handlers.go
- providers/dns/ovh/ovh.go
- providers/dns/ovh/ovh_test.go
We add OVH DNS Provider.
To do that we use the official GO librairy https://github.com/ovh/go-ovh
To use the new extention, we must add the folowwing environment variable :
* OVH_ENDPOINT the endpoint API you should to call
* OVH_APPLICATION_KEY the application key
* OVH_APPLICATION_SECRET the application key
* OVH_CONSUMER_KEY the consumer key
To key all, you must to go on "https://eu.api.ovh.com/createToken/" and you must add some right:
* POST /domain/zone/*
* DELETE /domain/zone/*
All the API is documented here: https://api.ovh.com/console/#/domain
> Add OVH DNS provider

- providers/dns/googlecloud/googlecloud.go
Make a more efficient API call to only fetch the name of interest.
> Filter Google Cloud DNS List() calls

- acme/dns_challenge.go
- acme/dns_challenge_test.go
This PR exports the PreCheckDNS variable so that library users can handle the DNS check before ACME is notified a DNS challenge is ready. This is especially useful in tests.
Additional discussion in https://github.com/xenolf/lego/issues/259
> Export PreCheckDNS so library users can manage the DNS check in tests

- .travis.yml
Some dependencies evidently require Go 1.6 and newer; also Go 1.7 is out.
> Shift CI test to newer Go versions

- acme/jws.go
This PR adds sync.Mutex to jws, and locks/unlocks methods where j.nonce is edited. This fixes the [data race](https://golang.org/doc/articles/race_detector.html) during tests for ObtainCertificate.
> Add sync.Mutex to lock and unlock j.nonces

- cli.go
- cli_handlers.go
Closes #219 
The way urfave/cli handles slice arguments is a bit clumsy. ~~I've called the new flag `--dns-resolver` (singular) as you specify it multiple times on the command line e.g. `--dns-resolver="8.8.8.8:53" --dns-resolver="8.8.4.4:53"`~~
EDIT: on second thoughts, changed to `--dns-resolvers` to make it consistent with the other multi-value flags
> Allow custom DNS resolvers

- providers/http/webroot/webroot.go
The HTTP challenge files and directories probably shouldn't be world-writable.  This PR fixes that.
> Tighten permissions on challenge files and directories

- cli.go
- cli_handlers.go
- providers/dns/linode/linode.go
- providers/dns/linode/linode_test.go
As the subject says, I've added support for Linode as a DNS provider.  Confirmed it works on at least subdomains (www.example.com) by acquiring a certificate for one of my domains.  Bare domains (example.com) SHOULD also work as well, but are currently untested.
> Add support for Linode as a DNS provider.

- acme/messages.go
Fixed issue by removing unused recoveryKeyMessage struct
Issue appears in Go 1.8+ due to this improvement to vet:
https://go-review.googlesource.com/#/c/16704/
> Fix duplicate json tag in recoveryKeyMessage

- cli_handlers.go
- providers/dns/ns1/ns1.go
- providers/dns/ns1/ns1_test.go
Hi!
I'd like to be able to use this package with [NS1](https://nsone.com) as DNS provider.
I added integration with their REST API uning their official Go client: 
https://github.com/ns1/ns1-go
Please, let me know if there any anything else I need to do to see this Pull Request merged.
Thanks for putting all this code together! :raised_hands:
Signed-off-by: David Calavera <david.calavera@gmail.com>
> Add NS1 DNS provider.

- providers/dns/googlecloud/googlecloud.go
- providers/dns/googlecloud/googlecloud_test.go
When record already exists in gcloud we can't add a new record without removing the other one first. This is a simple fix that doesn't attempt to create multiple entries for the record but just removes the previous data.
fixes #218
> Remove existing records in gcloud

- cli.go
- cli_handlers.go
- providers/dns/rackspace/rackspace.go
- providers/dns/rackspace/rackspace_test.go
Initially written a while back but never got round to finishing the testing 🙊 (done so now!)
I will be continuing to dog-food this and can support it for the foreseeable future.
This also officially closes out #208
* Uses standard libraries
* Authenticates against Identity API before grabbing DNS Endpoint
* Includes mock API server for tests
> Adds support for Rackspace DNS

- cli_handlers.go
- providers/dns/dns_providers.go
- providers/dns/dns_providers_test.go
This avoids duplication of this mapping in lib clients 
Ex : https://github.com/containous/traefik/pull/738#issuecomment-258810469
> Extract from CLI the name -> DNS provider mapping

- acme/jws.go
Before read access to `nonces` field in jws structure (in `Nonces` method) was not synchronized and we were still able
to get `slice bounds out of range` panic when trying to "pop" value in `Nonces` method.
The race can be actually observed by running `Nonce` method multiple times in separate goroutines with th precondition is `len(jws.nonces) == 1`.
> Properly lock jws.nonces

- acme/client.go
- acme/messages.go
- cli_handlers.go
Also write it out to the file system when running "lego run"
Removed caching of the issuer certificate inside the acme client, since
it didn't appear to be used.
> add issuer certificate to CertificateResource

- README.md
The previous example left out the MustStaple argument.
> Fix example call to ObtainCertificate

- providers/dns/vultr/vultr.go
Fixes the build broken by Vultr library.
While updating the library I changed the DNS function names to satisfy golint, and through this "accidentally" broke lego.
This PR should fix that and work again with the vultr/lib master.
> fix Vultr API calls

- acme/client.go
- acme/error.go
- acme/jws.go
I noticed that the response body is not closed in the error case of waiting for a certificate to be issued: https://sourcegraph.com/github.com/xenolf/lego@ce8fb060cb8361a9ff8b5fb7c2347fa907b6fcac/-/blob/acme/client.go#L673-674
AFAIK the response body needs to be closed even if there isn't one or it is not read. We close it above if the response code is 201 or 202, but not 200 or anything else. I think this will fix that problem.
> Close response body in error case and close first one

- acme/client.go
- acme/client_test.go
If `links["next"] == ""` the early return does not send neither success, nor failure to outer code,
which leads to whole `getChallenges` method being stuck forever, cause it waits for either `resc` or `errc` to receive message.
> Do not get stuck when server accidentally starts responding with bad data

- acme/client.go
https://letsencrypt.org/docs/rate-limits/ says:
> The pending authorization objects are represented by URLs of the form https://acme-v01.api.letsencrypt.org/acme/authz/XYZ, and should show up in your client logs.
> Log authorization urls

- acme/client.go
When creating bulk certificates, we often hit the acme rate limiting which is defined to 20 requests per second against the new-authz endpoint.
This PR add a workaround.
Note: letsencrypt set the limit to 20rps, but after some testing it seems that using a value of 18 work better.
> Add sleeps for new-authz rate limits

- providers/dns/dnsimple/dnsimple.go
- providers/dns/dnsimple/dnsimple_test.go
Hi I work at DNSimple. We're helping OSS projects to migrate to our newer API clients.
I noticed that you are using `github.com/weppos/dnsimple-go`, which points to our deprecated API v1. This PR introduces `github.com/dnsimple/dnsimple-go`, our official client that points to our new API v2.
Read more at: https://blog.dnsimple.com/2016/12/api-v2-stable/
Thanks ✌️
> Use DNSimple official Go client

- acme/http.go
- acme/jws.go
The error raised by an "invalid nonce" response never appeared inside `jws.go`, but instead it was handled at `http.go`, so it makes sense to move the retry logic to that file. The previous code from `jws.go` had no effect and did not solve issues related to invalid nonces.
> Move nonce retry from jws to http

- cli.go
The help documentation still points to the old environment variable (`DNSIMPLE_API_KEY`) so attempts that use that fail with: `DNSimple OAuth token is missing`. 
This updates the help message with the correct key (`DNSIMPLE_OAUTH_TOKEN`).
> Update DNSimple instructions to use new env key

- providers/dns/rfc2136/rfc2136.go
I just spent an hour reading the RFCs trying to remember what was the difference between `TSIG_KEY` and `TSIG_SECRET`... turns out the KEY is actually the key *name* as set in the nameserver config.
So here's a description of the variables so I don't have to look that up again next time.
> Add description for RFC2136 env vars

- cli.go
- cli_handlers.go
- providers/dns/dns_providers.go
- providers/dns/googlecloud/googlecloud.go
Using a Service Account file allows us to operate easier in an automated environment. Service Account files can be obtained from GCP IAM. If the GCE_SERVICE_ACCOUNT_FILE env var is set, it is used for authentication.
We may discuss a fallback to NewDNSProviderCredentials if NewDNSProviderServiceAccount fails.
> RFC: providers/dns: add Service Account authorization option to gcloud

- cli.go
- providers/dns/route53/route53.go
- providers/dns/route53/route53_integration_test.go
- providers/dns/route53/route53_test.go
This commit adds support for specifying hosted zone ID via the environment variable `AWS_HOSTED_ZONE_ID`. If this is not specified, the previous discovery process is used.
This is useful in environments where multiple hosted zones for the same domain name are present in an account.
> dns/route53: Allow specifying hosted zone ID

- providers/dns/azure/azure.go
Azure DNS provider was failing because the authorization header was not provided when getting the zone information. 
- Removed the recordset client 
- Added BearerAuthorizer to the ZonesClient
> fix azure dns provider: added authorization to dns zones client

- cli_handlers.go
Fixes #445 
Check registration != nil before continuing with renew/revoke
> renew/revoke - don't panic on wrong account

- acme/dns_challenge.go
- acme/dns_challenge_test.go
They will not get anymore an error message saying
"Could not find the start of authority".
Finding the zone cut of a FQDN now only rely on the presence
of a SOA record. Indeed, in the context of an eTLD the
authority will be the eTLD itself so you need to continue
to recurse until you get an answer instead of cutting the search
when you find the public suffix of a domain.
Fixes #434
> Users of an effective top-level domain can use the DNS challenge

- providers/dns/dns_providers.go
- providers/dns/godaddy/godaddy.go
- providers/dns/godaddy/godaddy_test.go
This PR adds support for the DNS Provider: GoDaddy
As the GoDaddy does not allow to safely delete records, the cleanup method will override the record data with "null" instead.
> Support for DNS Provider: GoDaddy

- acme/dns_challenge.go
- acme/dns_challenge_test.go
CNAMEs cannot co-exist with SOA records so responses with
a CNAME should be skipped.
The `cross-zone-example.assets.sh.` is currently hosted by
me (@fd) and will continue to exist for as long as the assets.sh
domain exists. (The assets.sh domain is used as a CDN and is unlikely
to go away.)
See #330
> Fix zone detection for cross-zone cnames

- README.md
The `acme.NewClient` function's `caDirURL` argument is expected to be
the full path to the ACME server's directory endpoint. In the README
example of using Lego programmatically against a Boulder instance only
the hostname & port are provided but not the directory path:
`"http://192.168.99.100:4000"`
This produces an error like:
```
2018/01/15 14:34:06 get directory at 'http://192.168.99.100:4000': invalid
character '<' looking for beginning of value
```
when used verbatim with a Boulder container since the `/directory` path
is missing and the "What is an ACME server" HTML index page is 
returned instead of the JSON directory contents.
This commit updates the example to use:
`"http://192.168.99.100:4000/directory"`
Which allows the example code to work with Boulder as-intended.
> Add `/directory` to example `NewClient` caDirURL.

- cli.go
`getNameservers` in `dns_challenge.go` attempts to determine the system resolvers from `/etc/resolv.conf` before using the Google DNS servers. Correct the help text to reflect this.
I discovered this as part of investigating #461 (which turns out not to be a valid bug).
> cli: Correct help text for --dns-resolvers default

- providers/dns/azure/azure.go
Needs testing.
Attempts to fix https://github.com/xenolf/lego/issues/489
`go get` will not work on this repository until this PR is merged.
If you want to test it on my fork, you have to do some manual commands before `go get` in order to get the imports to work correctly. This works for me:
```
mkdir -p $GOPATH/src/github.com/xenolf && \
cd $GOPATH/src/github.com/xenolf && \
git clone https://github.com/jammm/lego && \
cd lego && \
go get ./
```
> providers/azure: Refactor to work with new Azure SDK version.

- cli.go
- providers/dns/dns_providers.go
- providers/dns/exec/exec.go
As discussed in #505, this commits adds a very simple DNS provider which calls out to an external program/script which must then add or remove the DNS record.
I'm not sure how much testing is required for such a simple provider, please advise.
Closes #505, supersedes #417
> Add DNS challenge provider 'exec'

- cli.go
- providers/dns/bluecat/bluecat.go
- providers/dns/bluecat/bluecat_test.go
- providers/dns/dns_providers.go
This is an implementation of DNS01 challenge provider using the Bluecat Proteus API for enterprise DNS management. See #482
> add support for DNS01 challenges on Bluecat DNS server

- providers/dns/route53/route53.go
Hi,
After encountering #458 in the context of https://github.com/vancluever/terraform-provider-acme, I've traced the cause back to the use of the deprecated session.New in route53. Using NewSessionWithOptions instead fixes the problem. (You still need to set AWS_SDK_LOAD_CONFIG=1, AWS_REGION and AWS_PROFILE, if applicable).
Cheers,
Johannes
> Use NewSessionWithOptions instead of deprecated New. Fixes #458.

- providers/dns/dnsimple/dnsimple.go
Fixes:
> /go/src/github.com/xenolf/lego/providers/dns/dnsimple/dnsimple.go:179:49: cannot use whoamiResponse.Data.Account.ID (type int64) as type int in argument to strconv.Itoa
> Fix dnsimple api

- providers/dns/azure/azure.go
- providers/dns/azure/azure_test.go
- providers/dns/cloudflare/cloudflare.go
- providers/dns/cloudflare/cloudflare_test.go
Just had a pretty rough time trying to determine which envvars were being surfaced to Caddy and which weren't when using systemd.
Thought that something like this might forgo someone the pain if they go through the same headache.
> Adding output of which envvars are missing in Cloudflare and Azure

- acme/client.go
In ACME draft 10+, section 8 lists the valid challenge status' as:
`status (required, string):  The status of this challenge.  Possible
values are: "pending", "processing", "valid", and "invalid".`
In acme/client.go the "processing" status is missing as a possible return value.
> Added 'processing' status as valid challenge status

- providers/dns/exec/exec.go
This adds a function NewDNSProviderProgram() to the exec provider that allows to set the program to run directly instead of via the environment variable. This is similar to how other providers allow to set their credentials.
> Allow passing the program to the exec provider directly

- acme/http.go
- acme/http_test.go
This PR updates `acme/http.go` to allow customizing the `*x509.CertPool` used by the `HTTPClient` by specifying the filepath of one or more custom CA certificates via the `LEGO_CA_CERTIFICATES` environment variable.
This allows developers to easily trust a non-standard CA when interacting with an ACME test server (e.g. [Pebble](https://github.com/letsencrypt/pebble)):
```
LEGO_CA_CERTIFICATES=~/go/src/github.com/letsencrypt/pebble/test/certs/pebble.minica.pem \
lego \
--server https://localhost:14000/dir \
--email foo@bar.com \
-d example.com \
run
```
Resolves #569
> ACME HTTP: Allow customizing HTTP client x509.CertPool

- README.md
- acme/challenges.go
- acme/client.go
- acme/client_test.go
- acme/crypto.go
- acme/crypto_test.go
- acme/tls_alpn_challenge.go
- acme/tls_alpn_challenge_server.go
- acme/tls_alpn_challenge_test.go
- cli.go
- cli_handlers.go
Adds support for the draft [TLS-ALPN-01](https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-01) challenge.
1. [Download, install, and run the latest pebble.](https://github.com/letsencrypt/pebble#install)
2. Until #571 is merged, you have to manually patch lego to allow it to interact with pebble's self signed certificates:
```diff
diff --git a/acme/http.go b/acme/http.go
index f45e7f8..ab10f88 100644
--- a/acme/http.go
+++ b/acme/http.go
@@ -1,6 +1,7 @@
package acme
import (
+	"crypto/tls"
"encoding/json"
"errors"
"fmt"
@@ -26,6 +27,9 @@ var HTTPClient = http.Client{
TLSHandshakeTimeout:   15 * time.Second,
ResponseHeaderTimeout: 15 * time.Second,
ExpectContinueTimeout: 1 * time.Second,
+		TLSClientConfig: &tls.Config{
+			InsecureSkipVerify: true,
+		},
},
}
```
3. Add `127.0.0.1 …
> TLS-ALPN-01 Challenge

- acme/tls_alpn_challenge.go
- acme/tls_alpn_challenge_server.go
Due to the difficulty of serializing/deserializing `tls.Certificate`.
Add a function to return PEM blocks.
> tls-alpn: add a function to return PEM blocks.

- acme/client.go
- acme/crypto.go
[ACME draft Section 7.4 "Applying for Certificate Issuance"](https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-7.4)
> Clients SHOULD NOT make any assumptions about the sort order of
> "identifiers" or "authorizations" elements in the returned order
> object.
Pebble respect this assumption and this produce some weird certificate where the CN is the not the CN but a random SAN.
> Don't trust identifiers order.

- acme/http.go
Allow to specify a CA server name (`LEGO_CA_SERVER_NAME`).
This a requirement when you are using Pebble with an external DNS server.
Related to https://github.com/letsencrypt/pebble/pull/139
> CA Server Name.

- Gopkg.lock
- cli.go
- providers/dns/dns_providers.go
- providers/dns/vegadns/vegadns.go
- providers/dns/vegadns/vegadns_test.go
- vendor/github.com/OpenDNS/vegadns2client/LICENSE
- vendor/github.com/OpenDNS/vegadns2client/client.go
- vendor/github.com/OpenDNS/vegadns2client/domains.go
- vendor/github.com/OpenDNS/vegadns2client/main.go
- vendor/github.com/OpenDNS/vegadns2client/records.go
- vendor/github.com/OpenDNS/vegadns2client/tokens.go
This adds dns provider vegadns.  See [VegaDNS-API](https://github.com/shupp/VegaDNS-API) for more information on the provider.  This has been in use at my employer for over a year, and is performing well.  I figured it was time to push it upstream.  Please let me know if you have any questions or concerns.
Here's example output from my run locally:
```console
$ go vet github.com/xenolf/lego/providers/dns/vegadns
$ golint -set_exit_status github.com/xenolf/lego/providers/dns/vegadns
$ go test -v -cover github.com/xenolf/lego/providers/dns/vegadns
=== RUN   TestVegaDNSNewDNSProviderFail
--- PASS: TestVegaDNSNewDNSProviderFail (0.00s)
=== RUN   TestVegaDNSTimeoutSuccess
--- PASS: TestVegaDNSTimeoutSuccess (0.00s)
=== RUN   TestVegaDNSPresentSuccess
2018/05/29 14:01:16 tmpHostname for i = 1: …
```
> Add DNS Provider for VegaDNS

- cli.go
- providers/dns/dns_providers.go
- providers/dns/nifcloud/client.go
- providers/dns/nifcloud/client_test.go
- providers/dns/nifcloud/nifcloud.go
- providers/dns/nifcloud/nifcloud_test.go
This PR adds [NIFCLOUD](https://cloud.nifty.com/service/dns.htm) as a provider for the DNS challenge.
Please review and merge it!
(NIFCLOUD is one of the most famous IaaS in Japan)
> Add DNS Provider for NIFCLOUD DNS

- acme/client.go
When testing the new ACME v2 code in lego, we found that issuer certificates were empty.  After communicating with Let's Encrypt, we learned that they are no longer providing the cert links in the headers.  This change fixes the issue in our testing.
* https://community.letsencrypt.org/t/acme-v2-no-up-link-in-response/64962
* https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-7.4.2
> Fix missing issuer certificates from Let's Encrypt

- README.md
The `--server` example used the ACME v1 staging URL. Lego defaults to ACME v2 and should show the ACME v2 staging URL in the README.
> README: Change staging URL example for ACME v2.

- providers/dns/duckdns/duckdns.go
This corrects a small bug that clears the IP address from the A record instead of clearing the TXT record.
Fixes #600
> DuckDNS: fix TXT record update url

- acme/client.go
- acme/dns_challenge.go
This implements a simple way to increase the speed and reliability of dns challenges in cases where there are multiple challenges needed. It does not parallelize anything, it just creates all of the txt records in a preliminary pass so that things can propagate while we perform validations on other records. By the time the first record is resolving and validated, hopefully the others will be as well, and the overall time to issue a certificate can be greatly reduced.
The implementation simply involves an additional `presolver` interface implemented only by the dns solver so far. The intent of the `PreSolve` method is to allow preliminary work to happen in the first phase, and then validation can happen in the second `Solve` phase. If a `solver` does not implement `presolver`, the …
> Submit all dns records up front, then validate serially

- platform/config/env/env.go
- platform/config/env/env_test.go
- providers/dns/route53/route53.go
- providers/dns/route53/route53_integration_test.go
- providers/dns/route53/route53_test.go
Following up from #588, this allows the default route53.Config to be created from values in the environment.
> Route53: Make it possible to configure from the env

- providers/dns/ovh/ovh.go
- providers/dns/route53/route53.go
- providers/dns/route53/route53_test.go
Bugfix
This PR aadds a error checking during the OVH client creation to avoid panic.
Related https://github.com/containous/traefik/issues/2736
> Check error to avoid panic due to nil client

- account.go
- cli.go
- cli_handlers.go
- configuration.go
- providers/http/webroot/webroot.go
The path is a package to manipulate pseudo paths. use path/filepath for physical paths. For example, backslash and slash is contained both in `--path` usage.
> Use path/filepath instead of path

- cli.go
- providers/dns/alidns/alidns.go
- providers/dns/alidns/alidns_test.go
change credentials environment variables `ALIDNS_API_KEY` and `ALIDNS_SECRET_KEY` to `ALICLOUD_ACCESS_KEY` and `ALICLOUD_SECRET_KEY`
Fixes #632
> Rename Alibaba DNS env var.

- providers/dns/gandiv5/client.go
- providers/dns/gandiv5/gandiv5.go
- providers/dns/gandiv5/gandiv5_test.go
This PR allows fixing behavior to generate certificates for a wildcard domain and its base name with the provider `gandi v5`.
Related to https://github.com/containous/traefik/issues/3977
Example: `*.foo.com, foo.com`.
> gandiv5: fix DNS Challenge

- CONTRIBUTING.md
:wave: Hi folks,
In @ldez's DNS provider API docs update (https://github.com/xenolf/lego/pull/662) the link for the ACME-DNS Go client points to the base ACME-DNS project repo instead of the "goacmedns" Go library repo. This PR fixes the link.
Thanks!
> contrib: fix ACME DNS Go client link

- providers/dns/cloudflare/cloudflare.go
Cloudfare api won't work if domain has dot suffix beause even you get zone list with suffix, it won't match the name because of the code below.
```go
func (api *API) ZoneIDByName(zoneName string) (string, error) {
res, err := api.ListZones(zoneName)
if err != nil {
return "", errors.Wrap(err, "ListZones command failed")
}
for _, zone := range res {
if zone.Name == zoneName {
return zone.ID, nil
}
}
return "", errors.New("Zone could not be found")
}
```
`zone.Name == zoneName` won't match because even you request with suffix, api response without suffix.
> cloudflare: removed dot suffix from authzone while searching for zone.

- providers/dns/dnsmadeeasy/client.go
- providers/dns/dnsmadeeasy/dnsmadeeasy.go
When dnsmadeeasy returns status code > 299 it also often returns a helpful diagnostic message inside the request body. This message used to be discarded. This PR makes a change to log this message along with the status code
> dnsmadeeasy: log response body on error

- acme/client.go
- acme/client_test.go
In legacy ACME there was a requirement to send a JWS body that contained a key authorization as part of all challenge initiation POSTs. LEGO presently maintains this behaviour and sends the entire challenge resource back to the server in each POST.
Since both the client and server can reconstitute the key authorization there is no need to send it (or the rest of the challenge) and modern ACME expects challenges to be [initiated with a JWS carrying the trivial empty JSON object](https://tools.ietf.org/html/draft-ietf-acme-acme-16#section-7.5.1) (`{}`):
> 
>   A client responds with an empty object ({}) to acknowledge that the challenge can be validated by the server.
Some ACME servers (e.g. Pebble in `-strict` mode) will reject all challenge POSTs that have a legacy JWS body.
This commit …
> Client: Do not send a JWS body when POSTing challenges.

- acme/tls_alpn_challenge.go
The latest versions of [draft-ietf-acme-tls-alpn](https://datatracker.ietf.org/doc/draft-ietf-acme-tls-alpn/) specify a different `idPeAcmeIdentifierV1` value than Lego is using presently. The old value had a conflict with an existing assignment.
This commit updates the idPeAcmeIdentifierV1 value to match draft-05 and updates any references to the draft RFC to use the latest draft number and fixes #688.
Before this fix running Lego master (with 1164f44) against a Pebble instance running with `-strict` results in a failed TLS-ALPN-01 challenge:
```
$> LEGO_CA_CERTIFICATES=$GOPATH/src/github.com/letsencrypt/pebble/test/certs/pebble.minica.pem LEGO_CA_SERVERNAME=localhost lego --domains test.com --server https://localhost:14000/dir --exclude=dns-01 --exclude=http-01 --tls :5001 …
```
> TLS-ALPN-01: Update idPeAcmeIdentifierV1, draft refs.

- providers/dns/conoha/conoha.go
ConoHa DNS provider could not handle some domains correctly.
I forgot to use `acme.FindZoneByFqdn()` .
Sorry for my mistake.
```
$ lego --dns conoha --server https://acme-staging-v02.api.letsencrypt.org/directory --email kazuki@6715.jp --domains 6715.jp --domains *.6715.jp --domains test.zone1.6715.jp --domains test.zone2.6715.jp run
2018/11/02 20:32:38 [INFO] [6715.jp, *.6715.jp, test.zone1.6715.jp, test.zone2.6715.jp] acme: Obtaining bundled SAN certificate
2018/11/02 20:32:39 [INFO] [*.6715.jp] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/wetUyGGz3v_nv8bEhfRXhnffwT8oyyzjANCNkW4JUM8
2018/11/02 20:32:39 [INFO] [6715.jp] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/5GjvejDhjuCtPk6NlVwf_kYCgiYZQ4y0EnGNVREnuQ0
2018/11/02 20:32:39 [INFO] …
```
> conoha: fix finding domain id

- providers/dns/cloudflare/cloudflare.go
fix: Cloudflare error.
```
runtime/debug.Stack(0x265ea80, 0x17, 0xc00017a390)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x21e5ca0, 0x4551d40)
/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89
github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc000749b68)
/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
panic(0x21e5ca0, 0x4551d40)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/cloudflare.(*DNSProvider).Present(0xc0005f9b60, 0xc00073c540, 0x17, 0xc00045cb40, 0x2b, 0xc00088aa20, 0x57, 0x0, 0xc0007493f8)
/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/cloudflare/cloudflare.go:134 …
```
> fix: Cloudflare error.

- acme/http.go
- acme/http_test.go
Also, remove "Go-http-client/1.1". In practice this added detail doesn't
wind up being useful in diagnosing problems, particularly since it can
be deduced from the xenolf-acme version.
> Add version to xenolf-acme in User-Agent.

- providers/dns/azure/azure.go
Needed to issue a cert for *.example.net (main) and example.net (san) where lego tries to update the same rset _acme-challenge.example.net for different TXT records.
> Azure: Do not overwrite existing TXT records

- .travis.yml
- e2e/loader/loader.go
- e2e/readme.md
Let's Encrypt move the challtestsrv from boulder to pebble (which is great).
**This change made by LE is breaking all our builds.**
- https://github.com/letsencrypt/boulder/pull/3980
- https://github.com/letsencrypt/pebble/pull/181
ping @cpu
> Use new challtestsrv.

- providers/dns/alidns/alidns.go
alicloud dns api returns only 20 domains once by default. I tried to add pagination support to handle more than 20 domains correctly, and it's works.
> alidns: add support to handle more than 20 domains

- Gopkg.lock
- challenge/dns01/dns_challenge.go
- challenge/dns01/precheck.go
- e2e/loader/loader.go
- platform/wait/wait.go
- platform/wait/wait_test.go
- providers/dns/gcloud/googlecloud.go
- providers/dns/nifcloud/nifcloud.go
- providers/dns/route53/route53.go
the gcloud API returns values with quotes, this produce some errors for wildcards.
```
time="2018-11-01T11:46:41Z" level=error msg="Error obtaining certificate: acme: Error -> One or more domains had a problem:\n[qa.mydomain.com] error presenting token: googlecloud: googleapi: Error 409: The resource 'entity.change.additions[0].rrdata[1]' named '\"VuOLZS3tfLfrOswFtV3mayqOYaz5PvQK16nJdgMdMez\"' already exists, alreadyExists\n"
time="2018-11-01T11:46:41Z" level=error msg="Unable to obtain ACME certificate for domains \"*.qa.mydomain.com,qa.mydomain.com\" : unable to generate a certificate for the domains [*.qa.mydomain.com qa.mydomain.com]: acme: Error -> One or more domains had a problem:\n[qa.mydomain.com] error presenting token: googlecloud: googleapi: Error 409: The resource …
```
> gcloud: fix for wildcard

- README.md
The latest version of the policy doesn't need any manual adjusting; it's fine to use as-is.
> Removed an outdated instruction

- providers/dns/gcloud/googlecloud.go
Currently if `GCE_SERVICE_ACCOUNT_FILE` is set, `GCE_PROJECT` is ignored. This PR changes the behavior to use `GCE_PROJECT` for the project in all cases, if it is set.
I believe in practice the most common scenario is that a provided service account file does not specify a project, which is the default when generating a service account key via gcloud CLI or web console. So this change helps avoid forcing users to add a project ID to their service account file by simply specifying `GCE_PROJECT` as I think a user would expect.
This change also allows a user to override a project id in a service account file, which is probably a less common scenario but is the use case described in #604.
To use the project ID from a service account file, the user simply specifies `GCE_SERVICE_ACCOUNT_FILE` …
> Use GCE_PROJECT for project always, if specified

- providers/dns/gcloud/googlecloud.go
Fixes a typo from #750 so that GCE_PROJECT is actually used.
> dns/gcloud: Fix check for GCE_PROJECT when using gcloud

- .travis.yml
- acme/api/internal/sender/useragent.go
https://travis-ci.org/xenolf/lego/jobs/477470638
```
Deploying application
• releasing using goreleaser 0.95.2...
• loading config file       file=.goreleaser.yml
• RUNNING BEFORE HOOKS
• GETTING AND VALIDATING GIT STATE
• releasing v2.0.0, commit 9b4afbb99869234b76f5a6b6e48fcb9111f207d7
• SETTING DEFAULTS 
• SNAPSHOTING      
• skipped                   reason=not a snapshot
• CHECKING ./DIST  
⨯ release failed after 0.10s error=dist is not empty, remove it before running goreleaser or use the --rm-dist flag
Script failed with status 1
```
> Prepare release v2.0.1

- acme/api/api.go
Sets the HTTP client to the `core`.
Fixes #758
> fix: OCSP, set HTTP client.

- providers/dns/nifcloud/internal/client.go
NIFCLOUD DNS api endpoint changed.
http://info.biz.nifty.com/cloud/2019/01/post-163.html
> Change NIFCLOUD DNS base url

- providers/dns/namecheap/namecheap.go
- providers/dns/namecheap/namecheap_test.go
When the list of records contains multiple times the same records, the provider panics:
```
Stack: goroutine 54 [running]:
runtime/debug.Stack(0x26c79d0, 0x17, 0xc00032dc20)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x2243120, 0x45fc290)
/go/src/github.com/containous/traefik/safe/routine.go:148 +0x89
github.com/containous/traefik/safe.OperationWithRecover.func1.1(0xc0009f5b30)
/go/src/github.com/containous/traefik/safe/routine.go:156 +0x56
panic(0x2243120, 0x45fc290)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/namecheap.(*DNSProvider).CleanUp(0xc00000cbb0, 0xc00039d740, 0x7, 0xc000732690, 0x2b, 0xc000be6ea0, 0x57, 0xc00039d738, 0x3) …
```
> namecheap: fix panic.

- cmd/cmd_dnshelp.go
- providers/dns/gcloud/googlecloud.go
- providers/dns/gcloud/googlecloud_test.go
Added the option to provide the gcloud service account as a string via the environment variable `GCE_SERVICE_ACCOUNT` in addition to the already available option to specify a filepath to a keyfile.
see #775
> option to specify gcloud service account json by env as string

- .dockerignore
as it seems to prevent docker builds:
```go build -v -ldflags '-X "main.version=f05aa4c241fd8b43da9dc8cab8c8965e5b3c1b55"' -o dist/lego ./cmd/lego/
cmd/accounts_storage.go:20:2: cannot find package "github.com/xenolf/lego/lego" in any of:
/go/src/github.com/xenolf/lego/vendor/github.com/xenolf/lego/lego (vendor tree)
/usr/local/go/src/github.com/xenolf/lego/lego (from $GOROOT)
/go/src/github.com/xenolf/lego/lego (from $GOPATH)
make: *** [Makefile:20: build] Error 1```
> removing `lego` from the dockerignore

- challenge/dns01/cname.go
- challenge/dns01/dns_challenge.go
- challenge/dns01/precheck.go
- providers/dns/acmedns/acmedns_test.go
It may be desirable to host the dns-01 challenge in a zone other than
the one where the challenge is presented. For example, when validating
a.example.com, the challenge may need to live on example.org.
This change resolves CNAMEs encountered when determining the FQDN of the
challenge, and replaces them with the alias.
This PR is based on the original work in #584.
Closes #584 #506
Related to #479
Co-authored-by: Gurvinder Singh <gurvinder.singh@uninett.no>
> Resolve CNAME when creating dns-01 challenge

- Gopkg.lock
- acme/api/api.go
- challenge/resolver/solver_manager.go
- vendor/github.com/cenkalti/backoff/LICENSE
- vendor/github.com/cenkalti/backoff/backoff.go
- vendor/github.com/cenkalti/backoff/context.go
- vendor/github.com/cenkalti/backoff/exponential.go
- vendor/github.com/cenkalti/backoff/retry.go
- vendor/github.com/cenkalti/backoff/ticker.go
- vendor/github.com/cenkalti/backoff/tries.go
- during tests, allow to support more than 90% of bad nonce with a minimum of attempts.
- before with the simple retry system (5 attempts): ~50%
- partial fix for #486 and #793
> Uses a jittered exponential backoff

- challenge/dns01/dns_challenge.go
- challenge/dns01/dns_challenge_test.go
- challenge/dns01/precheck.go
This allows a `lego` client to implement a fix for #770 by wrapping with a function that sleeps two minutes before calling the original function (using some closed-over metadata to keep track of how long each call actually needs to sleep).
I'll write tests if this is something you want to go forward with.
The following needs locking on `solveToken` and `solved` for concurrent use, but otherwise is the idea.
```go
var solveToken map[string]string
func getCert(client *lego.Client, domains []string) {
token := randomString()
for _, domain := range domains {
solveToken[domain] = token
}
request := certificate.ObtainRequest{
Domains: domains,
}
certs, err := client.Certificate.Obtain(request)
}
func main() {
client := ...
delay := 120 * time.Second
solved := make(map[string]bool)
solveToken = …
```
> Add a mechanism to wrap a PreCheckFunc

- providers/dns/selectel/internal/client.go
This PR fixes issue when domain that haven't been added in Selectel Domains API as "basic" domain in terms of [our API](https://blog.selectel.com/managing-domains-with-the-selectel-dns-api/) (for example, if just a "A" record was created, but we want to have an individual certificate for that) can't be fetched by its name and we can't set acme challenge TXT record for it. Instead of this, we could find it's "sub-domain" and set TXT record to that.
I've tested it out:
```
dig +short testing.dstdfx.space A                                                                                                                       
95.213.158.178
```
```
./lego -m dstdfx@gmail.com --dns selectel -s https://acme-staging-v02.api.letsencrypt.org/directory -d "testing.dstdfx.space" run …
```
> selectel: getting sub-domain

- providers/dns/ovh/ovh.go
After removing the challenge record from OVH, the zone itself
does not get refreshed and leaving the obsolete record in place.
Calling '/domain/zone/ZONE/refresh' after deleting the record will
apply the changes to the zone.
> OVH: Refresh zone after deleting challenge record

- cmd/cmd_renew.go
- cmd/cmd_renew_test.go
Adds a log when certificates are not renew.
Related to https://github.com/xenolf/lego/issues/816#issuecomment-470945090
> Adds log when no renewal.

- cmd/zz_gen_cmd_dnshelp.go
- internal/dnsdocs/dns.go.tmpl
The output of `./lego dnshelp` was missing `manual` as a DNS provider.
> Add 'manual' provider to the output of dnshelp

- README.md
> README: fix link to library usage docs.

- providers/dns/hostingde/hostingde.go
To get the correct hosting.de-ZoneConfig the `ZoneName` provided via `HOSTINGDE_ZONE_NAME` needs to be used in a `ZoneConfigsFindRequest`.
When using a domain provided with `--domains` instead, the API-request returns an empty `ZoneConfig` if the `ZoneName` is different from the exact domain requested (eg. requesting a cert for `something.yourdomain.com` with zoneName `yourdomain.com`).
> Use provided ZoneName instead of domain for hostingde

- providers/dns/gcloud/googlecloud.go
fqdn is used for the TXT record, but not to find the zone. This breaks LEGO_EXPERIMENTAL_CNAME_SUPPORT for gcloud.
> Use fqdn to get zone in gcloud Present/CleanUp

- providers/dns/exec/exec.go
When requesting wildcard cert with SAN (--domains example.com
--domains *.example.com) I noticed 2 different TXT records are presented
in short succession, then one of them overwrites the other, and
eventually one of the authorizations fails.
Based on what other DNS providers do, I think Sequential() is required in
exec provider, too.
> exec: serial behavior

- platform/config/env/env.go
- platform/config/env/env_test.go
> Strip newlines when reading environment variables from `_FILE` suffixed files.

- providers/dns/digitalocean/client.go
- providers/dns/digitalocean/digitalocean.go
With this patch LEGO_EXPERIMENTAL_CNAME_SUPPORT will work on digitalocean as dns provider
> digitalocean: LEGO_EXPERIMENTAL_CNAME_SUPPORT support

- cmd/cmd_dnshelp.go
- cmd/zz_gen_cmd_dnshelp.go
- internal/dnsdocs/dns.go.tmpl
A better use of the `tabwriter`.
before:
```
Configuration for Cloudflare.
Code: 'cloudflare'
Since: 'v0.3.0'
Credentials:
- "CLOUDFLARE_API_KEY": API key
- "CLOUDFLARE_EMAIL": Account email
Additional Configuration:
- "CLOUDFLARE_HTTP_TIMEOUT": API request timeout
- "CLOUDFLARE_POLLING_INTERVAL": Time between DNS propagation check
- "CLOUDFLARE_PROPAGATION_TIMEOUT": Maximum waiting time for DNS propagation
- "CLOUDFLARE_TTL": The TTL of the TXT record used for the DNS challenge
```
after:
```
Configuration for Cloudflare.
Code:   'cloudflare'
Since:  'v0.3.0'
Credentials:
- "CLOUDFLARE_API_KEY":  API key
- "CLOUDFLARE_EMAIL":    Account email
Additional Configuration:
- "CLOUDFLARE_HTTP_TIMEOUT":         API request timeout
- "CLOUDFLARE_POLLING_INTERVAL":     Time between DNS …
```
> CLI help indentation.

- providers/dns/otc/client.go
As described in #902, OTC DNS Provider fails with timeout when sending an empty body.
This patch fixes the problem for me.
Fixes #902
> Prevent sending empty body in OTC DNS Provider

- docs/content/installation/_index.md
I have created a FreeBSD port for lego, easing installation on that platform. This PR adds install instructions for FreeBSD.
> Add install instructions for FreeBSD ports

- providers/dns/vultr/vultr.go
This will address #939 where the TXT value needs to be encapsulated in quotes. This is a quick fix to address the issue at hand. 
However in the long term I will look into updating the API or GoVultr itself to handle this more gracefully.
Fix  #939
> vultr: quote TXT record

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_cloudflare.md
- providers/dns/cloudflare/cloudflare.go
- providers/dns/cloudflare/cloudflare.toml
- providers/dns/cloudflare/cloudflare_test.go
To limit the scope of operations that can be performed, add support for API tokens (currently in public beta) to be used in place of the global API key. To quote the Cloudflare API docs:
> API Tokens provide a new way to authenticate with the Cloudflare API. They allow for scoped and permissioned access to resources [...]
Note that there is [currently a bug in the API when using tokens for authentication](https://community.cloudflare.com/t/restricted-api-keys/13647/109) causing 500 errors to be returned, so this should not be merged until that is fixed. I just wanted to open the PR to get any feedback in the meantime.
Resolves #890.
> cloudflare: add support for API tokens

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_linodev4.md
- providers/dns/linodev4/linodev4.go
- providers/dns/linodev4/linodev4.toml
Allow to configure the propagation timeout for Linode v4.
Fixes #960
> linodev4: propagation timeout configuration.

- docs/content/installation/_index.md
Using `github.com/go-acme/lego/cmd/lego` confuses `go get`. It fetches `github.com/go-acme/lego@v2.7.2+incompatible` (among others) and stumbles over a type error with that version.
Correcting the go get path to `github.com/go-acme/lego/v3/cmd/lego` does the right thing.
fixes #993
> docs: clarify installation-from-source instructions

- certificate/authorization.go
I use certificates that for domains that span multiple GCP accounts. In the past, I've used `lego` to request those certs. I've done this by calling lego a couple times, and expecting the first times to fail. eg:
```
DOMS=(--domains="proj1.example.com" --domains="proj2.example.com")
GCE_PROJECT=proj1 lego ${DOMS[*]} --dns="gcloud" --accept-tos run
GCE_PROJECT=proj2 lego ${DOMS[*]} --dns="gcloud" --accept-tos run
```
PR https://github.com/go-acme/lego/pull/851 breaks this behavior. With that change, when the first run of `lego` fails to complete all challenges, it deactivates _all_ of them. This makes the previous use case impossible.
This can be mitigated by changing the first `lego` run to only use `proj1.example.com`. It would succeed, and then the subsequent run would skip the …
> Don't deactivate valid authorizations

- .golangci.toml
- challenge/dns01/nameserver.go
- challenge/dns01/nameserver_test.go
Having a domain's primary nameserver is handy in some situations.
This reduces query overhead by caching not only the domain's zone,
but also the primary NS (of the same underlying SOA record).
Additional functions FindPrimaryNsByFqdn and FindPrimaryNsByFqdnCustom
can be used to access the same SOA record cache.
fixes #964
*(This is a copy of #965 because I made a mistake when creating the original PR and rebasing it recently. Github also does not allow to change the head repository/branch for existing PRs, so this one is not based off of `digineo:master`)*
> feat: expose more SOA fields found by dns01.FindZoneByFqdn

- providers/dns/httpreq/httpreq.go
Uses the `env.GetOrFile` to look for the environment variable and if it is
not found it tries to get the value from a file referred to in the
corresponding environment variable suffixed with `_FILE`.
Supports `HTTPREQ_USERNAME` and `HTTPREQ_PASSWORD`.
Closes #999
> httpreq: Allow use environment vars from a _FILE file

- e2e/challenges_test.go
- e2e/dnschallenge/dns_challenges_test.go
- providers/dns/auroradns/auroradns.go
- providers/dns/cloudflare/cloudflare.go
- providers/dns/digitalocean/digitalocean.go
- providers/dns/digitalocean/digitalocean_test.go
- providers/dns/ovh/ovh.go
Use `token` instead of `fqdn` as unique ID to find record ID for:
- Aurora DNS
- Cloudflare
- Digital Ocean
- OVH
The token allows to distinct wildcard domain (`*.example.com`) and root domain (`example.com`)
Closes #998
> fix: use token as unique ID.

- providers/dns/cloudflare/cloudflare.go
This amends #1003, where I missed the missing map initialization for Cloudflare in my review.
```console
$ export CLOUDFLARE_EMAIL=... CLOUDFLARE_API_KEY=... CLOUDFLARE_DOMAIN=...
$ go test -v github.com/go-acme/lego/v3/providers/dns/cloudflare -run TestLivePresent
=== RUN   TestLivePresent
--- FAIL: TestLivePresent (0.64s)
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
goroutine 7 [running]:
testing.tRunner.func1(0xc00010a100)
$GOROOT/src/testing/testing.go:874 +0x3a3
panic(0x78ba60, 0x8731b0)
$GOROOT/src/runtime/panic.go:679 +0x1b2
github.com/go-acme/lego/v3/providers/dns/cloudflare.(*DNSProvider).Present(0xc00000e640, 0xc00001e3f2, 0x8, 0x0, 0x0, 0x7fe85a, 0x6, 0xc000048f60, 0x47fef6)
$LEGOROOT/providers/dns/cloudflare/cloudflare.go:152 +0x3ce …
```
> cloudflare: fix panic when accessing record cache

- cmd/flags.go
- docs/content/usage/cli/_index.md
- docs/content/usage/cli/examples.md
The `--http.webroot` option does not properly explain that setting this _ONLY_ writes the token to the directory and _DOES NOT_ start a server. Also does not explain that the directory _MUST_ therefore be publicly available/hosted..
I have therefore tried to add this information to the examples documentation.. If not in a correct form please let me know how I should make it into a more intuitive/accepted description/example..
Edit: Also added a more explicit description to the CLI help output
#1011
> Update examples to explain http.webroot

- docs/content/dns/zz_gen_dnspod.md
- go.mod
- go.sum
- providers/dns/dnspod/dnspod.go
- providers/dns/dnspod/dnspod.toml
Fixes  #1031
Like https://github.com/decker502/dnspod-go doesn't really seem to be maintained, I created a fork in the "natural reserve of DNS clients in Golang": https://github.com/nrdcg/dnspod-go
I also cleaned a bit the code.
https://github.com/decker502/dnspod-go/compare/master...nrdcg:master
> Update dnspod, because of API breaking changes.

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_route53.md
- providers/dns/route53/route53.toml
- adds explicit exclusions about `_FILE` suffix
- adds a link about Setting AWS Credentials
Fixes #1033
> doc: improve Route53 documentation.

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_namecheap.md
- providers/dns/namecheap/namecheap.go
- providers/dns/namecheap/namecheap.toml
Add sandbox support through the env var `NAMECHEAP_SANDBOX` (boolean)
Uses the production API URL by default.
Fixes #1040
> namecheap: add sandbox support.

- acme/api/api.go
- challenge/resolver/solver_manager.go
- go.mod
- go.sum
- providers/dns/hostingde/client.go
The latest versions (since v3.2.0) of `cenkalti/backoff` contains a major regression.
```console
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6de565]
goroutine 7 [running]:
testing.tRunner.func1(0xc0000fc100)
/home/ldez/.gvm/gos/go1.13.6/src/testing/testing.go:874 +0x3a3
panic(0x774520, 0xaa4f40)
/home/ldez/.gvm/gos/go1.13.6/src/runtime/panic.go:679 +0x1b2
time.(*Timer).Stop(...)
/home/ldez/.gvm/gos/go1.13.6/src/time/sleep.go:74
github.com/cenkalti/backoff/v3.(*defaultTimer).Stop(0xc000232070)
/home/ldez/sources/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.2.1/timer.go:32 +0x25 …
```
> chore: update cenkalti/backoff to v4.

- providers/dns/designate/designate.go
The Designate plugin tries to clean up managed recordsets like SOA and NS.
In most Designate installations this is not allowed.
> designate: Don't clean up managed records like SOA and NS

- .golangci.toml
- providers/dns/namecheap/client.go
- providers/dns/namecheap/namecheap.go
- providers/dns/namecheap/namecheap_test.go
Namecheap allows you to add domains to their DNS service that aren't registered through them. This change allows getting certificates for those domains.
> namecheap: allow external domains

- cmd/flags.go
- cmd/lego/main.go
Similar to [`CADDYPATH` in Caddy](https://caddyserver.com/v1/docs/cli) I think that lego should have an environment variable that allows setting the default path. This feature is especially useful in containers.
> Add "LEGO_PATH" environment variable

- providers/dns/route53/route53.go
This allows custom profiles, assumed roles, etc without modifying environment variables. Also instrumentation, custom proxies, etc.
Let me know if you want any changes made to suit project style, etc. Happy to make changes as desired!
> route53: allow custom client to be provided

- providers/dns/zoneee/client.go
- providers/dns/zoneee/zoneee.go
- providers/dns/zoneee/zoneee_test.go
The zoneeee dns provider fails with any kind of subdomain, due to the API being based on the zone name rather than the subdomain. 
I put together a simple patch to fix this based on work from other providers.
> zoneee: fix subdomains.

- certcrypto/crypto.go
Tested that this works fine without a CommonName in the CSR, I was able to obtain certs from LE.
Closes #1063
> crypto: Treat CommonName as optional

- .travis.yml
- Dockerfile
- Makefile
- tmpl.Dockerfile
Allows to publish (on tags only) a multi-arch image.
I use a tool that I created to publish multi-arch image easily: https://github.com/ldez/seihon
I already added env vars to Travis CI: https://travis-ci.org/go-acme/lego/settings
Fixes #1071
https://hub.docker.com/r/goacme/lego
> feat: multi-arch Docker image.

- providers/dns/azure/azure.go
`github.com/Azure/go-autorest` expects `AZURE_CLIENT_SECRET` to be set. Otherwise, it will fall back to using metadata endpoint, which is only available from inside Azure.
This change essentially allows to set `AZURE_CLIENT_SECRET_FILE` instead of `AZURE_CLIENT_SECRET` and have client secret propagated to `autorest.Authorizer`.
> azure: pass AZURE_CLIENT_SECRET_FILE to autorest.Authorizer

- providers/dns/namedotcom/namedotcom.go
> namedotcom: get the actual registered domain so we can remove just that from the hostname to be created

- acme/api/api.go
- acme/api/internal/nonces/nonce_manager.go
- acme/api/internal/secure/jws.go
- certificate/errors.go
- challenge/http01/http_challenge_server.go
- challenge/resolver/errors.go
- challenge/resolver/prober_test.go
- challenge/tlsalpn01/tls_alpn_challenge_server.go
- cmd/accounts_storage.go
- providers/dns/pdns/client.go
- providers/http/memcached/memcached.go
- providers/http/webroot/webroot.go
Replaces arrows (`->`) to a more standard separator (`:`).
This avoid this kind of output:
```
acme: Error -\u003e 
```
Because some users think that `\u003e` is an error code.
https://community.containo.us/t/dns-01-challenge-with-ovh-not-working-acme-error-cleaning-up-ovh-unknown-record-id-acme-error-u003e/5030
> Use colon instead a arrow in error messages

- go.mod
- go.sum
The [v0.0.2](https://github.com/cpu/goacmedns/releases/tag/v0.0.2) release improves compatibility with account information generated with other tools (`pyacmedns`), or using a raw `acmedns` API response.
> acmedns: Update cpu/goacmedns v0.0.1 -> v0.0.2

- acme/api/internal/sender/useragent.go
- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_cloudns.md
- providers/dns/cloudns/cloudns.go
- providers/dns/cloudns/cloudns.toml
- providers/dns/cloudns/cloudns_test.go
- providers/dns/cloudns/internal/client.go
- providers/dns/cloudns/internal/client_test.go
Added new environment variable CLOUDNS_SUB_AUTH_ID to support cloudns provider as a subuser (https://www.cloudns.net/wiki/article/114/)
This adopts the acme client implementation (https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_cloudns.sh).
> Provider ClouDNS: Add subuser support

- providers/dns/ns1/ns1.go
I was using the ns1 DNS provider and saw the following weird message when it was trying to create a new record: 
```
Create a new record for [zone: mydomain.st, fqdn: _acme-challenge.mydomain.st., domain: %!s(MISSING)]
```
I had initially thought I had done something wrong programmatically on my end, but I think it's only an issue with regards to what we print to STDOUT.
> ns1: fix missing domain in log 

- go.mod
- go.sum
Hi everyone,
First, thanks for your excellent work!
This PR updates the **alibaba-cloud-sdk-go** dependency version to `v1.61.112`. Before this version, the Alibaba SDK mutates the global config of [json-iterator/go](https://github.com/json-iterator/go), which can cause unwanted side effects with other libraries using it (that was my case).
https://github.com/aliyun/alibaba-cloud-sdk-go/issues/412
> alicloud: update sdk dependency version to v1.61.112

- go.mod
- providers/dns/azure/azure.go
Azure provide a way to associate an identity to an instance via [user-managed-identity]( https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).
This PR allows lego to use that identity by updating the azure api to get its credential.
This should be retro-compatible to the previous way to get credentials.
> azure: Allow for the use of MSI

- providers/dns/godaddy/client.go
- providers/dns/godaddy/godaddy.go
```console
$ ./lego -m email@example.com --dns godaddy -d *.example.org -d example.org -s https://acme-staging-v02.api.letsencrypt.org/directory run
2020/04/17 13:11:31 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2020/04/17 13:11:40 [INFO] acme: Registering account for email@example.com
!!!! HEADS UP !!!!
Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/ldez/sources/go/src/github.com/go-acme/lego/.lego/accounts".
You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.2020/04/17 13:11:41 [INFO] [*.example.org, …
```
> godaddy: allow parallel solve.

- providers/dns/exoscale/exoscale.go
The second argument of `GetOrDefaultSecond` should be of type `time.Duration`.
When passing in a straight `int`, the argument will be interpreted as nanoseconds. This causes all HTTP requests to time out.
> Fix exoscale HTTP timeout

- providers/dns/mythicbeasts/client.go
Mythic Beasts just released their v2 api officially, so this updates
the API endpoint to use it.
This should fix #1129 and thus make it sane to do a release with this provider in.
> mythicbeasts: Update API base URL for released v2 API

- providers/dns/autodns/client.go
> autodns: removes TXT records during CleanUp.

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_dnsimple.md
- go.mod
- go.sum
- providers/dns/dnsimple/dnsimple.go
- providers/dns/dnsimple/dnsimple.toml
This PR upgrades the DNSimple client powering the DNSimple provider to the latest version.
There has been a number of changes compared to v0.30.0 that is currently in use, including some fixes that could have prevented the client to miss the proper TXT record to cleanup.
I also took the time to expand the docs with some CLI examples.
> Upgrade DNSimple client to 0.60.0

- registration/registar.go
- registration/registar_test.go
We use [pebble:latest](https://github.com/letsencrypt/pebble) as a way to integration-test our own LetsEncrypt certificate fetcher. 
One notable issue I found was that the `Registrar.ResolveAccountByKey` method errors out when we try to resolve an existing account with the following error: 
```
unable to resolve account by key: acme: error: 400 :: POST :: https://127.0.0.1:14000/my-account/1 :: urn:ietf:params:acme:e
rror:malformed :: Use POST-as-GET to retrieve account data instead of doing an empty update
```
Based on the pebble source [here](https://github.com/letsencrypt/pebble/blob/35691f87bc2df5a34577c4617975e269eec86f87/wfe/wfe.go#L987), our `POST-as-GET` gets interpreted as an update call and is failed as a malformed request. 
It seems like we used to be able to get account …
> Registrar.ResolveAccountByKey: Fix issues found testing with Pebble

- providers/dns/hetzner/hetzner.go
Hi folks,
Hope you're doing well.
I've made a PR to fix an issue that I'm having with the Hetzner DNS provider. From what I understand in the current situation when you try to request a certificate for let's say ``test.frikandel.nl`` the following will happen:
- It will recurse DNS to find SOA of ``test.frikandel.nl`` and then try to fetch this zone via Hetzner API, in this case SOA is ``frikandel.nl``
- When it succesfully finds SOA it will query the Hetzner Zone ID from Hetzner API for further requests
- From FQDN, in this case ``_acme-challenge.test.frikandel.nl.``, it will strip the domain provided by user, in this case ``test.frikandel.nl`` resulting in ``_acme-challenge``
- It will create ``_acme-challenge`` in DNS via Hetzner API which will result in …
> hetzner: fix record name.

- challenge/dns01/dns_challenge.go
Related to:
- https://community.letsencrypt.org/t/during-secondary-validation-incorrect-txt-record/113643
- https://community.letsencrypt.org/t/acme-v1-v2-validating-challenges-from-multiple-network-vantage-points/112253
- https://community.letsencrypt.org/t/during-secondary-validation-incorrect-txt-record/113643
> fix: multi-va.

- README.md
- providers/dns/oraclecloud/oraclecloud.go
- use https://pkg.go.dev instead of https://godoc.org
- add godoc on oracle package.
> doc: improvements.

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_desec.md
- providers/dns/desec/desec.toml
The deSEC.io DNS provider was added in verision 3.7.0. The docs incorrectly state it was added 0.3.7. This PR cleans that up.
> desec: Fix version in docs

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_azure.md
- providers/dns/azure/azure.go
- providers/dns/azure/azure.toml
- providers/dns/azure/azure_test.go
Current environments recognized are public, usgovernment, german, and
china. Not specifying any environment is the same as specifying public.
> azure: allow selecting environments

- .golangci.toml
- certificate/authorization.go
- challenge/challenges.go
- challenge/dns01/dns_challenge.go
- lego/client_config.go
- providers/dns/conoha/internal/client_test.go
- providers/dns/gandi/gandi.go
- providers/dns/netcup/internal/client_test.go
- providers/dns/netcup/netcup.go
- providers/dns/nifcloud/internal/client.go
- providers/dns/nifcloud/nifcloud.go
Update golangci-lint to v1.30.0.
The version is defined in the Travis settings.
> chore: update linter.

- docs/content/dns/zz_gen_edgedns.md
- docs/content/dns/zz_gen_namecheap.md
- providers/dns/edgedns/edgedns.toml
- providers/dns/namecheap/namecheap.toml
Currently, only after trying to enable API access, you get to see the following requirements:
"Account balance of $50+, 20+ domains in your account, or purchases totaling $50+ within the last 2 years."
Closes #1229
> Add additional namecheap-specific infos

- providers/dns/namesilo/namesilo.go
The namesilo api seems not "symmetric": the data required for storage may be different from the data that will be read.
Fixes #1238
> namesilo: fix cleanup.

- go.mod
- go.sum
The versions higher than v0.23.0 use a weird dependency do github.com/golangci/lint-1
https://github.com/exoscale/egoscale/blob/0590bfb2400cfce7358202c5f6337fa02198b1e0/go.mod#L4
https://github.com/deepmap/oapi-codegen/blob/fae4b9e07979f25a896eaa21816a7a00bb9a472d/go.mod#L8
---
the v1.19.0 seems to be an error: https://pkg.go.dev/github.com/exoscale/egoscale?tab=versions
https://github.com/go-acme/lego/commit/50a87b031e7c01fa75b20286a35082c3c7e931e7#r41994779
> exoscale: change dependency version.

- providers/dns/rfc2136/rfc2136.go
Issue #1256 has revealed an issue with the way we read the TSIG algorithm from the environment.
The RFC specifies the algorithm to be fully-qualified, but the CLI docs don't communicate this clearly to the end user.
This PR just wraps the algorithm in a `dns.Fqdn()` call, ensuring a trailing dot.
> rfc2136: ensure TSIG algorithm is fully qualified

- certificate/certificates.go
`ge` either should have been `get` or `be`. Changed to `be` here.
> Fix minor typo in docs

- acme/api/internal/nonces/nonce_manager_test.go
- acme/api/internal/secure/jws_test.go
- challenge/dns01/nameserver.go
- challenge/http01/http_challenge_server.go
- platform/tester/api.go
- providers/dns/azure/azure.go
- providers/dns/constellix/internal/auth.go
- providers/dns/dynu/internal/auth.go
- providers/dns/dynu/internal/client.go
- providers/dns/internal/selectel/client.go
- providers/dns/mythicbeasts/client.go
- providers/dns/scaleway/internal/client.go
Use `http.Header.Set` method instead of `Add` to overwrite all existing header values when it's useful.
> fix: use http.Header.Set method instead of Add.

- acme/api/account.go
- e2e/challenges_test.go
Similar to #1142, Registrar.QueryRegistration is affected by pebble's enforcement of Post-as-GET for account retrieval.
This updates AccountService.Get to use postAsGet instead of the full post to facilitate this.
-----
I was a little hesitant to add this so far down the call stack, but it looks like `Registrar.QueryRegistration` is the only consumer of this call at this point in time (checked using references and call hierarchy in VSCode). As such I think this is safe, but we could duplicate the logic if need be.
No tests as it seems like a challenge to test this non-trivially at this point in time. Post-as-GET still sends some degree of body as a JWS payload (see [`signedPost()`](https://github.com/go-acme/lego/blob/6860f823daa4bbdff2792d836d0499d148f39f17/acme/api/api.go#L118-L135)) so …
> acme/api: use postAsGet instead of post for AccountService.Get

- providers/dns/otc/client.go
- providers/dns/otc/mock_test.go
If the OTC API returns multiple dns zones, select the appropriate one by comparing the zone name instead of returning an error.
> otc: select correct zone if multiple returned

- acme/api/certificate.go
- acme/api/order.go
- acme/api/order_test.go
- acme/commons.go
- certificate/certificates.go
- certificate/certificates_test.go
Fixes #1294
By following the RFC:
>    The server MAY provide one or more link relation header fields
>    [RFC8288] with relation "alternate".  Each such field SHOULD express
>    an alternative certificate chain starting with the same end-entity
>    certificate.
https://tools.ietf.org/html/rfc8555#section-7.4.2
The "alternate" links are NOT provided by the order call but by the certificate call.
I don't understand why I didn't see the problem during the PR review introducing this.
I made a mistake and I want to apologize for it.
```
go run ./cmd/lego/ -m xxx@example.com -d example.com --dns xxx -s https://acme-staging-v02.api.letsencrypt.org/directory run --preferred-chain="Fake LE Root X2"
2020/11/21 01:22:01 [INFO] [example.com] acme: Obtaining bundled SAN certificate
2020/11/21 …
```
> fix: preferred chain support.

- docs/config.toml
Because of the update of the theme, a button "Home" appeared but the URL (related to this button) doesn't fit our doc system.
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
> doc: remove landing page button.

- docs/content/dns/zz_gen_hyperone.md
- providers/dns/hyperone/hyperone.toml
I am responsible at HyperOne for maintaining Lego integration.
`HYPERONE_ZONE_URI` env is not implemented.
> hyperone: Minor tweaks of documentation

- providers/dns/pdns/client.go
Hello,
When trying obtain a certificate, I got an error message
```
acme: error presenting token: pdns: error talking to PDNS API: Get "http://pdns-server:8081/api/v1/servers/localhost/zones": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
My PDNS server has > 5k zones, to get all zones it takes >30s. I can increase timeout by using `PDNS_HTTP_TIMEOUT` but I think we can get exact zone instead of all zones ( for single zone, it takes only ~50ms )
Fixes #817
> pdns: get exact zone instead of all zones

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_inwx.md
- providers/dns/inwx/inwx.go
- providers/dns/inwx/inwx.toml
INWX has rather unstable propagation delays. Users reported that the
robustness of the DNS challenge improves with a longer timeout, thus instead
of using the default, hardcode a larger default. Six minutes seems to work
fine so far.
Fixes #1297
> Increase INWX propagation timeout to 360s to improve robustness

- go.mod
- go.sum
- providers/dns/acmedns/acmedns_test.go
This commit updates the `github.com/cpu/goacmedns` dependency to the latest tagged release at the time of writing, [v0.1.1](https://github.com/cpu/goacmedns/releases/tag/v0.1.1).
Since v0.0.3 there have been [two](https://github.com/cpu/goacmedns/commit/41bdb34639cc9ccf8f39fafde9a802731eeab86e) [small](https://github.com/cpu/goacmedns/commit/745426768bae5f19dd10e50fa340bba52e2da6ae) changes to the storage interface. Both are backwards compatible.
> deps: update cpu/goacmedns to v0.1.1.

- acme/errors.go
The condition so far printed it only when it was known to be empty.
Found in https://github.com/NixOS/nixpkgs/issues/101445#issuecomment-757352452
> errors: Fix instance not being printed

- providers/dns/infomaniak/internal/client.go
- providers/dns/infomaniak/internal/models.go
The error message on infomaniak server error is not very verbose and well formated, 
For now,the error code is : 
```
infomaniak: error when calling api to create DNS record: unexpected API result (error): &{unexpected_error An unexpected error occurred map[] []}
```
My proposal gives
```
infomaniak: error when calling api to create DNS record: unexpected API result (error): An unexpected error occurred (HTTPStatus: 500 Internal Server Error)
(give the error description + http status)
```
I'm unsure if the description field is always filled, so we may prefer this : (give the raw body + https status)
```go
return nil, fmt.Errorf("unexpected API result (%s): %s (HTTPStatus: %s)", resp.Result, string(content), rawResp.Status)
```
```
infomaniak: error when calling api to create DNS record: …
```
> infomaniak: Make error message more meaningful

- .github/workflows/go-cross.yml
- .github/workflows/main.yml
- CONTRIBUTING.md
- docs/content/installation/_index.md
- go.mod
- update go version in the CI
- update documentation
I didn't replace `ioutil` to keep the compatibility with go1.15
> Update for go1.16

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_edgedns.md
- providers/dns/edgedns/edgedns.go
- providers/dns/edgedns/edgedns.toml
- providers/dns/edgedns/edgedns_integration_test.go
- providers/dns/edgedns/edgedns_test.go
Use `edgegrid.Init()` function to populate the EdgeGrid configuration from the environment variables or from a `.edgerc` file.
Akamai credentials are automatically detected in the following locations and prioritized in the following order:
1. Section-specific environment variables `AKAMAI_{SECTION}_HOST`, `AKAMAI_{SECTION}_ACCESS_TOKEN`, `AKAMAI_{SECTION}_CLIENT_TOKEN`, `AKAMAI_{SECTION}_CLIENT_SECRET` where `{SECTION}` is specified using `AKAMAI_EDGERC_SECTION`
2. If `AKAMAI_EDGERC_SECTION` is not defined or is set to `default`: Environment variables `AKAMAI_HOST`, `AKAMAI_ACCESS_TOKEN`, `AKAMAI_CLIENT_TOKEN`, `AKAMAI_CLIENT_SECRET`
3. .edgerc file located at `AKAMAI_EDGERC` (defaults to `~/.edgerc`, sections can be specified using `AKAMAI_EDGERC_SECTION`)
4. Default environment …
> edgedns: add support for .edgerc file

- docs/content/dns/zz_gen_mythicbeasts.md
- providers/dns/mythicbeasts/mythicbeasts.toml
> doc: Fix typo in env var name in Mythic Beasts usage example

- providers/dns/dnspod/dnspod.go
When there are more than 100 records in the domain, Records.List function without providing record name, may fail to receive  the records of the _acme_challenge TXT record. Because dnspod records list api return maximum 100 records one time.  So CleanUp will not delete the TXT records.
We can provide record name into Records.List function. This will search _acme_challenge TXT record more accurately, and with less return records, less than 100.
> dnspod: improve search accuracy when a domain have more than 100 records

- providers/dns/desec/desec.go
When I do not specify "DESEC_TTL=3600" the default behavior is this error. 
```
acme: error presenting token: desec: failed to create records: domainName=, recordName=_acme-challenge: 400: body: {"ttl":["Ensure this value is greater than or equal to 3600."]}
```
desec.io only allows TTL below 3600 if you contact there support and they approve this on your account. So the default behavior is always resulting in an error unless you contact support. 
See: 
https://desec.readthedocs.io/_/downloads/en/latest/pdf/
https://github.com/desec-io/desec-stack/issues/216
This PR set's the TTL to 3600 so there are no longer any errors.
> desec: fix error with default TTL

- lego/client_config.go
Let's Encrypt's API is sometimes slow:
~~~
2021/01/28 09:48:33 Could not obtain certificates:
error: one or more domains had a problem:
[*.mydomain.dev] Post "https://acme-v02.api.letsencrypt.org/acme/finalize/105472891/7570478847": net/http: timeout awaiting response headers
[mydomain.dev] Post "https://acme-v02.api.letsencrypt.org/acme/finalize/105472891/7570478847": net/http: timeout awaiting response headers
Certificate generation failed.
~~~
This prevents problems by waiting a little longer for a response.
> Increase HTTP client timeouts

- docs/content/dns/zz_gen_arvancloud.md
- providers/dns/arvancloud/arvancloud.toml
It has to be also changed in below page:
https://go-acme.github.io/lego/dns/arvancloud/#additional-configuration
> Typo issue in ArvanCloud configuration sample

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/new_dns_provider.md
Add issue templates to improve triage and issue quality.
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
> Add issue templates.

- Makefile
In #1374 the PDNS documentation was amended, but the author forgot to re-generate the docs.
We do have a validation check in the main workflow, but it didn't catch the change because the underlying Makefile target was broken.
This commit replaces the Makefile conditional with an equivalent shell conditional.
<details><summary>Explanation</summary>
The conditional checking for a dirty working directory ran before generating the documentation. In effect, `make validate-doc` only
did the right thing on the second invokation.
Consider this simplified Makefile example:
```make
generate:
aaaa
validate: generate
ifneq ($(shell bbbb),)
cccc
else
dddd
endif
```
The order of evaluation for `make validate` is:
1. detect `generate` target, no dependencies,
2. set body for `generate` target to `aaaa`, …
> make: fix validate-docs

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_pdns.md
- providers/dns/pdns/client.go
- providers/dns/pdns/pdns.go
- providers/dns/pdns/pdns.toml
Hi folks,
This PR has several improvements to the PowerDNS DNS Provider.
The PowerDNS API allows for a `server_name` other than 'localhost'. The auth server itself does not use it, but proxies that have multiple backends can. We are running such a proxy. The first commit in this series adds the `PDNS_SERVER_NAME` option to set this. The default remains the same.
Some proxies require the Content-Type header to be set. The second commit sets this header to 'application/json' when the method is not DELETE or GET.
The API allows the 'records' field to be omitted in the request when the `changetype` is 'DELETE'. The third commit implements this omission.
I was confused by an error report that had the word 'fetch' hardcoded. The last commit changes this to the HTTP Method used.
If there is …
> powerdns: several improvements

- .github/workflows/main.yml
- .golangci.toml
- providers/dns/constellix/internal/model.go
- providers/dns/constellix/internal/txtrecords_test.go
- providers/dns/otc/mock_test.go
Update golangci-lint to v1.39.0.
> chore: update linter

- providers/dns/nifcloud/nifcloud.go
I updated dns nifcloud provider. There was an error in the method of specifying the Zone, so I fixed it.
Fixes #1382
> nifcloud: Get zone info from dns01.FindZoneByFqdn

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_domeneshop.md
- providers/dns/domeneshop/domeneshop.toml
> domeneshop: fix documentation

- docs/content/dns/zz_gen_hurricane.md
- providers/dns/hurricane/hurricane.toml
Hurricane Electric's domain is `he.net`, not `he.org`.
Sorry for being pedantic :-)
> hurricane: documentation typo in domain name

- platform/wait/wait.go
- platform/wait/wait_test.go
> lib: improve wait.For returns.

- log/logger.go
> log: Use stderr instead of stdout.

- providers/dns/hurricane/internal/client.go
- providers/dns/hurricane/internal/client_test.go
In the hurricane DNS provider, consider only the first word in the response body to be the response code when checking whether the request succeeded; specifically, do not necessarily consider multi-word responses to be indicative of server errors. This corrects the handling of `nochg` responses from he.net's Dynamic DNS service, in which the response code is followed by the unchanged value of the TXT record.
Fixes #1408
----
I've confirmed that this fixes the issue raised in #1408 (domain name redacted):
```
2021/05/23 21:02:01 [INFO] [...] acme: use dns-01 solver
2021/05/23 21:02:01 [INFO] [...] acme: Preparing to solve DNS-01
2021/05/23 21:02:01 nochg "PeBwwj6VsqoP4Y_eUJrSGWi0yNN614vYteNLBTpWfXk": unchanged content written to TXT record _acme-challenge.[...]
2021/05/23 21:02:01 [INFO] …
```
> hurricane: only treat first word of response body as response code

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_mythicbeasts.md
- providers/dns/mythicbeasts/mythicbeasts.toml
MYTHICBEASYS_AUTH_API_ENDPOINT changed to MYTHICBEASTS_AUTH_API_ENDPOINT
> mythicbeasts: typo in documentation

- providers/dns/mythicbeasts/mythicbeasts.toml
I have had a support ticket open with Mythic Beasts, as TLD cert requests were failing.
I have been advised that https://www.mythic-beasts.com/support/api/auth should change to https://auth.mythic-beasts.com/login
I have made that change and my requests now work, so am updating this page for others :)
> mythicbeasts: update API Auth endpoint in documentation

- challenge/resolver/solver_manager.go
well, fix this strange bug, described at #1427 `¯\_(ツ)_/¯`
idk what to say else... hooray, opensource! 🎉🥳
Fixes #1427
> lib: fix backoff in SolverManager

- providers/dns/lightsail/lightsail.go
"LIGHTSAIL_" was mentioned two times in the key for lightsail provider
> lightsail: wrong Region env var name

- .github/workflows/go-cross.yml
- .github/workflows/main.yml
The comments inside the `path` section are misinterpreted then the cache is just empty.
> chore: fix github action cache.

- certificate/authorization.go
- certificate/certificates.go
- cmd/cmd_renew.go
- cmd/cmd_run.go
After a successful certificate request, the authorizations may be cached by the ACME provider for some time.
For example [Let's encrypt caches them for 30 days](https://letsencrypt.org/docs/faq/#i-successfully-renewed-a-certificate-but-validation-didn-t-happen-this-time-how-is-that-possible)
If the registration account is shared between multiple clients, a client can request a new certificate for domains already requested by the original client without new validation.
To avoid this behaviour, the authorizations must be deactivated explicitly, see [RFC 8555, Deactivating an Authorization](https://datatracker.ietf.org/doc/html/rfc8555#section-7.5.2)
With this PR, a flag `AlwaysDeactivateAuthorizations` is introduced to the `ObtainRequest` and `ObtainForCSRRequest` to enable this …
> Add AlwaysDeactivateAuthorizations flag to ObtainRequest

- providers/dns/edgedns/edgedns.go
The current Present logic of the EdgeDNS provider tries to create the TXT record even if it has just updated the existing TXT record.
The current CleanUp logic of the EdgeDNS provider deletes the TXT record even if it found that there are still challenges in the TXT record that should remain there.
This commit is to fix these issues.
> edgedns: fix Present and CleanUp logic

- docs/content/dns/zz_gen_infomaniak.md
- providers/dns/infomaniak/infomaniak.go
- providers/dns/infomaniak/infomaniak.toml
> infomaniak: fix subzone support

- certcrypto/crypto.go
I am using lego to implement the TLS-ALPN-01 challenge using Amazon Certificate Manager (ACM). Currently, the certificates generated by certcrypto.GeneratePemCert only last for 365 nanoseconds which is not long enough for me to upload the cert to ACM. This PR extends the validity period to 365 days since that seems like it may have been the original intent.
Fixes #1533
> Extend validity of TLS-ALPN-01 certificates to 365 days

- cmd/certs_storage.go
- cmd/flags.go
- docs/content/usage/cli/_index.md
- go.mod
- go.sum
With this option a PCKS#12 file is optionally generated with the private key.
The file has the certificate, the issuer certificate and private key.
The file is generated with a password by limitation of the PKCS#12 library, the default password is `changeit`, and it can be specified by the --pfx.pass option.
Fixes #1388.
> Added a --pfx, and --pfx.pass option to generate a PKCS#12 (.pfx) file.

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_azure.md
- providers/dns/azure/azure.go
- providers/dns/azure/azure.toml
- providers/dns/azure/azure_test.go
- providers/dns/azure/private.go
- providers/dns/azure/public.go
I've added support for Azure Private Zone DNS to be able to utilize private zones when running a private ACME server inside Azure
> azure: add support for Azure Private Zone DNS

- lego/client_config.go
- `LEGO_CA_CERTIFICATES` now accepts multiple file paths to be added by using `os.PathListSeparator` (`:` on POSIX, `;` on Windows) as a separator.
- `LEGO_CA_SYSTEM_CERT_POOL` initiates the cert pool with a copy of the system cert pool.
Fixes #1490
> feat: extended support of cert pool

- certcrypto/crypto.go
- certcrypto/crypto_test.go
If ParsePEMPrivateKey is called with input that is not actually
a valid PEM block (e.g. because a file got corrupted), pem.Decode
will return a nil block which is immediately dereferenced causing
a panic.
Guard against this case returning an error, and add some tests
to validate.
> Fix panic in certcrypto.ParsePEMPrivateKey

- providers/dns/tencentcloud/client.go
In #1527, there is [a comment](https://github.com/go-acme/lego/pull/1527#issuecomment-1035876292) saying he encountered InvalidParameter.DomainInvalid when using DNS challenges with Tencent Cloud DNS.
This PR fixes that.
Using FQDN as `request.Domain` will cause problems with Tencent SDK and `InvalidParameter.DomainInvalid` will be returned.
UnFQDN the domain name will solve it.
Formatting, linters, tests, and compiling have all passed.
> tencentcloud: fix InvalidParameter.DomainInvalid error when using DNS challenges

- providers/dns/dnsimple/dnsimple.go
Allow for passing DNSIMPLE_DEBUG to the environment; based on other providers I found
similar: https://github.com/go-acme/lego/blob/83c626d9a1889fa499bc9c97bc2fdea965307002/providers/dns/joker/joker.go
reference file: https://github.com/dnsimple/dnsimple-go/blob/af9daf7e8d193d83b06b323f792d8afe66ddae83/dnsimple/dnsimple.go#L69
> dnsimple: add debug option

- providers/dns/gcore/internal/client.go
Hi, this PR for https://gcorelabs.com/dns/
We moved our DNS API to new URL
> gcore: change dns api url

- go.mod
- go.sum
I noticed that GoVultr hasn't been updated in a while so I went ahead and bumped to the latest version 2.16.0. No major changes have been made to DNS so behavior has stayed the same.
Some test output
```console
$  lego [vultr-updates] make build
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: a77d023488dac3abc6bc9cbdf5850d51d88e2f55
go build -trimpath -ldflags '-X "main.version=a77d023488dac3abc6bc9cbdf5850d51d88e2f55"' -o  dist/lego ./cmd/lego/
$  dist [vultr-updates] ./lego -m your@email.com --dns vultr -d '*.dymko.dev' -d 'dymko.dev' --dns-timeout 100 -s https://acme-staging-v02.api.letsencrypt.org/directory  run
2022/05/07 12:07:02 [INFO] [*.dymko.dev, dymko.dev] acme: Obtaining bundled SAN certificate
2022/05/07 12:07:03 [INFO] [*.dymko.dev] AuthURL: …
```
> vultr: bump client from 2.7.1 to 2.16.0

- .golangci.toml
- cmd/cmd_renew.go
Add a sleep between 0 to 8 minutes during the call of the `renew` command like [certbot](https://github.com/certbot/certbot/blob/284023a1b7672be2bd4018dd7623b3b92197d4b0/certbot/certbot/_internal/renewal.py#L472).
Fixes #1656
> feat: sleep at renewal

- docs/content/dns/zz_gen_liquidweb.md
- providers/dns/liquidweb/liquidweb.toml
Fixed little typo in liquidweb example
> docs: fixed invalid environment parameter name in example

- cmd/accounts_storage.go
- cmd/flags.go
- cmd/setup.go
This allows applications which embed lego-cli to identify themselves,
which will assist the CA in operations and identifying issues.
Fixes #1663
> Add a --user-agent flag to lego-cli

- providers/dns/hetzner/hetzner.go
- providers/dns/hetzner/hetzner_test.go
Hetzner (now) allows a min TTL of 60.
> hetzner: set min TTL to 60s

- e2e/challenges_test.go
```
2022/08/22 15:12:00 [INFO] acme: Querying account for https://localhost:14000/my-account/b846792c3124aa5
challenges_test.go:266:
Error Trace:	/home/runner/work/lego/lego/e2e/challenges_test.go:266
Error:      	Expect "https://localhost:14000/list-orderz/b846792c3124aa5" to match "https://localhost:14000/list-orderz/\d+"
Test:       	TestChallengeHTTP_Client_Registration_QueryRegistration
challenges_test.go:267:
Error Trace:	/home/runner/work/lego/lego/e2e/challenges_test.go:267
Error:      	Expect "https://localhost:14000/my-account/b846792c3124aa5" to match "https://localhost:14000/my-account/\d+"
Test:       	TestChallengeHTTP_Client_Registration_QueryRegistration
```
https://github.com/go-acme/lego/runs/7954912813?check_suite_focus=true
> fix: flaky tests

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_loopia.md
- providers/dns/loopia/loopia.go
- providers/dns/loopia/loopia.toml
> loopia: add configuratble API endpoint

- challenge/dns01/dns_challenge.go
Right now the `LEGO_EXPERIMENTAL_CNAME_SUPPORT` only follows one CNAME record. If this CNAME record points to another, then the chain breaks and the DNS record created is incorrect.
This change allows it to keep following CNAME records as long as it continues to find one up to a limit so that CNAME loops don't hang the service.
And thanks for the awesome work on this repo!!
> add recursive CNAME lookup support

- providers/dns/pdns/client.go
- providers/dns/pdns/pdns.go
This change addresses the PowerDNS DNS provider.
When using the API with a setup where there is not only the primary but also some secondary servers, the secondary servers were not sent a `NOTIFY` and would not initiate an AXFR transfer.
Thus, the challenge would not propagate to all DNS servers which would in return cause failed verifications.
This change uses the [`/notify`](https://doc.powerdns.com/authoritative/http-api/zone.html#put--servers-server_id-zones-zone_id-notify) endpoint of the PowerDNS API to notify the secondaries.
> pdns: notify secondary servers after updates

- go.mod
- go.sum
This updates x/oauth2/google. The new version supports
"external_account" JSON key files, which are needed when using workload
identity federation on GCP.
> gcloud: update golang.org/x/oauth2

- acme/api/certificate.go
- certificate/certificates_test.go
This fixes #963
This fix removes the embedded issuer certificate(s) from the issued certificate if bundle is false
I've changed the tests so that they pass, but let me know if it should be done differently
> Remove embedded issuer certificates from issued certificate if bundle is false

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_digitalocean.md
- docs/content/dns/zz_gen_yandex.md
- providers/dns/digitalocean/digitalocean.go
- providers/dns/digitalocean/digitalocean.toml
I wanted to proxy the calls to DigitalOcean API made for dns ACME challenge, and the go-acme/lego `digitalocean` provider has hardcoded https://api.digitalocean.com, this PR should handle that hopefully.
> digitalocean: configurable base URL

- docs/content/dns/zz_gen_route53.md
- providers/dns/route53/route53.toml
[AWS recently released new IAM permission conditions](https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-route-53-support-dns-resource-record-set-permissions/) to restrict access to Route 53 beyond the scope of a hosted zone down to individual records. This makes it possible to finally create least privilege IAM policies for restricting access to only the [specific DNS TXT record](https://letsencrypt.org/docs/challenge-types/#dns-01-challenge) required. I have [written a blog post](https://paulgalow.com/aws-route-53-iam-policy-letsencrypt-dns) with more context and examples.
I'd like to propose an updated IAM policy which takes into account the new capabilities to lock down access as much as possible. I have successfully tested this policy with Traefik.
One downside I see with the …
> Route 53: Update IAM policy example to grant least privilege access

- .github/workflows/go-cross.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: update actions/cache to v3

- challenge/dns01/nameserver_test.go
- providers/dns/regru/internal/client.go
- providers/dns/regru/internal/client_test.go
Currently, reg.ru seems to have an API problem, I detected that because the tests are falling on master.
> "API error: INTERNAL_API_ERROR: Внутренняя ошибка, status code: 503"
This PR doesn't fix the API problem but improves the error messages and skips the tests.
The tests must be restored in the future.
> regru: improve error handling

- providers/dns/ibmcloud/internal/wrapper.go
I noticed that requesting wildcard certificates for subdomains does not work for the ibmcloud (softlayer) dns solver.
The problem is that the softlayer API getDomainID is used and the domain name is passed as an argument.
For wildcard certificates for subdomains this argument will be the subdomain. The subdomain is not a separate entity in softlayer DNS so no record and thus no domain ID is found.
This change will try to find the "parent" of the subdomain in case the domain that was used to find the domain ID has more than two parts.
When the parent can be found the correct acme challenge entries will be made and a wildcard certificate for a subdomain will be created successfully.
I did live tests with one of my domains in softlayer and with the change I am able to retrieve the wildcard …
> ibmcloud: add support for subdomains

- providers/dns/tencentcloud/client.go
Fixes https://github.com/go-acme/lego/discussions/1787
https://github.com/go-acme/lego/blob/6695fcc87344a920efcf0a504f299913a7869b54/providers/dns/tencentcloud/client.go#L20-L23
https://github.com/go-acme/lego/blob/6695fcc87344a920efcf0a504f299913a7869b54/providers/dns/tencentcloud/client.go#L39-L44
The tencent cloud sdk `DescribeDomainList` api.
The `Name` fields returned by `DescribeDomainList` api will not be converted into punycode format, can use `Punycode` field.
> tencentcloud: support punycode domain

- providers/dns/luadns/luadns.go
Fixes #1795 
The comparison in findZone does not work because authZone has a dot at the end and the entries in zones do not contain a dot.
If the dot is removed with UnFqdn it works for me.
> luadns: removed dot suffix from authzone while searching for zone

- docs/content/usage/cli/Renew-a-Certificate.md
Hello, I found a small mistake in the documentation. 
Its not valid cron schedule. This PR fix it.
> doc: fix cron schedule in example

- cmd/flags.go
- docs/content/usage/cli/Options.md
- docs/data/zz_cli_help.toml
This extends the documentation for the `--dns.resolvers` flag as suggested in #1777.
The commits are currently based off of PR #1785, so depending on whether that gets merged, I'll rebase this PR accordingly.
@oseiberts11: Would you like to proof-read the new section? You can find a preview here: https://mm.dmke.org/lego-b649657b/usage/cli/options/#dns-resolvers-and-challenge-verification
> docs: expand description for --dns.resolvers

- providers/dns/route53/route53.go
- providers/dns/route53/route53_test.go
This is incremental progress to implementing #1736, the first part being porting over certain providers (specifically route53 and lightsail) to use static credentials not derived from the environment.
This specifically adds support for the static chain where an access key ID, secret access key, and (optionally) a session token can be supplied manually.
> route53: Allow static credentials to be supplied

- docs/content/dns/zz_gen_gcloud.md
- providers/dns/gcloud/gcloud.toml
[Document](https://go-acme.github.io/lego/dns/gcloud/) has note to add CLI example for provider: `glcoud` 
Adding example with this PR.
> gcloud: add CLI example

- providers/dns/dynu/dynu.go
Hi,
Fixes https://github.com/go-acme/lego/issues/1672
It should fix the subdomain issue.
Hope it helps.
> dynu: fix subdomain support

- .github/workflows/pr.yml
- e2e/readme.md
- use `go install` instead of `go get`
- use main branch of pebble
> chore: update Pebble

- providers/dns/dnshomede/internal/readme.md
Updated your observation from our API.
> docs: update dnshomede API documentation

- docs/content/installation/_index.md
- lego is available in the ArchLinux Community repository
- Updated outdated link to AUR package
> docs: Add ArchLinux package, fix AUR link

- providers/dns/internal/rimuhosting/client.go
The base URL seems to have changed or the URL was wrong since the creation of the provider.
https://rimuhosting.com/dns/dyndns.jsp
fixes #1880
> rimuhosting: fix API base URL

- docs/content/usage/cli/Obtain-a-Certificate.md
I noticed that this env var doesn't exist anymore, as it was presumably renamed to `LEGO_CERT_KEY_PATH` as listed above.
> doc: fix wrong env var name

- cmd/cmd_run.go
Currently only the renew hook gets these variables set, this makes the behavior consistant for run hooks as well.
Fixes #1906
> feat: add LEGO_CERT_PEM_PATH and LEGO_CERT_PFX_PATH to run hook

- docs/content/dns/zz_gen_googledomains.md
- providers/dns/googledomains/googledomains.toml
The example for the Google Domains provider refers to a `gdomains` code, but it should be `googledomains`.
> docs: fix `gdomains`→`googledomains`

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_route53.md
- providers/dns/route53/route53.toml
Looks like the section that details the use of `AWS_ASSUME_ROLE_ARN` mentions that it can't be used in the configuration file, but it incorrectly repeats `AWS_ASSUME_ROLE_ARN` instead of mentioning `AWS_ASSUME_ROLE_ARN_FILE`.
> route53: minor correction to documentation

- providers/dns/autodns/autodns.go
This fixes the problem that lego doesn't use the resolved FQDN from the CNAME in the API calls to AutoDNS.
Tested with CNAME, without CNAME on subdomans and root domains.
> autodns: fixes wrong zone in api call if CNAME is used

- providers/dns/route53/route53.go
- providers/dns/route53/route53.toml
External ID property is useful when granting access to AWS resources to a third party : https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
Fixes #1919
> route53: pass ExternalID property to STS:AssumeRole API operation

- providers/dns/websupport/websupport.go
`internal.ParseError(resp)` always return an error, it cannot be nil.
> websupport: simplify errors

- acme/api/internal/sender/sender.go
Currently, the badNonce error handling relies on the status field in the problem object .  
From my understanding of the Problem Object spec ([rfc7807](https://datatracker.ietf.org/doc/html/rfc7807#section-3.1)), the status field is not necessarily required.  
This change uses the response status code if the problem object does not contain the status field.
> fix: read status code from response

- acme/commons.go
I detected a variation from the RFC: the RFC says `explanationURL` instead of `explanationUrl`.
`explanationURL` follows the same naming rule (commons Go initialism) as `certID`.
https://www.ietf.org/archive/id/draft-ietf-acme-ari-01.html#section-4.1
https://www.ietf.org/archive/id/draft-ietf-acme-ari-01.html#section-4.2
Related to #1912
> fix: ARI explanationURL

- go.mod
- go.sum
- providers/dns/cloudflare/cloudflare.go
- providers/dns/cloudflare/wrapper.go
I was having problems with lego yesterday - thought it might be because of the older `cloudflare-go` package.
Turns out - that wasn't it - it was API key shenanigans - but I thought maybe y'all would be interested in a library upgrade PR.
The tests pass:
```
=== RUN   TestNewDNSProvider
=== RUN   TestNewDNSProvider/success_email,_API_key
=== RUN   TestNewDNSProvider/success_API_token
=== RUN   TestNewDNSProvider/success_separate_API_tokens
=== RUN   TestNewDNSProvider/missing_credentials
=== RUN   TestNewDNSProvider/missing_email
=== RUN   TestNewDNSProvider/missing_api_key
--- PASS: TestNewDNSProvider (0.00s)
--- PASS: TestNewDNSProvider/success_email,_API_key (0.00s)
--- PASS: TestNewDNSProvider/success_API_token (0.00s)
--- PASS: TestNewDNSProvider/success_separate_API_tokens (0.00s) …
```
> cloudflare: update api client to v0.70.0

- challenge/dns01/cname.go
- challenge/dns01/cname_test.go
Fixes #1955 
Changes:
- Modified the `updateDomainWithCName` function in `cname.go` to use a case-insensitive comparison (`strings.EqualFold`). This allows the function to correctly identify the CNAME records irrespective of case.
- Added a new unit test `TestCnameCaseInsensitive` in `cname_test.go` to validate that the `updateDomainWithCName` function works correctly when the DNS record is in uppercase.
> fix: ensure case-insensitive comparison of CNAME records

- challenge/dns01/nameserver.go
Some networks block UDP packets. The ability to switch to TCP-only DNS queries will help a lot here.
`LEGO_EXPERIMENTAL_DNS_TCP_ONLY=true` to use TCP
https://community.traefik.io/t/docker-traefik-route53-dns-01-challenge-not-renewing-certificates/17463
> Experimental option to force DNS queries to use TCP

- .github/workflows/release.yml
- acme/api/internal/sender/useragent.go
During the release of v4.12.2 a problem about "no space left on device" appears for the first time https://github.com/go-acme/lego/actions/runs/5313815049
The problem happens during the build of the binaries: Go creates a lot a small artifacts during a build.
I was thinking that it's not really related to disk space but to inode, so I decreased the number of concurrent builds to 1.
And this fixed the problem for v4.12.3.
https://github.com/go-acme/lego/actions/runs/5316467651
Now the problem happens again with v4.13.0, I still think it's related to inode and the build artifacts.
https://github.com/go-acme/lego/actions/runs/5609596730/jobs/10263519288
I added a new step to the release process: [free-disk-space-ubuntu](https://github.com/marketplace/actions/free-disk-space-ubuntu).
Before …
> Prepare release v4.13.1

- providers/dns/servercow/internal/client.go
Fixes #1963
servercow doesn't seem to follow the standard about `Content-Type` header.
> Likewise, the "Content-Type" is explicitly specified here as "application/json"!
> --- https://cp.servercow.de/client/plugin/support_manager/knowledgebase/view/34/dns-api-v1/7/
> servercow: fix regression

- cmd/flags.go
- docs/data/zz_cli_help.toml
> Allow to set EAB kid and hmac via environment variables

- go.mod
It's better to use `exclude` directives instead of just adding a comment for an excluded version.
> chore: exclude egoscale v1.19.0

- .github/workflows/documentation.yml
- .github/workflows/go-cross.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- certificate/authorization.go
- certificate/certificates.go
- certificate/errors.go
- certificate/errors_test.go
- go.mod
- providers/dns/allinkl/internal/types_api.go
- providers/dns/ipv64/internal/client.go
- providers/dns/ipv64/internal/client_test.go
- providers/dns/ipv64/ipv64.go
- updates CI to use go1.20 and go1.21: uses the aliases `stable` and `oldstable` to avoid updating the branch protection each time there is a Go update.
- uses `errors.Join` to improve `obtainError`
https://tip.golang.org/doc/go1.20
Fixes #793
>  chore: update to go1.20

- docs/Makefile
- docs/go.mod
- docs/go.sum
- docs/hugo.toml
This PR changes: the way the documentation is created: `hugo-theme-learn` ist now pulled in as hugo module. This is the newer and more elegant way to use hugo theme components.
> doc: retrieve hugo-theme-learn as hugo module

- providers/dns/nearlyfreespeech/internal/client.go
- providers/dns/nearlyfreespeech/internal/client_test.go
This change fixes the issue where the path that was hashed was missing the initial slash. There is a bug in Golang's stdlib that surfaces when one uses `url.Parse` with a URL that has an empty path and no slash just after the domainname (https://golang.org/issue/58605). We add a workaround for that issue.
Also, this change adds a golden value test for the contents of the authentication header, to guard against changes caused by e.g. updates to Golang stdlib. Sadly, they will need updating if we make a deliberate change to the requests. I think they are still the best we can do without a reference implementation to compare against in a test.
Fixes #1998
> nearlyfreespeech: fix authentication

- go.mod
This reverts commit 01747e39cc77b5041cde93ca6bdb500710e58976.
Fixes #2002
> Revert "chore: exclude egoscale v1.19.0"

- providers/dns/gandiv5/gandiv5.go
- providers/dns/gandiv5/gandiv5.toml
- providers/dns/gandiv5/gandiv5_test.go
- providers/dns/gandiv5/internal/client.go
Closes #2006
https://api.gandi.net/docs/livedns/
> gandiv5: add Personal Access Token support

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_gandiv5.md
- docs/content/dns/zz_gen_ipv64.md
- providers/dns/ipv64/ipv64.go
- providers/dns/ipv64/ipv64.toml
`IPV64_SEQUENCE_INTERVAL` is unused.
> ipv64: remove unused option

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_otc.md
- providers/dns/otc/otc.go
- providers/dns/otc/otc.toml
OTC doesn't support creating multiple recordsets with the same name.
Therefore, we configure the OTC provider for the sequential challenge.
feat: added OTC_SEQUENCE_INTERVAL environment variable. The default
value is dns01.DefaultPropagationTimeout
closes #2021
> otc: sequential challenge 

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_azuredns.md
- providers/dns/azuredns/azuredns.go
- providers/dns/azuredns/azuredns.toml
- providers/dns/azuredns/azuredns_test.go
Hello,
After using `azuredns` new DNS provider, I figured out it could be really useful to manage which authentication methods to use, in order to configure more accurately the expected behavior.
Therefore, I have splited the `DefaultAzureCredential` by using the different Azure credential methods and added the possibility to disable some of them.
Note that for `NewManagedIdentityCredential` I added a timeout management as described in the [azidentity package documentation](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#example-NewChainedTokenCredential-ManagedIdentityTimeout)
Let me know if you want me to add anything.
Thanks.
> azuredns: provide the ability to select authentication methods

- providers/dns/gandiv5/gandiv5_test.go
- providers/dns/gandiv5/internal/client.go
The "Bearer" prefix is required per
https://api.gandi.net/docs/authentication/ to declare the content of the Authorization header as a personal access token.
Without this change, the user has to specify `GANDIV5_PERSONAL_ACCESS_TOKEN='Bearer 12341234'` instead of `GANDIV5_PERSONAL_ACCESS_TOKEN=12341234` which disagrees with the documentation and the existing test data.
This change is not backwards-compatible. This should be OK because the commit 113648a36817a5d9667b8dd1f1c6c67eeb914916 (#2007) which added support for personal access tokens was not in any release yet.
> gandiv5: Add "Bearer" prefix to the auth header

- providers/dns/nifcloud/internal/client.go
> nifcloud: fix API requests

- providers/dns/regru/internal/client.go
- providers/dns/regru/internal/types.go
http method GET is deprecated
https://www.reg.ru/reseller/api2doc#common_connection
so, we need to change it to POST
> regru: HTTP method changed to POST

- providers/dns/cloudru/internal/client.go
Changes:
- APIBaseURL changed: The variable has been changed because I was getting the RBAC access denied error. Technical support cloud.ru gave me an answer: "Danil, good afternoon! There is an error in our documentation, use the host console.cloud.ru instead of console.sbercloud.ru to send a request to the API." With the host console.cloud.ru the error is gone.
- AuthBaseURL changed: The old variable works too. But I think that soon they will completely migrate the host API from sbercloud.ru on cloud.ru .
> cloudru: change default URLs

- providers/dns/ionos/ionos.go
> ionos: fix DNS record removal

- providers/dns/inwx/inwx.go
- providers/dns/inwx/inwx_test.go
This is a workaround for #1608.  INWX forbids to re-use the same TOTP twice, but the INWX DNS provider tries to reauthenticate from scratch on each step.
I believe that this is not easily implementable with the existing Lego DNS provider interface, so to avoid refactoring that interaction, let's just make the INWX provider wait a bit until a new token is available.  A new token is available every 30 seconds.
The current workaround is to invoke Lego many more times.  Retrying at a higher level is worse than retrying here.
Fixes #1608
> inwx: wait before generating new TOTP TANs

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_gcloud.md
- providers/dns/gcloud/gcloud.toml
- providers/dns/gcloud/googlecloud.go
The GCloud IAM permission system permits a zone to grant access to an actor, without the project granting any access. This can be used with Service Accounts to let an SA edit DNS in one particular zone, and nothing more.
Remove the need for the caller to have project-level role access granting the dns.managedZones.list permission, in exchange for the caller telling us the explicit zone ID to use, via the GCE_ZONE_ID environment variable.
-----
PR comment: sorry, I'm going to need help figuring out the test rig and how to set it up to fail the managedzones list call but succeed on zone edits, to add a test for this logic.
PR comment 2: this is #2073 redone from a personal repo at the request of a member of go-acme/lego
> gcloud: support GCE_ZONE_ID to bypass zone list

- providers/dns/inwx/inwx.go
- providers/dns/inwx/inwx_test.go
https://github.com/go-acme/lego/pull/2084#discussion_r1458040487
<details>
```go
package foo
import (
"encoding/base32"
"testing"
"time"
"github.com/pquerna/otp/totp"
"github.com/stretchr/testify/assert"
"github.com/stretchr/testify/require"
)
func TestTOTP(t *testing.T) {
testCases := []struct {
desc     string
now      string
expected string
counter  string
}{
{
desc:     "TAN A",
now:      "2024-01-01T06:29:59Z",
expected: "801386",
counter:  "2024-01-01T06:29:30Z",
},
{
desc:     "TAN B [1]",
now:      "2024-01-01T06:30:00Z",
expected: "078251",
counter:  "2024-01-01T06:30:00Z",
},
{
desc:     "TAN B [2]",
now:      "2024-01-01T06:30:29Z",
expected: "078251",
counter:  "2024-01-01T06:30:00Z",
},
{
desc:     "TAN C [1]",
now:      "2024-01-01T06:30:30Z",
expected: "521951",
counter: …
```
> inwx: improve sleep calculation

- .golangci.yml
- README.md
- acme/commons.go
- certificate/renewal.go
- certificate/renewal_test.go
- cmd/cmd_renew.go
- docs/data/zz_cli_help.toml
- Implemented the updated CertID format as specified in draft-ietf-acme-ari-02.
- Removed the `--ari-hash-name` flag, which is no longer necessary with the updated format.
- Enabled ARI usage for users with `--no-bundle` option. Previously, this was not possible as the draft-ietf-acme-ari-01 format required metadata available only in the issuer.
---
ATTENTION: this must NOT be merged and should remain in draft until https://github.com/letsencrypt/boulder/pull/7184 is merged and deployed.
UPDATE: this change has been merged, but it will not be deployed to Production until a few days into the new year. I'll update this issue when that's the case.
> Update CertID format as per draft-ietf-acme-ari-02

- certcrypto/crypto.go
- certificate/certificates.go
- cmd/cmd_list.go
- cmd/cmd_renew.go
Let's encrypt will support certificates without common name starting at 2023-11-29. Details see in this [announcement](https://community.letsencrypt.org/t/simplifying-issuance-for-very-long-domain-names/207924). It allows to create certificates for domains longer than 64 characters without needing to set the common name to a shorter domain name. 
This PR makes small adjustments to the certificate ordering to reflect the new possibility. The common name is only set if the first domain name is shorter or equal than 64 characters. Therefore the change should be compatible with the current usage.
*Note: The new behaviour can already be tested on the staging server (https://acme-staging-v02.api.letsencrypt.org/directory)*
Fixes #2049
> feat: support simplified issuance for very long domain names at Let's Encrypt

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_pdns.md
- docs/data/zz_cli_help.toml
- providers/dns/pdns/internal/client.go
- providers/dns/pdns/internal/client_test.go
- providers/dns/pdns/pdns.go
- providers/dns/pdns/pdns.toml
- providers/dns/pdns/pdns_test.go
Some PowerDNS servers don't have exposed the [root API endpoints](https://doc.powerdns.com/recursor/common/api/endpoint-api.html) and PowerDNS API version auto-detection fails. Use the optional parameter `PDNS_CUSTOM_API_VERSION` to set the version number in such situations.
related to  #2016
> pdns: optional custom API version

- go.mod
- go.sum
- providers/dns/allinkl/internal/client.go
References:
- https://github.com/mitchellh/mapstructure/issues/349
- https://github.com/mitchellh/mapstructure/pull/328#issuecomment-1858922295
- https://www.theregister.com/2023/12/15/hashimoto_departs_hashicorp/
> chore: replace mitchellh/mapstructure by go-viper/mapstructure/v2

- docs/content/dns/zz_gen_route53.md
- providers/dns/route53/route53.toml
The example was missing the `lego` command.
> route53: fix example

- .github/workflows/pr.yml
- .golangci.yml
- acme/api/account.go
- certcrypto/crypto.go
- cmd/cmd_renew.go
- cmd/cmd_run.go
- go.mod
- go.sum
- platform/config/env/env_test.go
- providers/dns/alidns/alidns.go
- providers/dns/azuredns/oidc.go
- providers/dns/checkdomain/checkdomain.go
- providers/dns/cloudru/internal/client.go
- providers/dns/cpanel/cpanel.go
- providers/dns/designate/designate.go
- providers/dns/edgedns/edgedns.go
- providers/dns/googledomains/googledomains.go
- providers/dns/iij/iij.go
- providers/dns/loopia/loopia_mock_test.go
- providers/dns/mythicbeasts/internal/client.go
- providers/dns/nicmanager/nicmanager.go
- providers/dns/servercow/servercow.go
- providers/dns/transip/fakeclient_test.go
- providers/dns/vkcloud/vkcloud.go
- providers/dns/yandex/yandex.go
- providers/dns/yandexcloud/yandexcloud.go
- providers/http/memcached/memcached_test.go
- providers/http/s3/s3.go
- uses `slices.Contains`
- update linter to v1.56.0
https://tip.golang.org/doc/go1.21
> chore: update to go1.21

- .github/workflows/pr.yml
- providers/dns/ns1/ns1.go
Regression on the API client from a breaking change of the NS1 API client: https://github.com/ns1/ns1-go/pull/220
Same problem as https://github.com/ns1/ns1-go/pull/51
```
unable to generate a certificate for the domains [*.internal.redacted.com internal.redacted.com internal.redacted.com]:
error: one or more domains had a problem:
[*.internal.redacted.com] [*.internal.redacted.com] acme: error presenting token:
ns1: failed to create record [zone: \"internal.redacted.com\", fqdn: \"_acme-challenge.internal.redacted.com.\"]: PUT https://api.nsone.net/v1/zones/internal.redacted.com/_acme-challenge.internal.redacted.com/TXT: 400 Input validation failed (Value None for field '<obj>.tags' is not of type object)
[internal.redacted.com] [internal.redacted.com] acme: error presenting token:
ns1: …
```
> ns1: fix record creation

- providers/dns/easydns/easydns.go
- providers/dns/easydns/easydns_test.go
- providers/dns/easydns/internal/client.go
- providers/dns/easydns/internal/client_test.go
- providers/dns/easydns/internal/fixtures/error.json
- providers/dns/easydns/internal/fixtures/error1.json
- providers/dns/easydns/internal/fixtures/list-zone.json
- providers/dns/easydns/internal/readme.md
- providers/dns/easydns/internal/types.go
> easydns: fix zone detection

- cmd/cmd_renew.go
It doesn't fix the problem behind ARI but at least doesn't break the renewal for all users.
Related to #2137
> fix: don't generate ARI cert ID if ARI is not enable

- .github/workflows/release.yml
- .goreleaser.yml
- docs/content/installation/_index.md
The LEGO snap makes it easy to install and use LEGO on any Linux distribution that supports snaps. This PR adds the snap to go releaser to automatically build and publish the snap. 
```bash
sudo snap install lego
sudo lego \
--email="you@example.com" \
--domains="example.com" \
--server=https://acme-staging-v02.api.letsencrypt.org/directory \
--http \
--http.port :8080 \
run
```
**Note**: The LEGO snap can only write to the `/var/snap/lego/common/.lego` directory.
The snap is strictly confined, meaning it only has access to what it requires to work and for LEGO that means [network binding](https://snapcraft.io/docs/network-bind-interface). 
For the snap publishing to succeed, it will be necessary to do the following before merging this PR:
1. Create a snapcraft account
2. Make a request …
> chore: add snap to release packages

- CHANGELOG.md
- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_scaleway.md
- providers/dns/scaleway/scaleway.go
- providers/dns/scaleway/scaleway.toml
- providers/dns/scaleway/scaleway_test.go
The official Scaleway doc uses some env var naming: https://www.scaleway.com/en/developers/api/domains-and-dns/
To be less confusing for users, I added alternative env var names.
Related to #2135
> scaleway: add alternative env var names

- providers/dns/exec/exec.go
The command outputs will be displayed in realtime.
Fixes #2165
> exec: stream command output

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_ovh.md
- go.mod
- go.sum
- providers/dns/ovh/ovh.go
- providers/dns/ovh/ovh.toml
- providers/dns/ovh/ovh_test.go
The latest go-ovh version allows authentication using OAuth2 client_id and client_secret. Which in turn can be provisioned using the OVH terraform provider thus enabling everything to be configured as code.
I'm not usually writing code in Go so I'm not sure if everything is idiomatic. Please advice if something needs to be changed to be more in line with the rest of the code.
> ovh: add OAuth2 authentication

- providers/dns/exoscale/exoscale.go
Instead of updating a record, it always creates a new record.
To find the record to delete, the record value is used.
Fixes #2174
> exoscale: simplify record creation

- providers/dns/azuredns/azuredns.go
Users with several tenants should have a way to use a specific one for authentication.
Fixes #2178
> azuredns: use TenantID also for cli authentication

- docs/content/dns/zz_gen_godaddy.md
- providers/dns/godaddy/godaddy.toml
https://community.letsencrypt.org/t/getting-unauthorized-url-error-while-trying-to-get-cert-for-subdomains/217329/15
> godaddy: documentation new API limitations

- providers/dns/pdns/internal/client.go
- providers/dns/pdns/internal/client_test.go
As I was trying to both better understand the behavior and create a patch for myself that makes lego work for my DNS provider's API, I have implemented a fix for #2128 even as the discussion in the issue has not yet progressed any further. If you require further discussion before this PR should be considered, please let me know.
This corresponds to the first of the two solutions, that I've proposed in #2128. It replaces the usage of the (at least for my provider) absolute URL `zone.URL`, which resulted in incorrect URLs being used when the API endpoint is not located at the server's root, by relative URLs. AFAICS, these should now work in all cases (both if the API endpoint is located at the server's root and if it isn't).
The two added test cases for non-root API endpoints also …
> pdns: reconstruct zone URLs to enable non-root folder API endpoints

- certificate/authorization.go
- certificate/certificates.go
- cmd/flags.go
- cmd/setup.go
- docs/data/zz_cli_help.toml
- lego/client.go
- lego/client_config.go
> feat: add option to handle the overall request limit

- challenge/http01/domain_matcher.go
- lego/client_config.go
- providers/dns/acmedns/acmedns_test.go
Allow to reuse the way to create a certificates pool.
> feat: expose certificates pool creation

- docs/content/installation/_index.md
Adding note to cut down on hair pulling, by providing clarity into where exactly certificates are dropped.
> docs: add note about snap

- .goreleaser.yml
- go.mod
- go.sum
I removed Solaris during [v4.17.2](https://github.com/go-acme/lego/blob/master/CHANGELOG.md#v4172---2024-05-28) because of a problem with [flock](https://github.com/gofrs/flock/issues/60).
The problem with flock is now fixed https://github.com/gofrs/flock/releases/tag/v0.10.0
```bash
GOOS=solaris GOARCH=amd64 go build -o templego ./cmd/lego
```
> fix: restore Solaris

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_designate.md
- providers/dns/designate/designate.go
- providers/dns/designate/designate.toml
This is basically the same feature as in #1433 for the OpenStack Designate provider.
This solves problems that occur in situations like SplitDNS/Private DNS Zones where the automatic SOA detection might not work to the full extend. When setting the Zone Name via environment, it specifically uses this Zone Name when communicating with the Designate API. Otherwise, nothing changes.
> designate: allow manually overwriting DNS zone

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_bluecat.md
- providers/dns/bluecat/bluecat.go
- providers/dns/bluecat/bluecat.toml
> bluecat: skip deploy

- cmd/cmd_run.go
#2164 made the environment variable LEGO_ISSUER_CERT_PATH available to hook scripts but was isolated to the `renew` command. This PR extends that logic to the `run` command.
Related to #2164, #2160
> feat: add LEGO_ISSUER_CERT_PATH to run hook

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_cloudflare.md
- providers/dns/cloudflare/cloudflare.toml
Specify CLOUDFLARE additional configuration timeouts and intervals are in seconds
> cloudflare: update documentation to specify the unit of time-based options

- certificate/renewal.go
https://www.ietf.org/archive/id/draft-ietf-acme-ari-04.html#section-4.2 says:
> If the client receives no response or a malformed response (e.g. an end timestamp which is equal to or precedes the start timestamp), it SHOULD make its own determination of when to renew the certificate, and MAY retry the renewalInfo request with appropriate exponential backoff behavior.
Currently when lego encounters an ARI renewal window that specifies *"an end timestamp which is equal to or precedes the start timestamp"*, the following panic occurs:
```
panic: invalid argument to Int63n
goroutine 1 [running]:
math/rand.(*Rand).Int63n(0x0?, 0x0?)
math/rand/rand.go:122 +0xcb
math/rand.Int63n(0x0)
math/rand/rand.go:443 +0x25
github.com/go-acme/lego/v4/certificate.(*RenewalInfoResponse).ShouldRenewAt(0xc001608c …
```
> fix: avoid Int63n panic in ShouldRenewAt()

- docs/content/installation/_index.md
- lego is in official FreeBSD ports tree: https://www.freshports.org/security/lego
- use `pkg install` to install package
> docs: update installation for FreeBSD

- docs/content/installation/_index.md
- lego is in official OpenBSD ports tree https://openports.pl/path/security/lego
- install it with `pkg_add lego`
> docs: add installation for OpenBSD

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_dnshomede.md
- docs/content/dns/zz_gen_hurricane.md
- providers/dns/dnshomede/dnshomede.toml
- providers/dns/hurricane/hurricane.toml
This PR corrects a typo in the documentation for `dnshome.de` and `hurricane` providers, changing `Configuration.Addtional` to `Configuration.Additional`.
The incorrect key was preventing the "Additional Configuration" section from being generated correctly.
> docs: fix typos in some DNS descriptors

- cmd/flags.go
- cmd/setup_challenges.go
- docs/data/zz_cli_help.toml
The flags system doesn't allow having a "mixed" type flag (bool/duration): using `GenericFlag` doesn't work because you are forced to set a value, this means that using `--dns.disable-cp` without an explicit value will break.
So it's not possible to use `dns.disable-cp` to handle the wait.
Also the flag name `dns.disable-cp` is inaccurate because it will not disable all the propagation checks but only the checks on the nameservers.
Fixes #2030
> feat(cli): add dns.propagation-wait flag

- providers/dns/ionos/ionos.go
Ping @markusm7, can you run the command (with your domain, email, credentials, etc.)?
```bash
make build
rm -rf .lego
IONOS_API_KEY=xxxxxxxx \
./dist/lego -m your@email.com --dns ionos -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
Fixes https://github.com/go-acme/lego/discussions/2280
> ionos: follow CNAME

- challenge/dns01/precheck.go
- challenge/dns01/precheck_test.go
- cmd/flags.go
- cmd/setup_challenges.go
- docs/data/zz_cli_help.toml
- e2e/dnschallenge/dns_challenges_test.go
- deprecation of `dns.disable-cp`, replaced by `dns.propagation-disable-ans`.
- add `dns.propagation-rns` option to check all the authoritative nameservers.
Fixes #2276
> feat: add dns.propagation-rns option

- providers/dns/namesilo/namesilo.go
I restricted the `CleanUp` to only delete the record with a specific value instead of all TXT records.
Because of this restriction, it's useless to call the `CleanUp` during the `Present` because the value will never be the same.
Fixes #2286
Revert #1833
> namesilo: restrict CleanUp

- challenge/dns01/precheck.go
- cmd/setup_challenges.go
Replace the function `PropagationWaitOnly` with `PropagationWait`.
It's not a breaking change because #2266 is not a part of a release.
> feat: add PropagationWait function

- challenge/dns01/nameserver.go
When a large number of applications are made, there will be a large number of lock seizures and lower performance
> perf: reducing the lock strength of the soa cache entry

- providers/dns/selectelv2/selectelv2.go
- use `config.BaseURL` instead of the hardcoded one
- use a more "standard" use agent
> selectelv2: use baseURL from configuration

- docs/content/dns/zz_gen_epik.md
- docs/data/zz_cli_help.toml
- providers/dns/epik/epik.toml
- providers/dns/epik/internal/client.go
> epik: add User-Agent

- challenge/dns01/precheck.go
Wraps the errors to know the sources of errors.
> feat: improve propagation check error messages

- providers/dns/volcengine/volcengine.go
> volcengine: set API information within the default configuration

- README.md
- internal/dns/docs/generator.go
- internal/dns/docs/readme.md.tmpl
This changes the provider table generator to output an HTML table directly, instead of writing Markdown markup.
This is mostly an attempt of keeping future PRs introducing new providers a little less noisy. Since the provider entries are now strictly stacked vertically in the markup (i.e. at most one provider per line), adding another one in the middle will at worst shuffle the `</tr><td>` tags around.
As a nifty side-effect, this also eliminates the empty header row:
<details><summary>before</summary>
</details>
<details open><summary>after</summary>
</details>
> chore: update readme generator

- internal/dns/docs/readme.md.tmpl
If the number of providers is odd then it generates non-empty cells:
```
<td><a href="https://go-acme.github.io/lego/dns//"></a></td>
```
https://github.com/go-acme/lego/pull/1967/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> chore: fix readme generator

- cmd/setup_challenges.go
Current log output in `setup_challenges.go` looks like this:
```
Nov 01 01:05:07 xxx lego[1548788]: 2024/11/01 01:05:07 The flag '%s' is deprecated use '%s' instead. dns.disable-cp dns.propagation-disable-ans
```
This MR fixes the output.
> fix: Parse printf verbs in log line output

- README.md
- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_brandit.md
- providers/dns/brandit/brandit.toml
Brandit has been acquired by Abion.
Related to #2105
---
Waiting for the merge of #2112
> brandit: provider deprecation

- cmd/flags.go
- cmd/setup.go
- docs/data/zz_cli_help.toml
Adds an option to skip the TLS verification of the ACME server.
Fixes https://github.com/go-acme/lego/discussions/2334
> feat: skip the TLS verification of the ACME server

- docs/content/usage/cli/Options.md
Adds the missing doc of the options managed only through env vars.
> docs: add documentation for env var only options

- docs/content/dns/zz_gen_cloudflare.md
- providers/dns/cloudflare/cloudflare.toml
The least privilege instructions for setting up Cloudflare API keys were over-granting permissions. This would allow lego to read all the zones in the account. This was unnecessary. It only requires read access to the individual zones.
Closes #2048
---
note - I'm unsure if this is the correct file to edit, or if it's the docs file (or both)
> docs: update least privilege instructions for Cloudflare

- cmd/cmd_renew.go
- docs/data/zz_cli_help.toml
With [draft-ietf-acme-ari](https://datatracker.ietf.org/doc/draft-ietf-acme-ari/) now in IETF Working Group Last Call—the final step before becoming an RFC—it is reasonable to enable ARI checks by default.
> feat: attempt to check ARI unless explicitly disabled

- challenge/http01/domain_matcher.go
- challenge/http01/domain_matcher_test.go
- challenge/http01/http_challenge_server.go
> fix: HTTP server IPv6 matching

- .goreleaser.yml
The problem was the command path.
Related to #2134
> chore: restore snap packaging

- .goreleaser.yml
I feel (I didn't test it) like I should follow the same configuration as goreleaser:
https://github.com/goreleaser/goreleaser/blob/efe8b7089e55ac2de54238b699f2ba18cc339d5f/.goreleaser.yaml#L353C12-L354C85
> chore: fix snap name

- providers/dns/technitium/internal/client.go
The status code 400 was not included in the error detection.
> technitium: fix status code handling

- CHANGELOG.md
- acme/api/internal/sender/useragent.go
- cmd/lego/zz_gen_version.go
- providers/dns/internal/useragent/useragent.go
It's mainly to test the publication of the snap and the AUR.
> Prepare release v4.20.3

- cmd/cmd_renew.go
Closes #1532
When changing the --domains values, the certificate will not be refreshed to update the SANs appropriately.
This change introduces a simple flag to check + enforce that the domains specified match exactly those in the certificate during renewal.
I couldn't see a straightforward way to contribute a unit test for this, but I performed a full integration test using the NixOS ACME integration test suite. You can run that test locally with this command:
`nix run github:m1cr0man/nixpkgs/lego-domain-testing#nixosTests.acme`
> feat: add --force-cert-domains flag to renew

- cmd/setup.go
Clone and modify the transport instead of overriding the transport.
> fix(cli): clone the transport with tls-skip-verify

- .golangci.yml
- cmd/cmd_renew.go
- cmd/cmd_revoke.go
- cmd/cmd_run.go
- cmd/setup.go
> fix(cli): create client only when needed

- providers/dns/inwx/inwx.go
The original implementation deleted all TXT records on the domain. That was not very nice. I took the way the IONOS Implementation is done to only delete the newly generated DNS Challenge records.
> inwx: delete only the TXT record related to the DNS challenge

- cmd/cmd_renew.go
- cmd/cmd_run.go
- cmd/hook.go
- docs/data/zz_cli_help.toml
Add the option `--run-hook-timeout` and `--renewal-hook-timeout` which lets you configure how long lego should wait for the hook to finish. The default of `120` seconds may be too short in some cases.
Background:
We have a setup in which we run lego periodically with a systemd service/timer combo.
When we execute the run/renewal hook we have multiple tasks which we would execute with the hook script, those tasks may in some cases exceed the 120s timeout. The option added in this PR lets us configure this timeout and successfully finish all tasks with the script.
> feat: add hook-timeout to run and renew commands

- cmd/flags.go
Extend the use of LEGO_EMAIL in the renew command to all uses of the --email flag
> cli: add environment variable for specifying email

- cmd/setup.go
The logger of the retryable client needs to be explicitly set to nil to avoid extra debug logs.
<details>
```console
2025/01/28 02:55:19 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2025/01/28 02:55:19 [DEBUG] POST https://acme-staging-v02.api.letsencrypt.org/acme/new-order
2025/01/28 02:55:19 [DEBUG] POST https://acme-staging-v02.api.letsencrypt.org/acme/authz/182137934/15857393534
2025/01/28 02:55:20 [DEBUG] HEAD https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce
2025/01/28 02:55:20 [DEBUG] POST https://acme-staging-v02.api.letsencrypt.org/acme/authz/182137934/15857393544
2025/01/28 02:55:20 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/182137934/15857393534
2025/01/28 02:55:20 [INFO] [example.com] …
```
> fix(cli): remove extra debug logs

- certificate/authorization.go
- cmd/cmd_run.go
- cmd/setup.go
- docs/content/usage/cli/Options.md
- e2e/challenges_test.go
- e2e/dnschallenge/dns_challenges_test.go
Adds `LEGO_DEBUG_ACME_HTTP_CLIENT` to debug the calls to the ACME server.
> feat(cli): add LEGO_DEBUG_ACME_HTTP_CLIENT to debug the calls to the ACME server

- certcrypto/crypto.go
- certcrypto/crypto_test.go
- certificate/certificates.go
- e2e/challenges_test.go
> feat: option to set CSR emails

- docs/content/dns/zz_gen_liara.md
- providers/dns/liara/internal/client.go
- providers/dns/liara/liara.toml
Hello,
The documentation link for the Liara DNS provider has changed from https://dns-service.iran.liara.ir/swagger to https://openapi.liara.ir/?urls.primaryName=DNS. I have updated the link and submitted a pull request.
I would appreciate it if you could review and consider the update.
Thank you!
> chore: update links of liara provider API doc

- providers/dns/acmedns/acmedns.go
- providers/dns/acmedns/internal/http_storage.go
- providers/dns/acmedns/internal/http_storage_test.go
- providers/dns/acmedns/internal/readme.md
This allows the HTTP storage server to control the CNAME creation.
if the `Put` returns a 201, lego expects the CNAME to be created automatically by the server.
Closes #2436
> acme-dns: allow the HTTP storage server to create the CNAME

- README.md
- cmd/zz_gen_cmd_dnshelp.go
- docs/content/_index.md
- docs/content/dns/zz_gen_acme-dns.md
- providers/dns/acmedns/acmedns.go
- providers/dns/acmedns/acmedns.toml
- providers/dns/acmedns/acmedns_test.go
- fix `storage.NewFile(values[EnvStoragePath], 0o600)` (`values[EnvStoragePath]` doesn't exist)
- add `ACME_DNS_ALLOWLIST`
- rewrite constructors to follow the same design as the other implementations.
> acme-dns: fix file path

- providers/dns/acmedns/acmedns.go
https://github.com/go-acme/lego/pull/2437#issuecomment-2663309250
> acme-dns: continue the process when the CNAME is handled by the storage

- acme/api/order_test.go
- certcrypto/crypto_test.go
- challenge/dns01/dns_challenge_test.go
- challenge/http01/http_challenge_test.go
- challenge/resolver/solver_manager_test.go
- challenge/tlsalpn01/tls_alpn_challenge_test.go
- go.mod
- lego/client_test.go
- providers/dns/hyperone/internal/token_test.go
- providers/dns/oraclecloud/oraclecloud_test.go
- registration/registar_test.go
The tests have been updated because go1.24 will produce an error with a bit size lower than 1024.
https://go.dev/doc/go1.24#cryptorsapkgcryptorsa
The behavior can be tested by adding the following line inside the `go.mod`:
```
godebug rsa1024min=1
```
> chore: use go1.23

- .golangci.yml
- cmd/cmd_renew.go
- providers/dns/cloudflare/cloudflare.go
- providers/dns/netcup/netcup.go
- providers/dns/shellrent/shellrent.go
> fix: malformed log messages

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_infoblox.md
- providers/dns/infoblox/infoblox.go
- providers/dns/infoblox/infoblox.toml
The infloblox client uses a weird option: `SSLVerify` can be a boolean or a path to a CA certificate...
https://github.com/infobloxopen/infoblox-go-client/blob/de49b186dc041882af6e6c8e0823c27f103509c8/connector.go#L45-L70
> feat: add INFOBLOX_CA_CERTIFICATE option

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_edgedns.md
- providers/dns/edgedns/edgedns.go
- providers/dns/edgedns/edgedns.toml
- providers/dns/edgedns/edgedns_test.go
An Akamai EdgeDNS API client may have permission to manage multiple accounts. In such cases, specifying an account switch key allows the API client to edit DNS zones belonging to other Akamai accounts. Support for this account switch key has been implemented.
ref. https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client
> edgedns: add account switch key option

- cmd/hook.go
- cmd/hook_test.go
- cmd/testdata/sleeping_beauty.sh
- cmd/testdata/sleepy.sh
The `context.WithTimeout` doesn't kill a command when the command is stuck because `CombinedOutput` is waiting for a "pause".
The previous implementation was able to stop the hook if the script was too long, but not stuck on one element (cf test: `sleepy.sh`).
But it was not able to stop the hook if the script was waiting for a long (never-ending) process (cf test: `sleeping_beauty.sh`).
I modified the code to add a timer that kills the current process if the timeout is reached.
This implementation has another advantage: the output of the hook will be live streamed to the console.
Fixes #2468
> fix: kill hook when the command is stuck

- cmd/hook.go
- cmd/hook_test.go
In fact, we don't need a timer, a go routine on `context.DOne()` is enough.
Related to #2469
> chore: related timer with context.Done

- acme/api/internal/sender/sender.go
- acme/api/order.go
- acme/api/order_test.go
- acme/errors.go
Fixes #2474
related to https://github.com/aarongable/draft-acme-ari/issues/56
> fix: retry on alreadyReplaced error

- challenge/dns01/nameserver_test.go
`physics.georgetown.edu.` has changed a nit their NS: "ns.b1ddi.physics.georgetown.edu.", "ns4.georgetown.edu.", "ns5.georgetown.edu.", "ns6.georgetown.edu."
So I switch to more stable NS.
> tests: change ns

- certcrypto/crypto_test.go
When comparing RSA private keys we want to assert equality based on the core values of the key, not any precomputed intermediaries held for optimization purposes.
This is the job of [`rsa.PrivateKey.Equal`]( https://pkg.go.dev/crypto/rsa@master#PrivateKey.Equal), so we employ that in `TestParsePEMPrivateKey` in place of a deep field-by-field comparison.
Prior to this change running the test with Go 1.24+ and `-count=100` would reliably produce ~2-3 failures out of the 100. With this change in place we can increase to even `-count=1000` without any failures.
> certcrypto: compare RSA priv keys ignoring precomputed

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_route53.md
- providers/dns/route53/route53.go
- providers/dns/route53/route53.toml
- providers/dns/route53/route53_test.go
Fixes #2161
https://github.com/go-acme/lego/issues/2161#issuecomment-2735892554
> route53: adds option to use private zone

- providers/dns/allinkl/internal/client.go
- providers/dns/allinkl/internal/client_test.go
- providers/dns/allinkl/internal/types_api.go
The type of `ReturnInfo` doesn't seem "stable".
allinkl doesn't have a real API schema: https://kasapi.kasserver.com/soap/wsdl/KasApi.wsdl
```xml
<message name="KasApiAntwort">
<part name="Result" type="xsd:anyType"/>
</message>
```
```
2025/03/20 12:54:56 [WARN] [*.example.com] acme: cleaning up failed: allinkl: response struct decode: decoding failed due to the following error(s):
'Response.ReturnInfo' expected type '%!s(bool=false)', got unconvertible type '""', value: '""'
```
Related to #2489
> allinkl: remove ReturnInfo

- providers/dns/designate/designate.go
When searching for an object in OpenStack we can let the API do the heavy lifting by applying filters (i.e. ListOpts). This helps speeding up the API requests for projects that have a large number of zones or zones that have a large number of records.
---
In a larger test project this speeds up the API calls from about 30s to 1.5s for filtered vs unfiltered API calls.
> designate: speed up API requests by using filters

- providers/dns/pdns/pdns.go
- providers/dns/pdns/pdns_test.go
When using the pdns backend, using a domain and a wildcard domain at the same time (example.com, *.example.com) means cleanup wasn't successful because it was trying to DELETE all the TXT records even though its only supposed to delete 1 challenge at a time.
> pdns: fix TXT record cleanup for wildcard domains

- CHANGELOG.md
- acme/api/internal/sender/useragent.go
- cmd/lego/zz_gen_version.go
- providers/dns/internal/useragent/useragent.go
First failure:
```
• docker images
⨯ release failed after 55m5s              
error=
│ docker build failed: failed to copy artifact: failed to copy: write /tmp/goreleaserdocker2826257344/lego: copy_file_range: no space left on device
│ Learn more at https://goreleaser.com/errors/docker-build
```
I cleaned the cache, and second failure:
```
⨯ release failed after 59m10s             
error=
│ 1 error occurred:
│ 	* snapcraft packages: failed to push dist/lego_386.snap package: exit status 1: Exported credentials are no longer valid for the Snap Store.
│ Recommended resolution: Run export-login and update SNAPCRAFT_STORE_CREDENTIALS.
│ For more information, check out: https://snapcraft.io/docs/snapcraft-authentication
│ Full execution log: …
```
> Prepare release v4.23.1

- providers/dns/cloudflare/cloudflare.go
Cloudflare changed their [TXTRecord API Type](https://developers.cloudflare.com/api/resources/dns/subresources/records/models/txt_record/#(schema))'s `content` property. The new wording states: 
> Text content for the record. The content must consist of quoted "character strings" (RFC 1035), each with a length of up to 255 bytes. Strings exceeding this allowed maximum length are automatically split. 
On their dashboard, they automatically add quotation marks, if the user does not already do so.
This behavior, however, is not present in their API. Therefore, all TXT records added via their API, need to have their content wrapped manually; otherwise, Cloudflare will display a warning for each record about the missing quotation marks.
> cloudflare: add quotation marks to TXT record

- go.mod
- go.sum
- providers/dns/dnsimple/dnsimple.go
- providers/dns/namedotcom/namedotcom.go
- providers/dns/selectelv2/selectelv2.go
**github.com/dnsimple/dnsimple-go**
- https://github.com/dnsimple/dnsimple-go/compare/v1.7.0...v4.0.0
- https://github.com/dnsimple/dnsimple-go/tags
**github.com/namedotcom/go**
- https://github.com/namedotcom/go/compare/08470befbe04...v4.0.2
- https://github.com/namedotcom/go/tags
**github.com/selectel/go-selvpcclient**
- https://github.com/selectel/go-selvpcclient/compare/v3.2.1...v4.1.0
- https://github.com/selectel/go-selvpcclient/tags
**Not inside this PR**
- `github.com/gophercloud/gophercloud/v2` (because the [selectel client](https://github.com/selectel/go-selvpcclient/pull/177) must updated before)
- `github.com/akamai/AkamaiOPEN-edgegrid-golang/v10` (because it needs a dedicated PR)
---
<details>
Data from https://github.com/ldez/gomodcachesize.
Cache before (`go mod download`): …
> chore: bump dnsimple, namedotcom, and selectel to major versions

- providers/dns/pdns/pdns.go
> pdns: improve error messages

- docs/content/dns/zz_gen_cpanel.md
- providers/dns/cpanel/cpanel.toml
Adds missing `\` inside cPanel examples.
> docs(cPanel): fix examples

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_azion.md
- providers/dns/azion/azion.go
- providers/dns/azion/azion.toml
* Add pagination support for Azion DNS record lookup with a configurable page size to fix zones with a large number of records.
* Ordering environment variable equal to auto-generated files
> azion: add pagination support

- go.mod
- go.sum
- providers/dns/oraclecloud/configprovider.go
- providers/dns/oraclecloud/oraclecloud.go
- providers/dns/oraclecloud/oraclecloud_test.go
I created a fork of oci-go-sdk, this fork is maintained by a script, no manual hacks.
- https://github.com/nrdcg/oci-go-sdk
I used [gomodcachesize](https://github.com/ldez/gomodcachesize) to compute the sizes.
Currently `github.com/oracle/oci-go-sdk/v65@v65.87.0` uses 109.858 MiB.
With my fork:
- `github.com/nrdcg/oci-go-sdk/dns/v1065@v1065.95.0`: 877.271 KiB
- `github.com/nrdcg/oci-go-sdk/common/v1065@v1065.95.0`: 704.420 KiB
The size of the GOCACHE for this module is divided by 100.
It will allow us to avoid "no space left on device" during releases.
Note: this doesn't change the binary size.
Related to https://github.com/oracle/oci-go-sdk/issues/255
> oraclecloud: replace oci-go-sdk by a modular fork

- providers/dns/azion/azion.go
- providers/dns/azion/azion_test.go
- providers/dns/azion/fixtures/zones.json
- providers/dns/azion/fixtures/zones_empty.json
> azion: improve zone lookup

- cmd/cmd_renew.go
- cmd/cmd_renew_test.go
- docs/data/zz_cli_help.toml
Adds a new flag `--dynamic` for the `renew` command: dynamically defines the renewal date.
- 1/3rd of the lifetime left
- or 1/2 of the lifetime left, if the lifetime is shorter than 10 days)
The flag `--dynamic` overrides the flag `--days`.
Fixes #2572
> feat: add option to define dynamically the renew date

- cmd/zz_gen_cmd_dnshelp.go
- docs/content/dns/zz_gen_vinyldns.md
- providers/dns/vinyldns/vinyldns.go
- providers/dns/vinyldns/vinyldns.toml
**Description**
This PR adds quotes to DNS records to ensure Route53 compatibility during the DNS-01 ACME/Let's Encrypt validation process.
**Problem**
The current code didn't include quotes in DNS record values, causing DNS-01 challenge failures when used with Route53. Route53 has specific formatting requirements that require certain values to be quoted.
> vinyldns: add an option to add quotes around the TXT record value

- go.mod
- go.sum
- providers/dns/tencentcloud/tencentcloud.go
- providers/dns/tencentcloud/wrapper.go
This is a special fork: the methods of the structure `Client` are converted to functions that use `Client` as a parameter.
The goal is to break the link between the `Client` structure and the other structures to reduce the binary size.
This automatic approach for the fork is possible because the official `tencentcloud-sdk-go` library is 100 % generated.
https://github.com/go-acme/tencentclouddnspod
| Version  | Size inside the binary | Module size (`GOCACHE`) |
|----------|------------------------|-------------------------|
| official | 3.9 MB                 | 1.1 MB                  |
| fork     | 183 kB                 | 1.1 MB                  |
> tencentcloud: replace tencentcloud-sdk-go with a fork

- go.mod
- go.sum
- providers/dns/alidns/alidns.go
This is a special fork: the methods of the structure `Client` are converted to functions that use `Client` as a parameter.
The goal is to break the link between the `Client` structure and the other structures to reduce the binary size.
This automatic approach for the fork is possible because the official `alidns-20150109` library is 100 % generated.
https://github.com/go-acme/alidns-20150109
| Version  | Size inside the binary | Module size (`GOCACHE`) |
|----------|------------------------|-------------------------|
| official | 4.6 MB                 | 2.04 MiB                |
| fork     | 112 kB                 | 2.04 MiB                |
The cache size has been reduced from 88.654 MiB to 2.04 MiB inside https://github.com/go-acme/lego/pull/2558
> alidns: replace alidns-20150109 with a fork

- .golangci.yml
- providers/dns/huaweicloud/huaweicloud.go
- providers/dns/huaweicloud/internal/client.go
Same problem as alidns or dnspod, the client depends on too many structures.
The client is 100% generated code, but the huaweicloud client can be easily recreated without forking.
The client methods contain only plumbing, and it's always the same pattern.
We still depend on the official client, so we will receive the benefits of bug fixes but without the binary cost.
| branch | Size inside the binary |
|--------|------------------------|
| master | 1.1 MB                 |
| PR     | 259 kB                 |
> huaweicloud: lightweight client

- cmd/flags.go
- docs/data/zz_cli_help.toml
Related to a wrong copy/paste and replace: I used the name of the flag as env var name.
> fix: remove wrong env var

- acme/api/certificate.go
- acme/api/certificate_test.go
- acme/api/order_test.go
- certificate/certificates_test.go
- certificate/renewal_test.go
- challenge/dns01/dns_challenge_test.go
- challenge/http01/http_challenge_test.go
- challenge/resolver/prober_test.go
- challenge/resolver/solver_manager_test.go
- challenge/tlsalpn01/tls_alpn_challenge_test.go
- lego/client_test.go
- platform/tester/api.go
- providers/dns/constellix/internal/domains_test.go
- providers/dns/constellix/internal/fixtures/domains-GetAll.json
- providers/dns/constellix/internal/fixtures/domains-Search.json
- providers/dns/gcloud/googlecloud_test.go
- providers/dns/servercow/internal/client_test.go
- registration/registar_test.go
- Replaces test domains with `.example.` domains
- Uses the servermock system outside DNS providers
When I was updating tests with the new servermock system, I found a weird element:
```go
// Get issuerCert from bundled response from Let's Encrypt
// See https://community.letsencrypt.org/t/acme-v2-no-up-link-in-response/64962
_, issuer := pem.Decode(cert)
if issuer != nil {
```
The `if` is always `true` because `issuer` is a `[]byte`.
I wanted to fix that, so I read the reference inside the comment: https://community.letsencrypt.org/t/acme-v2-no-up-link-in-response/64962
And in ACME v2, there is no `up` link for the issuer.
- https://www.rfc-editor.org/rfc/rfc8555.html#section-7.4.2
> chore: clean up tests and code

- acme/api/certificate_test.go
- acme/api/internal/nonces/nonce_manager_test.go
- acme/api/internal/secure/jws_test.go
- acme/api/internal/sender/sender.go
- acme/api/internal/sender/sender_test.go
- acme/api/order_test.go
- certificate/certificates_test.go
- certificate/renewal_test.go
- challenge/dns01/dns_challenge_test.go
- challenge/http01/http_challenge_test.go
- challenge/resolver/solver_manager_test.go
- challenge/tlsalpn01/tls_alpn_challenge_test.go
- lego/client_test.go
- platform/tester/api.go
- platform/tester/servermock/builder.go
- registration/registar_test.go
Related to https://datatracker.ietf.org/doc/html/rfc8555#section-6.1
> fix: enforce HTTPS to the ACME server

- acme/api/certificate_test.go
- acme/api/internal/nonces/nonce_manager_test.go
- acme/api/internal/secure/jws_test.go
- acme/api/order_test.go
- certificate/certificates_test.go
- certificate/renewal_test.go
- challenge/dns01/dns_challenge_test.go
- challenge/http01/http_challenge_test.go
- challenge/resolver/solver_manager_test.go
- challenge/tlsalpn01/tls_alpn_challenge_test.go
- lego/client_test.go
- platform/tester/api.go
- platform/tester/servermock/builder.go
- registration/registar_test.go
I'm not happy with the signature of the method `BuildHTTPS`.
`Build` and `BuildHTTPS` should have the same signature.
> tests: change the signature of the method BuildHTTPS

- CHANGELOG.md
- acme/api/internal/sender/useragent.go
- cmd/lego/zz_gen_version.go
- providers/dns/internal/useragent/useragent.go
**IMPORTANT**
The 2 commits must be kept: the merge must be done with a **rebase** (neither merge commit nor squash)
2 commits:
> Prepare release v4.25.2

- providers/dns/simply/internal/client.go
- providers/dns/simply/internal/client_test.go
- providers/dns/simply/simply.toml
<details><summary>How to test this PR?</summary>
1. You need [Go](https://go.dev/doc/install)
2. Check out the PR:
```bash
git clone https://github.com/ldez/lego.git
cd lego
git checkout feat/dns/simply/api-v2
```
3. Compile lego:
- if you have `make`: `make build`
- if you don't make `make`: `go build -o dist/lego ./cmd/lego`
4. Run the following command with your information (email, domain, credentials):
```bash
SIMPLY_ACCOUNT_NAME=xxx \
SIMPLY_API_KEY=xxx \
./dist/lego -m your_email@example.com --dns simply -d '*.example.com' -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
**The wildcard domain is important**
5. Before each run of the command, you should clean your local environment:
```bash
rm -rf .lego
```
</details>
Fixes #2630
> simply: update to API v2
